# Generated by Django 3.2.6 on 2023-03-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_schema", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualUICOverride",
            fields=[
                (
                    "serial",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Aircraft Serial Number",
                    ),
                ),
                (
                    "uic",
                    models.CharField(
                        max_length=6, verbose_name="Unit Identification Code"
                    ),
                ),
            ],
        ),
    ]
