# Generated by Django 4.2.2 on 2025-01-14 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0031_merge_20240725_1331"),
        ("agse", "0006_alter_agse_field_sync_status_and_more"),
        ("aircraft", "0045_aircraft_equipment_number_and_more"),
        ("uas", "0011_historicaluav_equipment_number_uav_equipment_number"),
        ("supply", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisionalStock",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "dodaac",
                    models.CharField(blank=True, max_length=6, verbose_name="Department of Defense unit, activity"),
                ),
                (
                    "gcss_internal_material_number",
                    models.CharField(max_length=18, verbose_name="Foreign key, connects source datasets together"),
                ),
                (
                    "plant",
                    models.CharField(
                        max_length=4, verbose_name="Indicates whether storage SLOC is a unit's local sloc or an SSA."
                    ),
                ),
                (
                    "mrp_area_id",
                    models.CharField(max_length=10, verbose_name="Areas which refer to provisional storage locations"),
                ),
                ("storage_location", models.CharField(max_length=4, verbose_name="Where the stock is being stored")),
                ("total_stock", models.FloatField(verbose_name="Total Stock")),
                ("serviceable_stock", models.FloatField(verbose_name=" Stock that is ready for use")),
                (
                    "non_serviceable_stock",
                    models.FloatField(verbose_name="Stock that is not ready for use in its current condition"),
                ),
                (
                    "num_serviceable_zero_balance_batches",
                    models.IntegerField(verbose_name="number of serviceable batches that have no stock "),
                ),
                (
                    "num_non_serviceable_zero_balance_batches",
                    models.IntegerField(verbose_name="number of non-serviceable batches with no stock"),
                ),
                (
                    "batches",
                    models.JSONField(
                        verbose_name="list that classify the physical state or serviceability of equipment or supplies"
                    ),
                ),
                ("serviceable_batches", models.JSONField(verbose_name="list of serviceable batches")),
                ("non_serviceable_batches", models.JSONField(verbose_name="list of non serviceable batchesd")),
                ("num_batches", models.IntegerField(verbose_name="Number of batches")),
                ("num_serviceable_batches", models.IntegerField(verbose_name="The number of serviceable batches ")),
                (
                    "num_non_serviceable_batches",
                    models.IntegerField(verbose_name="The number of non serviceable batches"),
                ),
                ("is_bench_stock", models.BooleanField(verbose_name="Bench or Stock")),
                (
                    "storage_bin",
                    models.CharField(max_length=10, verbose_name="Sub-location within a larger storage location"),
                ),
                (
                    "sloc_class",
                    models.CharField(max_length=4, null=True, verbose_name="Storage location classification"),
                ),
                ("sloc_types", models.JSONField(verbose_name="Storage Location types")),
                (
                    "sloc_fe_abbr",
                    models.CharField(
                        max_length=12, null=True, verbose_name="Force element and associated storage location name"
                    ),
                ),
                (
                    "sloc_fe_name",
                    models.CharField(
                        max_length=40, null=True, verbose_name="Force element and associated storage location name"
                    ),
                ),
                (
                    "ric",
                    models.CharField(
                        max_length=3, verbose_name="Unit's SSA that has to retrograde items to support_ric"
                    ),
                ),
                ("support_ric", models.CharField(max_length=3, verbose_name="Unit's installation SSA")),
                (
                    "sloc_description",
                    models.CharField(max_length=16, verbose_name="Description of the storage location"),
                ),
                (
                    "derived_dodaac",
                    models.CharField(
                        max_length=6, null=True, verbose_name="The dodaac dervied from the sloc_fe_name column"
                    ),
                ),
                ("mrp_type", models.CharField(max_length=2, verbose_name="MRP type")),
                ("reorder_point", models.FloatField(verbose_name="Reorder point")),
                ("safety_stock", models.FloatField(verbose_name="Safety Stock")),
                ("has_storage_bin", models.BooleanField(verbose_name="Calculated field")),
                ("is_shop_stock", models.BooleanField(verbose_name="Calculated field")),
                ("is_authorized", models.BooleanField(verbose_name="Calculated field")),
                ("authorized_stock", models.FloatField(verbose_name="Stock a unit is authorized to have ")),
                (
                    "material_number",
                    models.CharField(max_length=23, verbose_name="Number identifying what the component is"),
                ),
                (
                    "material_number_type",
                    models.CharField(max_length=15, null=True, verbose_name="The type of material number"),
                ),
                (
                    "material_description",
                    models.CharField(max_length=45, null=True, verbose_name="Description of the component"),
                ),
                (
                    "line_item_number",
                    models.CharField(
                        max_length=6, verbose_name="Identifies the generic nomenclature of equipment item"
                    ),
                ),
                (
                    "material_number_with_fsc",
                    models.CharField(max_length=24, verbose_name="Material number with four digit FSC"),
                ),
                (
                    "material_number_with_fsc_type",
                    models.CharField(max_length=13, null=True, verbose_name="Material number + 4 digit FSC type"),
                ),
                ("recovery_code", models.CharField(max_length=1, verbose_name="Recovery code")),
                ("unit_price", models.FloatField(verbose_name="How much the part cost")),
                (
                    "unserviceable_credit_value",
                    models.FloatField(verbose_name="Credit received when turning in a unserviceable part"),
                ),
                (
                    "serviceable_credit_value",
                    models.FloatField(verbose_name="Credit received when turning in a usable part"),
                ),
                (
                    "serviceable_exchange_credit_price",
                    models.FloatField(verbose_name="Credit received when exchanging repairable part for another"),
                ),
                ("sc_name", models.CharField(max_length=17, null=True, verbose_name="Physical installation location")),
                (
                    "total_stock_valuation",
                    models.FloatField(verbose_name="Calculated field - total_stock times the unit_price"),
                ),
                (
                    "stock_id",
                    models.CharField(
                        max_length=28,
                        verbose_name="Concatenated field- gcss_internal_material_number + plant + storage_location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("requisition_number", models.CharField(max_length=10, verbose_name="Purchase Requisition Number")),
                (
                    "requisition_item_number",
                    models.CharField(max_length=3, verbose_name="Purchase Requisition Item Number"),
                ),
                (
                    "storage_location",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Ordering Storage Location"),
                ),
                (
                    "requisition_status",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Requisition Status"),
                ),
                ("requisition_material_number", models.CharField(max_length=20, verbose_name="Requisitioned NIIN")),
                (
                    "requisition_material_description",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Requisitioned material description"
                    ),
                ),
                (
                    "requisition_federal_supply_class_code",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Requisitioned FSC Code"),
                ),
                (
                    "requisition_source_of_supply",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Requisitioned Source of Supply"
                    ),
                ),
                ("parked", models.BooleanField(blank=True, null=True, verbose_name="Parked indicator")),
                ("quantity_withdrawn", models.FloatField(verbose_name="Quantity Withdrawn")),
                (
                    "requisition_last_changed_by_user",
                    models.CharField(max_length=12, verbose_name="User who last changed requisition"),
                ),
                ("requisition_last_changed_on_date", models.DateField(verbose_name="Date requisition last changed")),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="Purchase Order Number"),
                ),
                (
                    "order_item_number",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="Purchase Order Item Number"),
                ),
                (
                    "ordered_material_number",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="Ordered NIIN"),
                ),
                (
                    "ordered_material_description",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="Ordered Material Description"),
                ),
                (
                    "ordered_federal_supply_class_code",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Ordered FSC Code"),
                ),
                (
                    "ordered_source_of_supply",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="Ordered Source of Supply"),
                ),
                (
                    "order_priority",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="Order priority"),
                ),
                ("quantity_ordered", models.FloatField(blank=True, null=True, verbose_name="Quantity Ordered")),
                ("quantity_issued", models.FloatField(blank=True, null=True, verbose_name="Quantity Issued")),
                ("quantity_delivered", models.FloatField(blank=True, null=True, verbose_name="Quantity Delivered")),
                ("quantity_received", models.FloatField(blank=True, null=True, verbose_name="Quantity Received")),
                ("quantity_scheduled", models.FloatField(blank=True, null=True, verbose_name="Quantity Scheduled")),
                (
                    "order_unit_of_measure",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Order Unit of Measure"),
                ),
                (
                    "requirement_urgency",
                    models.CharField(blank=True, max_length=1, null=True, verbose_name="Requirement urgency"),
                ),
                (
                    "requirement_priority",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Requirement priority"),
                ),
                (
                    "issuing_storage_location",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Issuing storage location"),
                ),
                (
                    "dod_document_number",
                    models.CharField(blank=True, max_length=14, null=True, verbose_name="DOD Document Number"),
                ),
                ("item_delivered", models.BooleanField(verbose_name="Delivery indicator")),
                (
                    "planned_shipment_start_date",
                    models.DateField(blank=True, null=True, verbose_name="Planned Shipment Start Date"),
                ),
                (
                    "item_delivery_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Item Delivery Datetime"),
                ),
                (
                    "purchase_document_created_on_date",
                    models.DateField(blank=True, null=True, verbose_name="Date purchase order created"),
                ),
                (
                    "order_last_changed_at_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last changed at datetime"),
                ),
                ("price_per_unit", models.FloatField(blank=True, null=True, verbose_name="Price per unit of measure")),
                ("total_price", models.FloatField(blank=True, null=True, verbose_name="Total price")),
                (
                    "funding_source",
                    models.CharField(blank=True, max_length=15, null=True, verbose_name="Funding Area; includes MDEP"),
                ),
                (
                    "reservation_storage_location",
                    models.CharField(max_length=4, verbose_name="Reserving storage location"),
                ),
                ("required_by_date", models.DateField(verbose_name="Required by date")),
                ("quantity_required", models.FloatField(verbose_name="Quantity required")),
                ("quantity_on_hand", models.FloatField(verbose_name="Quantity on Hand")),
                ("unit_of_measure", models.CharField(max_length=2, verbose_name="Quantity Unit of measure")),
                ("dollars_withdrawn", models.FloatField(verbose_name="Dollars withdrawn")),
                ("movement_type", models.CharField(max_length=3, verbose_name="Movement Type")),
                ("reservation_urgency", models.CharField(max_length=1, verbose_name="Reservation Urgency")),
                ("reservation_priority", models.CharField(max_length=2, verbose_name="Reservation Priority")),
                (
                    "line_item_number",
                    models.CharField(blank=True, max_length=6, null=True, verbose_name="Reserved Line Item Number"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="User provided notes for this purchase order",
                    ),
                ),
                ("last_change_time", models.DateTimeField(verbose_name="Last time order was updated")),
                (
                    "last_update_time",
                    models.DateTimeField(verbose_name="Last time the user edited data for this purchase order"),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "db_table": "supply_purchase_orders",
            },
        ),
        migrations.CreateModel(
            name="RawProvisionalStock",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "dodaac",
                    models.CharField(blank=True, max_length=6, verbose_name="Department of Defense unit, activity"),
                ),
                (
                    "gcss_internal_material_number",
                    models.CharField(max_length=18, verbose_name="Foreign key, connects source datasets together"),
                ),
                (
                    "plant",
                    models.CharField(
                        max_length=4, verbose_name="Indicates whether storage SLOC is a unit's local sloc or an SSA."
                    ),
                ),
                (
                    "mrp_area_id",
                    models.CharField(max_length=10, verbose_name="Areas which refer to provisional storage locations"),
                ),
                ("storage_location", models.CharField(max_length=4, verbose_name="Where the stock is being stored")),
                ("total_stock", models.FloatField(verbose_name="Total Stock")),
                ("serviceable_stock", models.FloatField(verbose_name=" Stock that is ready for use")),
                (
                    "non_serviceable_stock",
                    models.FloatField(verbose_name="Stock that is not ready for use in its current condition"),
                ),
                (
                    "num_serviceable_zero_balance_batches",
                    models.IntegerField(verbose_name="number of serviceable batches that have no stock "),
                ),
                (
                    "num_non_serviceable_zero_balance_batches",
                    models.IntegerField(verbose_name="number of non-serviceable batches with no stock"),
                ),
                (
                    "batches",
                    models.JSONField(
                        verbose_name="list that classify the physical state or serviceability of equipment or supplies"
                    ),
                ),
                ("serviceable_batches", models.JSONField(verbose_name="list of serviceable batches")),
                ("non_serviceable_batches", models.JSONField(verbose_name="list of non serviceable batchesd")),
                ("num_batches", models.IntegerField(verbose_name="Number of batches")),
                ("num_serviceable_batches", models.IntegerField(verbose_name="The number of serviceable batches ")),
                (
                    "num_non_serviceable_batches",
                    models.IntegerField(verbose_name="The number of non serviceable batches"),
                ),
                ("is_bench_stock", models.BooleanField(verbose_name="Bench or Stock")),
                (
                    "storage_bin",
                    models.CharField(max_length=10, verbose_name="Sub-location within a larger storage location"),
                ),
                ("uic", models.CharField(blank=True, max_length=6, verbose_name="Unit identification code")),
                (
                    "sloc_class",
                    models.CharField(max_length=4, null=True, verbose_name="Storage location classification"),
                ),
                ("sloc_types", models.JSONField(verbose_name="Storage Location types")),
                (
                    "sloc_fe_abbr",
                    models.CharField(
                        max_length=12, null=True, verbose_name="Force element and associated storage location name"
                    ),
                ),
                (
                    "sloc_fe_name",
                    models.CharField(
                        max_length=40, null=True, verbose_name="Force element and associated storage location name"
                    ),
                ),
                (
                    "ric",
                    models.CharField(
                        max_length=3, verbose_name="Unit's SSA that has to retrograde items to support_ric"
                    ),
                ),
                ("support_ric", models.CharField(max_length=3, verbose_name="Unit's installation SSA")),
                (
                    "sloc_description",
                    models.CharField(max_length=16, verbose_name="Description of the storage location"),
                ),
                (
                    "derived_dodaac",
                    models.CharField(
                        max_length=6, null=True, verbose_name="The dodaac dervied from the sloc_fe_name column"
                    ),
                ),
                (
                    "sloc_description_uic",
                    models.CharField(max_length=6, null=True, verbose_name="The uic from the sloc_description column"),
                ),
                ("mrp_type", models.CharField(max_length=2, verbose_name="MRP type")),
                ("reorder_point", models.FloatField(verbose_name="Reorder point")),
                ("safety_stock", models.FloatField(verbose_name="Safety Stock")),
                ("has_storage_bin", models.BooleanField(verbose_name="Calculated field")),
                ("is_shop_stock", models.BooleanField(verbose_name="Calculated field")),
                ("is_authorized", models.BooleanField(verbose_name="Calculated field")),
                ("authorized_stock", models.FloatField(verbose_name="Stock a unit is authorized to have ")),
                (
                    "material_number",
                    models.CharField(max_length=23, verbose_name="Number identifying what the component is"),
                ),
                (
                    "material_number_type",
                    models.CharField(max_length=15, null=True, verbose_name="The type of material number"),
                ),
                (
                    "material_description",
                    models.CharField(max_length=45, null=True, verbose_name="Description of the component"),
                ),
                (
                    "line_item_number",
                    models.CharField(
                        max_length=6, verbose_name="Identifies the generic nomenclature of equipment item"
                    ),
                ),
                (
                    "material_number_with_fsc",
                    models.CharField(max_length=24, verbose_name="Material number with four digit FSC"),
                ),
                (
                    "material_number_with_fsc_type",
                    models.CharField(max_length=13, null=True, verbose_name="Material number + 4 digit FSC type"),
                ),
                ("recovery_code", models.CharField(max_length=1, verbose_name="Recovery code")),
                ("unit_price", models.FloatField(verbose_name="How much the part cost")),
                (
                    "unserviceable_credit_value",
                    models.FloatField(verbose_name="Credit received when turning in a unserviceable part"),
                ),
                (
                    "serviceable_credit_value",
                    models.FloatField(verbose_name="Credit received when turning in a usable part"),
                ),
                (
                    "serviceable_exchange_credit_price",
                    models.FloatField(verbose_name="Credit received when exchanging repairable part for another"),
                ),
                ("sc_name", models.CharField(max_length=17, null=True, verbose_name="Physical installation location")),
                (
                    "total_stock_valuation",
                    models.FloatField(verbose_name="Calculated field - total_stock times the unit_price"),
                ),
                (
                    "stock_id",
                    models.CharField(
                        max_length=28,
                        verbose_name="Concatenated field- gcss_internal_material_number + plant + storage_location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawPurchaseOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("work_order_number", models.CharField(max_length=12, verbose_name="Work order purchased against")),
                (
                    "reservation_storage_location",
                    models.CharField(max_length=4, verbose_name="Reserving storage location"),
                ),
                ("required_by_date", models.DateField(verbose_name="Required by date")),
                ("quantity_required", models.FloatField(verbose_name="Quantity required")),
                ("quantity_on_hand", models.FloatField(verbose_name="Quantity on Hand")),
                ("unit_of_measure", models.CharField(max_length=2, verbose_name="Quantity Unit of measure")),
                ("quantity_withdrawn", models.FloatField(verbose_name="Quantity Withdrawn")),
                ("dollars_withdrawn", models.FloatField(verbose_name="Dollars withdrawn")),
                ("movement_type", models.CharField(max_length=3, verbose_name="Movement Type")),
                ("reservation_urgency", models.CharField(max_length=1, verbose_name="Reservation Urgency")),
                ("reservation_priority", models.CharField(max_length=2, verbose_name="Reservation Priority")),
                (
                    "line_item_number",
                    models.CharField(blank=True, max_length=6, null=True, verbose_name="Reserved Line Item Number"),
                ),
                (
                    "purchase_order_number",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="Purchase Order Number"),
                ),
                (
                    "purchase_order_item_number",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="Purchase Order Item Number"),
                ),
                (
                    "purchase_requisition_number",
                    models.CharField(max_length=10, verbose_name="Purchase Requisition Number"),
                ),
                (
                    "purchase_requisition_item_number",
                    models.CharField(max_length=3, verbose_name="Purchase Requisition Item Number"),
                ),
                (
                    "requisition_last_changed_by_user",
                    models.CharField(max_length=12, verbose_name="User who last changed requisition"),
                ),
                ("requisition_last_changed_on_date", models.DateField(verbose_name="Date requisition last changed")),
                (
                    "storage_location",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Ordering Storage Location"),
                ),
                ("quantity_ordered", models.FloatField(blank=True, null=True, verbose_name="Quantity Ordered")),
                ("quantity_issued", models.FloatField(blank=True, null=True, verbose_name="Quantity Issued")),
                ("quantity_delivered", models.FloatField(blank=True, null=True, verbose_name="Quantity Delivered")),
                ("quantity_received", models.FloatField(blank=True, null=True, verbose_name="Quantity Received")),
                ("quantity_scheduled", models.FloatField(blank=True, null=True, verbose_name="Quantity Scheduled")),
                (
                    "order_unit_of_measure",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Order Unit of Measure"),
                ),
                ("price_per_unit", models.FloatField(blank=True, null=True, verbose_name="Price per unit of measure")),
                ("total_price", models.FloatField(blank=True, null=True, verbose_name="Total price")),
                (
                    "item_delivered",
                    models.CharField(blank=True, max_length=1, null=True, verbose_name="Delivery indicator"),
                ),
                (
                    "requirement_urgency",
                    models.CharField(blank=True, max_length=1, null=True, verbose_name="Requirement urgency"),
                ),
                (
                    "requirement_priority",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Requirement priority"),
                ),
                (
                    "issuing_storage_location",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Issuing storage location"),
                ),
                (
                    "functional_area_ekpo",
                    models.CharField(blank=True, max_length=15, null=True, verbose_name="Funding Area; includes MDEP"),
                ),
                (
                    "dod_document_number",
                    models.CharField(blank=True, max_length=14, null=True, verbose_name="DOD Document Number"),
                ),
                (
                    "order_last_changed_at_datetime",
                    models.CharField(blank=True, max_length=28, null=True, verbose_name="Last changed at datetime"),
                ),
                (
                    "order_priority",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="Order priority"),
                ),
                (
                    "purchase_document_created_on_date",
                    models.DateField(blank=True, null=True, verbose_name="Date purchase order created"),
                ),
                (
                    "planned_shipment_start_date",
                    models.DateField(blank=True, null=True, verbose_name="Planned Shipment Start Date"),
                ),
                (
                    "item_delivery_datetime",
                    models.CharField(blank=True, max_length=28, null=True, verbose_name="Item Delivery Datetime"),
                ),
                (
                    "requisition_status",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Requisition Status"),
                ),
                (
                    "ordered_material_number",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="Ordered NIIN"),
                ),
                (
                    "ordered_material_description",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="Ordered Material Description"),
                ),
                (
                    "ordered_federal_supply_class_code",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Ordered FSC Code"),
                ),
                (
                    "ordered_source_of_supply",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="Ordered Source of Supply"),
                ),
                (
                    "requisition_material_number",
                    models.CharField(max_length=20, verbose_name="Requisitioned Material Number"),
                ),
                (
                    "requisition_material_description",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Requisitioned material description"
                    ),
                ),
                (
                    "requisition_federal_supply_class_code",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Requisitioned FSC Code"),
                ),
                (
                    "requisition_source_of_supply",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Requisitioned Source of Supply"
                    ),
                ),
                ("parked", models.CharField(blank=True, max_length=1, null=True, verbose_name="Parked indicator")),
                (
                    "centaur_sync_timestamp",
                    models.CharField(max_length=28, verbose_name="Timestamp used to control syncing behavior"),
                ),
            ],
            options={
                "verbose_name": "Raw Purchase Order",
                "verbose_name_plural": "Raw Purchase Orders",
                "db_table": "raw_purchase_orders",
            },
        ),
        migrations.CreateModel(
            name="RawWorkOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("work_order_number", models.CharField(max_length=12, verbose_name="Work order number")),
                ("equipment_number", models.CharField(max_length=18, verbose_name="GCSS-A Equipment Number")),
                (
                    "main_work_center",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Main work center completing order"
                    ),
                ),
                (
                    "work_center",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Work center completing the work"
                    ),
                ),
                (
                    "plant",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Plant the work is conducted at"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True, verbose_name="Work order description"),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("CR", "Created"),
                            ("RL", "Released"),
                            ("TECH", "Technically Completed"),
                            ("CL", "Closed"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=21,
                        verbose_name="Work order status",
                    ),
                ),
                ("date_released", models.DateField(blank=True, null=True, verbose_name="Date released for work")),
                (
                    "date_technically_completed",
                    models.DateField(blank=True, null=True, verbose_name="Date technical work complete"),
                ),
                ("date_closed", models.DateField(blank=True, null=True, verbose_name="Date order closed")),
                (
                    "technical_status_code",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Work Order technical status"),
                ),
                (
                    "technical_status_description",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Work Order technical status description"
                    ),
                ),
                (
                    "technical_status_timestamp",
                    models.CharField(
                        blank=True, max_length=28, null=True, verbose_name="Date technical status started"
                    ),
                ),
                ("project_code", models.CharField(blank=True, max_length=3, null=True, verbose_name="Project code")),
                ("fund_code", models.CharField(blank=True, max_length=2, null=True, verbose_name="Fund code")),
                (
                    "order_priority",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="Order priority"),
                ),
                ("priority", models.CharField(blank=True, max_length=1, null=True, verbose_name="Order priority")),
                (
                    "system_condition",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="System condition (aka status code)"
                    ),
                ),
                (
                    "system_condition_datetime",
                    models.CharField(
                        blank=True, max_length=28, null=True, verbose_name="Date system condition started"
                    ),
                ),
                (
                    "basic_start_datetime",
                    models.CharField(blank=True, max_length=28, null=True, verbose_name="Basic start datetime"),
                ),
                (
                    "basic_finish_datetime",
                    models.CharField(blank=True, max_length=28, null=True, verbose_name="Basic finish datetime"),
                ),
                (
                    "scheduled_start_datetime",
                    models.CharField(blank=True, max_length=28, null=True, verbose_name="Scheduled start datetime"),
                ),
                (
                    "scheduled_finish_datetime",
                    models.CharField(blank=True, max_length=28, null=True, verbose_name="Scheduled finish datetime"),
                ),
                (
                    "actual_start_datetime",
                    models.CharField(blank=True, max_length=28, null=True, verbose_name="Actual start datetime"),
                ),
                (
                    "confirmed_order_finish_datetime",
                    models.CharField(blank=True, max_length=28, null=True, verbose_name="Confirmed finish datetime"),
                ),
                (
                    "created_by_user",
                    models.CharField(max_length=12, verbose_name="The user (or process) who created the order"),
                ),
                (
                    "created_at_timestamp",
                    models.CharField(max_length=28, verbose_name="The timestamp the order was created"),
                ),
                (
                    "last_changed_by_user",
                    models.CharField(max_length=12, verbose_name="The user (or process) who last changed the order"),
                ),
                (
                    "last_changed_at_timestamp",
                    models.CharField(max_length=28, verbose_name="The timestamp the order was last changed"),
                ),
                (
                    "centaur_sync_timestamp",
                    models.CharField(max_length=28, verbose_name="Timestamp used to control syncing behavior"),
                ),
            ],
            options={
                "verbose_name": "Raw Work Order",
                "verbose_name_plural": "Raw Work Orders",
                "db_table": "raw_equipment_work_orders",
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("order_number", models.CharField(max_length=12, verbose_name="Work order number")),
                (
                    "main_work_center",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Main work center completing order"
                    ),
                ),
                (
                    "work_center",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Work center completing the work"
                    ),
                ),
                (
                    "plant",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Plant the work is conducted at"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True, verbose_name="Work order description"),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("CR", "Created"),
                            ("RL", "Released"),
                            ("TECH", "Technically Completed"),
                            ("CL", "Closed"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=4,
                        verbose_name="Work order status",
                    ),
                ),
                ("date_released", models.DateField(blank=True, null=True, verbose_name="Date released for work")),
                (
                    "date_technically_completed",
                    models.DateField(blank=True, null=True, verbose_name="Date technical work complete"),
                ),
                ("date_closed", models.DateField(blank=True, null=True, verbose_name="Date order closed")),
                (
                    "technical_status",
                    models.CharField(
                        choices=[
                            ("NS", "No Status"),
                            ("CLR", "Cleared"),
                            ("TICL", "Technical Inspector Cleared"),
                            ("DI", "Diagonal"),
                            ("DA", "Dash"),
                            ("E", "Admin Deadline"),
                            ("X", "Deadline - Non Mission Capable"),
                            ("CX", "Circle X"),
                            ("NUKE", "Nuclear Containment"),
                            ("CHEM", "Chemical Containment"),
                            ("BIO", "Biological Containment"),
                        ],
                        default="NS",
                        max_length=4,
                        verbose_name="Work Order technical status",
                    ),
                ),
                (
                    "technical_status_start_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date technical status started"),
                ),
                ("project_code", models.CharField(blank=True, max_length=3, null=True, verbose_name="Project code")),
                ("fund_code", models.CharField(blank=True, max_length=2, null=True, verbose_name="Fund code")),
                (
                    "order_priority",
                    models.CharField(blank=True, max_length=3, null=True, verbose_name="Order priority"),
                ),
                (
                    "system_condition_code",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="System condition (aka status code)"
                    ),
                ),
                (
                    "system_condition_start_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date system condition started"),
                ),
                (
                    "basic_start_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Basic start datetime"),
                ),
                (
                    "basic_finish_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Basic finish datetime"),
                ),
                (
                    "scheduled_start_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Scheduled start datetime"),
                ),
                (
                    "scheduled_finish_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Scheduled finish datetime"),
                ),
                (
                    "actual_start_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Actual start datetime"),
                ),
                (
                    "confirmed_order_finish_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Confirmed finish datetime"),
                ),
                (
                    "created_by",
                    models.CharField(max_length=12, verbose_name="The user (or process) who created the order"),
                ),
                ("created_at", models.DateTimeField(verbose_name="The timestamp the order was created")),
                (
                    "changed_by",
                    models.CharField(max_length=12, verbose_name="The user (or process) who last changed the order"),
                ),
                ("changed_at", models.DateTimeField(verbose_name="The timestamp the order was last changed")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=2048, null=True, verbose_name="User provided notes for this work order"
                    ),
                ),
                (
                    "last_update_time",
                    models.DateTimeField(verbose_name="Last time the user edited data for this equipment"),
                ),
            ],
            options={
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
                "db_table": "work_orders",
            },
        ),
        migrations.CreateModel(
            name="AGSEWorkOrder",
            fields=[
                (
                    "workorder_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="supply.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "AGSE Work Order",
                "verbose_name_plural": "AGSE Work Orders",
                "db_table": "agse_work_orders",
            },
            bases=("supply.workorder",),
        ),
        migrations.CreateModel(
            name="AircraftWorkOrder",
            fields=[
                (
                    "workorder_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="supply.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aircraft Work Order",
                "verbose_name_plural": "Aircraft Work Orders",
                "db_table": "aircraft_work_orders",
            },
            bases=("supply.workorder",),
        ),
        migrations.CreateModel(
            name="UAVWorkOrder",
            fields=[
                (
                    "workorder_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="supply.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "UAV Work Order",
                "verbose_name_plural": "UAV Work Orders",
                "db_table": "uav_work_orders",
            },
            bases=("supply.workorder",),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.UniqueConstraint(fields=("order_number",), name="unique work order numbers"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="work_order_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="purchase_orders",
                to="supply.workorder",
            ),
        ),
        migrations.AddField(
            model_name="provisionalstock",
            name="sloc_description_uic",
            field=models.ForeignKey(
                blank=True,
                db_column="sloc_description_uic",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uic_sloc_description",
                to="auto_dsr.unit",
            ),
        ),
        migrations.AddField(
            model_name="provisionalstock",
            name="uic",
            field=models.ForeignKey(
                blank=True,
                db_column="uic",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provisional_stock",
                to="auto_dsr.unit",
            ),
        ),
        migrations.AddField(
            model_name="uavworkorder",
            name="uav",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="work_orders", to="uas.uav"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("requisition_number", "requisition_item_number", "order_number", "order_item_number"),
                name="unique order items per requisition",
            ),
        ),
        migrations.AddField(
            model_name="aircraftworkorder",
            name="aircraft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="work_orders", to="aircraft.aircraft"
            ),
        ),
        migrations.AddField(
            model_name="agseworkorder",
            name="agse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="work_orders", to="agse.agse"
            ),
        ),
    ]
