# Generated by Django 4.2.4 on 2023-11-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_da_7817_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='da_7817',
            name='recorded_by_legacy',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Recorded By (Legacy)'),
        ),
    ]
