# Generated by Django 4.2.4 on 2023-11-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0006_soldier_pfc_dor_soldier_pv2_dor_soldier_sfc_dor_and_more"),
        ("forms", "0006_da_7817_recorded_by_legacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="DA_4856",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("title", models.CharField(max_length=50, verbose_name="DA 4856 Form Title")),
                ("document", models.FileField(blank=True, null=True, upload_to="", verbose_name="DA 4856 Form")),
            ],
            options={
                "verbose_name": "DA 4856",
                "verbose_name_plural": "DA 4856s",
                "db_table": "da_4856",
            },
        ),
        migrations.AddConstraint(
            model_name="da_7817",
            constraint=models.UniqueConstraint(
                fields=("date_time", "event_type", "recorded_by", "recorded_by_legacy"), name="da_7817_uniqueness"
            ),
        ),
        migrations.AddField(
            model_name="da_4856",
            name="soldier",
            field=models.ForeignKey(
                db_column="da_4856_soldier_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="da_4856_soldier_id",
                to="personnel.soldier",
            ),
        ),
        migrations.AddField(
            model_name="da_7817",
            name="attached_da_4856",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="forms.da_4856"
            ),
        ),
    ]
