# Generated by Django 4.2.4 on 2023-12-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0010_remove_da_7817_gainingunit_da_7817_gaining_unit_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="da_7817",
            name="da_7817_uniqueness",
        ),
        migrations.RenameField(
            model_name="da_7817",
            old_name="date_time",
            new_name="date",
        ),
        migrations.AlterField(
            model_name="da_7817",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Training", "Training Event"),
                    ("Evaluation", "Evaluation Event"),
                    ("PCS/ETS", "PCS or ETS Event"),
                    ("Award", "Award Event"),
                    ("Records Review", "Records Review Event"),
                    ("Other", "Other Event"),
                ],
                default="Other",
                max_length=15,
                verbose_name="Event Type",
            ),
        ),
        migrations.AlterField(
            model_name="da_7817",
            name="training_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Advanced Composites", "Advanced Composites Training"),
                    ("Weight and Balance", "Aircraft Weight and Balance Software Training"),
                    ("Oil Analysis", "Army Oil Analysis Training"),
                    ("Corpus Christi Depot", "Corpus Christi Army Depot Training"),
                    ("Corrosion Monitor", "Corrosion Monitor Training"),
                    ("Defence Acquisition University", "Defense Acquisition University"),
                    ("T700 Engine", "T700 Engine Training"),
                    (
                        "Logistics Assistance Representative University",
                        "Logistics Assistance Representative University",
                    ),
                    ("Non-Destructive Testing Training", "Non-Destructive Testing Training"),
                    ("Senior Maintainer Course", "Senior Maintainer Course"),
                    ("Test, Measurement, and Diagnostic", "Test, Measurement, and Diagnostic Equipment Training"),
                    ("Credentialing Programs", "Credentialing Programs"),
                    ("Professional Military Education", "Professional Military Education"),
                    ("Hazardous Materials", "Hazardous Materials"),
                    ("Flight Evaluator Training", "Flight Evaluator Training"),
                    ("Other", "Other Training Type"),
                ],
                max_length=50,
                null=True,
                verbose_name="Training Type",
            ),
        ),
    ]
