# Generated by Django 4.2.4 on 2024-03-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0011_soldiertransferrequest_and_more"),
        ("forms", "0014_alter_da_4856_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICallLogging",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "request",
                    models.JSONField(
                        verbose_name="The data that is passed in with a HttpRequest (headers, method, body, path/path_info)"
                    ),
                ),
                (
                    "response",
                    models.JSONField(
                        verbose_name="The data that will be returned from the API Endpoint being called (class, status_code, content)"
                    ),
                ),
                ("time_of_request", models.DateTimeField(verbose_name="Date and Time at which the request was made")),
                (
                    "request_made_by",
                    models.ForeignKey(
                        db_column="soldier_id",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="personnel.soldier",
                    ),
                ),
            ],
        ),
    ]
