# Generated by Django 4.2.4 on 2024-05-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0017_alter_da_7817_training_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="da_7817",
            name="tcs_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OIF", "Operation Iraqi Freedom"),
                    ("OEF", "Operation Enduring Freedom"),
                    ("OFS", "Operation Freedom Sentinel"),
                    ("OIR", "Operation Inherent Resolve"),
                    ("ORS", "Operation Resolute Support"),
                    ("OAR", "Operation Atlantic Resolve"),
                    ("OPP", "Operation Pacific Pathways"),
                    ("OEADR", "Operation European Assure, Deter, and Reinforce"),
                    ("Other", "Other TCS Location"),
                    ("Return", "Return from TCS"),
                ],
                max_length=25,
                null=True,
                verbose_name="TCS Location",
            ),
        ),
        migrations.AlterField(
            model_name="da_7817",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Training", "Training Event"),
                    ("Evaluation", "Evaluation Event"),
                    ("PCS/ETS", "PCS or ETS Event"),
                    ("TCS", "TCS Event"),
                    ("Award", "Award Event"),
                    ("Records Review", "Records Review Event"),
                    ("Other", "Other Event"),
                ],
                default="Other",
                max_length=15,
                verbose_name="Event Type",
            ),
        ),
    ]
