# Generated by Django 4.2.4 on 2024-06-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0013_alter_soldier_mos"),
        ("forms", "0019_da_4856_visible_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="da_4856",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                db_column="uploaded_by_soldier_dod_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="counseling_uploaded_by",
                to="personnel.soldier",
            ),
        ),
    ]
