# Generated by Django 4.2.2 on 2024-07-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0020_da_4856_uploaded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="da_7817",
            name="award_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASA", "Aviation Safety Award"),
                    ("AAM", "Army Achievement Medal"),
                    ("ARCOM", "Army Commendation Medal"),
                    ("GCM", "Good Conduct Medal"),
                    ("DSC", "Distinguished Service Cross"),
                    ("DDSM", "Defense Distinguished Service Medal"),
                    ("DSM", "Distinguished Service Medal"),
                    ("SSTAR", "Silver Star"),
                    ("DSSM", "Defense Superior Service Medal"),
                    ("LOM", "Legion of Merit"),
                    ("DFC", "Distinguished Flying Cross"),
                    ("SM", "Soldier's Medal"),
                    ("BSM", "Bronze Star Medal"),
                    ("PH", "Purple Heart"),
                    ("DMSM", "Defense Meritorious Service Medal"),
                    ("MSM", "Meritorious Service Medal"),
                    ("AM", "Air Medal"),
                    ("JSCM", "Joint Service Commendation Medal"),
                    ("JSAM", "Joint Service Achievement Medal"),
                    ("POWM", "Prisoner of War Medal"),
                    ("ARCAM", "Army Reserve Component Achievement Medal"),
                    ("AOM", "Army of Occupation Medal"),
                    ("NDSM", "National Defense Service Medal"),
                    ("AFEM", "Armed Forces Expeditionary Medal"),
                    ("ASR", "Army Service Ribbon"),
                    ("AFSM", "Armed Forces Service Medal"),
                    ("AOSR", "Army Overseas Service Ribbon"),
                    ("AFRM", "Armed Forces Reserve Medal"),
                    ("NPDR", "NCO Professional Development Ribbon"),
                    ("NM", "Nato Medal"),
                    ("UNM", "United Nations Medal"),
                    ("ARCOTR", "Army Reserve Component Overseas Training Ribbon"),
                    ("Other", "Other Award"),
                ],
                max_length=20,
                null=True,
                verbose_name="Award Type",
            ),
        ),
        migrations.AlterField(
            model_name="da_7817",
            name="training_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Advanced Composites", "Advanced Composites Training"),
                    ("Weight and Balance", "Aircraft Weight and Balance Software Training"),
                    ("Oil Analysis", "Army Oil Analysis Training"),
                    ("Corpus Christi Depot", "Corpus Christi Army Depot Training"),
                    ("Corrosion Monitor", "Corrosion Monitor Training"),
                    ("Defence Acquisition University", "Defense Acquisition University"),
                    ("T700 Engine", "T700 Engine Training"),
                    (
                        "Logistics Assistance Representative University",
                        "Logistics Assistance Representative University",
                    ),
                    ("Non-Destructive Testing Training", "Non-Destructive Testing Training"),
                    ("Senior Maintainer Course", "Senior Maintainer Course"),
                    ("Test, Measurement, and Diagnostic", "Test, Measurement, and Diagnostic Equipment Training"),
                    ("Credentialing Programs", "Credentialing Programs"),
                    ("Professional Military Education", "Professional Military Education"),
                    ("Hazardous Materials", "Hazardous Materials"),
                    ("Flight Evaluator Training", "Flight Evaluator Training"),
                    ("Compressed Gas", "Compressed Gas Training"),
                    ("Tire Inflation", "Tire Inflation Training"),
                    ("ECS Cart", "ECS Cart Training"),
                    ("Overhead Hoist", "Overhead Hoist Training"),
                    ("Job Hazard Analysis", "Job Hazard Analysis Training"),
                    ("CPR Certification", "CPR Certification Training"),
                    ("Laser Safety", "Laser Safety Training"),
                    ("FOD Training", "Foreign Object and Debris Training"),
                    ("Evaluator Training", "AMTP Evaluator Training"),
                    ("Other", "Other Training Type"),
                ],
                max_length=50,
                null=True,
                verbose_name="Training Type",
            ),
        ),
    ]
