# Generated by Django 4.2.4 on 2024-09-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0026_da_7817_mos_historicalda_7817_mos"),
    ]

    operations = [
        migrations.AddField(
            model_name="da_7817",
            name="mass_entry_key",
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name="Mass Entry Key"),
        ),
        migrations.AddField(
            model_name="historicalda_7817",
            name="mass_entry_key",
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name="Mass Entry Key"),
        ),
    ]
