# Generated by Django 4.2.2 on 2023-08-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auto_dsr", "0014_userrequest_access_level"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Aircraft",
                    fields=[
                        (
                            "serial",
                            models.CharField(
                                max_length=32,
                                primary_key=True,
                                serialize=False,
                                verbose_name="Aircraft Serial Number",
                            ),
                        ),
                        (
                            "model",
                            models.CharField(
                                max_length=16,
                                verbose_name="Aircraft Mission Design Series",
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("FMC", "Fully Mission Capable"),
                                    ("PMC", "Partially Mission Capable"),
                                    ("PMCM", "Partially Mission Capable - Maintenance"),
                                    ("PMCS", "Partially Mission Capable - Sustainment"),
                                    ("NMC", "Non Mission Capable"),
                                    ("NMCS", "Non Mission Capable - Supply"),
                                    ("NMCM", "Non Mission Capable - Maintenance"),
                                    ("FIELD", "Field"),
                                    ("SUST", "Sustainment"),
                                    ("DADE", "Department of the Army Directed Event"),
                                    ("UNK", "Unknown"),
                                ],
                                default="UNK",
                                max_length=5,
                                verbose_name="Maintenance Status (FMC, NMC)",
                            ),
                        ),
                        (
                            "rtl",
                            models.CharField(
                                max_length=4,
                                verbose_name="Ready to Launch Status (RTL, NRTL)",
                            ),
                        ),
                        (
                            "total_airframe_hours",
                            models.FloatField(
                                verbose_name="Lifetime Flight Hours for that Airframe"
                            ),
                        ),
                        (
                            "flight_hours",
                            models.FloatField(
                                default=0.0,
                                verbose_name="Hours Flown in the current reporting period",
                            ),
                        ),
                        (
                            "hours_to_phase",
                            models.FloatField(
                                verbose_name="Flight Hours Until Phase Inspection"
                            ),
                        ),
                        (
                            "remarks",
                            models.TextField(
                                blank=True,
                                max_length=2048,
                                null=True,
                                verbose_name="Displayed Aircraft Remarks",
                            ),
                        ),
                        (
                            "date_down",
                            models.DateField(
                                blank=True,
                                null=True,
                                verbose_name="Date Aircraft Entered non-FMC status",
                            ),
                        ),
                        (
                            "ecd",
                            models.DateField(
                                blank=True,
                                null=True,
                                verbose_name="Estimated Completion Date for non-FMC Aircraft",
                            ),
                        ),
                        (
                            "last_sync_time",
                            models.DateTimeField(verbose_name="Last Sync from ACN"),
                        ),
                        (
                            "location",
                            models.ForeignKey(
                                blank=True,
                                db_column="location_id",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="auto_dsr.location",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "aircraft",
                        "db_table": "aircraft",
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Phase",
                    fields=[
                        (
                            "serial",
                            models.OneToOneField(
                                db_column="serial",
                                on_delete=django.db.models.deletion.CASCADE,
                                primary_key=True,
                                serialize=False,
                                to="aircraft.aircraft",
                            ),
                        ),
                        (
                            "last_conducted_hours",
                            models.FloatField(
                                verbose_name="Aircraft Hours When last conducted"
                            ),
                        ),
                        (
                            "hours_interval",
                            models.IntegerField(
                                verbose_name="Maximum Flying Hours between phase"
                            ),
                        ),
                        (
                            "next_due_hours",
                            models.FloatField(
                                blank=True,
                                null=True,
                                verbose_name="Aircraft Hours the Phase must begin before",
                            ),
                        ),
                        (
                            "phase_type",
                            models.CharField(
                                choices=[
                                    ("PMI1", "UH-60 PMI One"),
                                    ("PMI2", "UH-60 PMI Two"),
                                    ("FM1", "CH-47 PMI One"),
                                    ("FM2", "CH-47 PMI Two"),
                                    ("FM3", "CH-47 PMI Three"),
                                    ("GEN", "Generic PMI"),
                                ],
                                default="GEN",
                                max_length=4,
                                verbose_name="Phase Inspection Type",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "phases",
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="UserAircraftRemark",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True,
                                serialize=False,
                                verbose_name="Auto Unique Id",
                            ),
                        ),
                        (
                            "save_time",
                            models.DateTimeField(
                                verbose_name="The time the user saved this remark"
                            ),
                        ),
                        (
                            "remarks",
                            models.TextField(
                                max_length=2048,
                                verbose_name="User provided Remarks for a given Aircraft",
                            ),
                        ),
                        (
                            "lock_remark",
                            models.BooleanField(
                                verbose_name="A flag to identify if this column should persist through ACN updates"
                            ),
                        ),
                        (
                            "serial",
                            models.ForeignKey(
                                db_column="serial",
                                on_delete=django.db.models.deletion.PROTECT,
                                to="aircraft.aircraft",
                            ),
                        ),
                        (
                            "user_id",
                            models.ForeignKey(
                                db_column="user_id",
                                on_delete=django.db.models.deletion.PROTECT,
                                to="auto_dsr.user",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "user aircraft remarks",
                        "db_table": "user_aircraft_remarks",
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="UnitAircraft",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True,
                                serialize=False,
                                verbose_name="Auto Unique Id",
                            ),
                        ),
                        (
                            "serial",
                            models.ForeignKey(
                                db_column="serial",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="aircraft.aircraft",
                            ),
                        ),
                        (
                            "uic",
                            models.ForeignKey(
                                db_column="uic",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="auto_dsr.unit",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "unit_aircraft",
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="ReassignedAircraft",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True,
                                serialize=False,
                                verbose_name="Auto Unique Id",
                            ),
                        ),
                        (
                            "changed_on",
                            models.DateTimeField(
                                verbose_name="The time the change occured"
                            ),
                        ),
                        (
                            "changed_by",
                            models.ForeignKey(
                                db_column="changed_by_dodid",
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="auto_dsr.user",
                            ),
                        ),
                        (
                            "new_uic",
                            models.ForeignKey(
                                db_column="new_uic",
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="added_aircraft",
                                to="auto_dsr.unit",
                            ),
                        ),
                        (
                            "previous_uic",
                            models.ForeignKey(
                                db_column="previous_uic",
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="removed_aircraft",
                                to="auto_dsr.unit",
                            ),
                        ),
                        (
                            "serial_number",
                            models.ForeignKey(
                                db_column="serial_number",
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="aircraft.aircraft",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "Reassigned Aircraft",
                        "db_table": "reassigned_aircraft",
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Inspection",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True,
                                serialize=False,
                                verbose_name="Auto Unique Id",
                            ),
                        ),
                        (
                            "inspection_name",
                            models.CharField(
                                max_length=64, verbose_name="Inspection Display Name"
                            ),
                        ),
                        (
                            "last_conducted_hours",
                            models.FloatField(
                                blank=True,
                                null=True,
                                verbose_name="Aircraft Hours When Last Conducted",
                            ),
                        ),
                        (
                            "hours_interval",
                            models.IntegerField(
                                blank=True,
                                null=True,
                                verbose_name="Maximum Flying Hours before Inspection",
                            ),
                        ),
                        (
                            "next_due_hours",
                            models.FloatField(
                                blank=True,
                                null=True,
                                verbose_name="Aircraft Hours the Inspection must occur by",
                            ),
                        ),
                        (
                            "last_conducted_date",
                            models.DateField(
                                blank=True,
                                null=True,
                                verbose_name="Date the inspection was last conducted on",
                            ),
                        ),
                        (
                            "day_interval",
                            models.IntegerField(
                                blank=True,
                                null=True,
                                verbose_name="Maximum Days before inspection",
                            ),
                        ),
                        (
                            "next_due_date",
                            models.DateField(
                                blank=True,
                                null=True,
                                verbose_name="Date the inspection must occur by",
                            ),
                        ),
                        (
                            "serial",
                            models.ForeignKey(
                                blank=True,
                                db_column="serial",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="aircraft.aircraft",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "inspections",
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Flight",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True,
                                serialize=False,
                                verbose_name="Auto Unique Id",
                            ),
                        ),
                        (
                            "length",
                            models.FloatField(
                                verbose_name="How long the flight is expected to last for"
                            ),
                        ),
                        (
                            "begin_time",
                            models.DateTimeField(
                                verbose_name="When the flight is expected to begin"
                            ),
                        ),
                        (
                            "end_time",
                            models.DateTimeField(
                                null=True,
                                verbose_name="When the flight is expected to end",
                            ),
                        ),
                        (
                            "serial",
                            models.ForeignKey(
                                blank=True,
                                db_column="serial",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="aircraft.aircraft",
                            ),
                        ),
                        (
                            "uic",
                            models.ForeignKey(
                                db_column="uic",
                                on_delete=django.db.models.deletion.PROTECT,
                                to="auto_dsr.unit",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "flights",
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Fault",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True,
                                serialize=False,
                                verbose_name="Auto Unique Id",
                            ),
                        ),
                        (
                            "remarks",
                            models.TextField(
                                max_length=2048, verbose_name="Fault Remarks from ACN"
                            ),
                        ),
                        (
                            "severity",
                            models.CharField(
                                choices=[
                                    ("X", "Deadline"),
                                    ("O", "Commander Underwritten Deadline"),
                                    ("/", "Non-deadlining Fault"),
                                    ("U", "Unknown or Unspecified"),
                                ],
                                default="U",
                                max_length=10,
                                verbose_name="Severity Code",
                            ),
                        ),
                        (
                            "open_date",
                            models.DateField(
                                verbose_name="Date the fault was identified"
                            ),
                        ),
                        (
                            "open",
                            models.BooleanField(
                                verbose_name="Flag indicating if the fault is still open"
                            ),
                        ),
                        (
                            "serial",
                            models.ForeignKey(
                                db_column="serial",
                                on_delete=django.db.models.deletion.PROTECT,
                                to="aircraft.aircraft",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "faults",
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="AircraftEditLog",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                primary_key=True,
                                serialize=False,
                                verbose_name="Auto Unique Id",
                            ),
                        ),
                        (
                            "effective_time",
                            models.DateTimeField(
                                verbose_name="The timestamp when a user made this edit"
                            ),
                        ),
                        (
                            "edited_column",
                            models.CharField(
                                max_length=32,
                                verbose_name="The column edited by the user",
                            ),
                        ),
                        (
                            "lock_edit",
                            models.BooleanField(
                                verbose_name="A flag to keep track of if this column should be locked (not updated when a new ACN update is made)"
                            ),
                        ),
                        (
                            "record",
                            models.JSONField(
                                verbose_name="The column's previous and newly edited value"
                            ),
                        ),
                        (
                            "serial",
                            models.ForeignKey(
                                db_column="serial",
                                on_delete=django.db.models.deletion.PROTECT,
                                to="aircraft.aircraft",
                            ),
                        ),
                        (
                            "user_id",
                            models.ForeignKey(
                                db_column="user_id",
                                on_delete=django.db.models.deletion.PROTECT,
                                to="auto_dsr.user",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "aircraft_edit_log",
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name="inspection",
                    constraint=models.UniqueConstraint(
                        fields=("serial", "inspection_name"),
                        name="inspection_for_serial",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aircraft",
            name="uic",
            field=models.ManyToManyField(
                through="aircraft.UnitAircraft", to="auto_dsr.unit"
            ),
        ),
    ]
