# Generated by Django 4.2.2 on 2023-09-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_unitaircraft_aircraft_in_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.CharField(choices=[('FMC', 'Fully Mission Capable'), ('PMC', 'Partially Mission Capable'), ('PMCM', 'Partially Mission Capable - Maintenance'), ('PMCS', 'Partially Mission Capable - Sustainment'), ('NMC', 'Non Mission Capable'), ('NMCS', 'Non Mission Capable - Supply'), ('NMCM', 'Non Mission Capable - Maintenance'), ('FIELD', 'Field'), ('SUST', 'Sustainment'), ('DADE', 'Department of the Army Directed Event'), ('MTF', 'Maintenance Test Flight'), ('UNK', 'Unknown')], default='UNK', max_length=5, verbose_name='Maintenance Status (FMC, NMC)'),
        ),
    ]
