# Generated by Django 4.2.2 on 2024-01-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0008_appliedmodification_other_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="classification",
            field=models.CharField(
                choices=[
                    ("ROUTINE", "Routine"),
                    ("UNCLASSIFIED", "Unclassified"),
                    ("CLASS I", "Class 1"),
                    ("LIMITED URGENT", "Limited Urgency"),
                    ("NORMAL", "Normal"),
                    ("NO PRIORITY", "No Priority"),
                    ("CLASS II", "Class 2"),
                ],
                default="ROUTINE",
                max_length=16,
                verbose_name="Urgency or classification of message (urgent, routine, etc)",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="confirmation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date that the unit must confirm receipt of the message"
            ),
        ),
    ]
