# Generated by Django 4.2.2 on 2024-03-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0013_aircrafttransferrequest_aircrafttransferlog'),
        ('aircraft', '0014_equipment_unitequipment_equipment_tracked_by_unit_and_more'),
    ]

    operations = [
    ]
