# Generated by Django 5.0.1 on 2024-06-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0018_rename_end_datetime_flight_stop_datetime'),
        ('auto_dsr', '0024_rename_user_id_usersetting_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('flight_id',), name='flight_id'),
        ),
    ]
