# Generated by Django 4.2.2 on 2024-06-27 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0026_auto_20240610_0957"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aircraft", "0019_flight_flight_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAircraft",
            fields=[
                ("serial", models.CharField(db_index=True, max_length=32, verbose_name="Aircraft Serial Number")),
                ("model", models.CharField(max_length=16, verbose_name="Aircraft Mission Design Series")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FMC", "Fully Mission Capable"),
                            ("PMC", "Partially Mission Capable"),
                            ("PMCM", "Partially Mission Capable - Maintenance"),
                            ("PMCS", "Partially Mission Capable - Sustainment"),
                            ("NMC", "Non Mission Capable"),
                            ("NMCS", "Non Mission Capable - Supply"),
                            ("NMCM", "Non Mission Capable - Maintenance"),
                            ("FIELD", "Field"),
                            ("SUST", "Sustainment"),
                            ("DADE", "Department of the Army Directed Event"),
                            ("MTF", "Maintenance Test Flight"),
                            ("MOC", "Maintenance Operational Check"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=5,
                        verbose_name="Maintenance Status (FMC, NMC)",
                    ),
                ),
                ("rtl", models.CharField(max_length=4, verbose_name="Ready to Launch Status (RTL, NRTL)")),
                ("total_airframe_hours", models.FloatField(verbose_name="Lifetime Flight Hours for that Airframe")),
                (
                    "flight_hours",
                    models.FloatField(default=0.0, verbose_name="Hours Flown in the current reporting period"),
                ),
                (
                    "in_phase",
                    models.BooleanField(
                        default=False, verbose_name="An indicator for if the aircraft is currently in phase"
                    ),
                ),
                (
                    "phase_start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="The date the current phase began (if the aircraft is in phase)",
                    ),
                ),
                ("hours_to_phase", models.FloatField(verbose_name="Flight Hours Until Phase Inspection")),
                (
                    "remarks",
                    models.TextField(blank=True, max_length=2048, null=True, verbose_name="Displayed Aircraft Remarks"),
                ),
                (
                    "date_down",
                    models.DateField(blank=True, null=True, verbose_name="Date Aircraft Entered non-FMC status"),
                ),
                (
                    "ecd",
                    models.DateField(
                        blank=True, null=True, verbose_name="Estimated Completion Date for non-FMC Aircraft"
                    ),
                ),
                (
                    "should_sync",
                    models.BooleanField(
                        default=True, verbose_name="An indicator if the aircraft should be updated automatically"
                    ),
                ),
                ("last_sync_time", models.DateTimeField(verbose_name="Last Sync from ACN")),
                (
                    "last_export_upload_time",
                    models.DateTimeField(verbose_name="Last time this aircraft was updated from an ACD Export Upload"),
                ),
                ("last_update_time", models.DateTimeField(verbose_name="Last Edit on this Aircraft made in Griffin")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "current_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="current_unit_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aircraft",
                "verbose_name_plural": "historical aircraft",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
