# Generated by Django 4.2.2 on 2024-07-12 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0021_alter_da_1352_source_and_more"),
        ("aircraft", "0021_remove_historicalaircraft_history_user_and_more"),
    ]

    operations = []
