# Generated by Django 4.2.2 on 2024-07-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0026_auto_20240610_0957"),
        ("aircraft", "0022_merge_20240711_2002"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DA_1352",
            new_name="Raw_DA_1352",
        ),
    ]
