# Generated by Django 4.2.2 on 2024-07-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0026_auto_20240610_0957"),
        ("aircraft", "0023_rename_da_1352_raw_da_1352"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raw_da_1352",
            options={"verbose_name": "Raw DA 1352", "verbose_name_plural": "Raw DA 1352s"},
        ),
        migrations.CreateModel(
            name="DA_1352",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("reporting_month", models.DateField(verbose_name="The month the report is in reference to")),
                ("model_name", models.CharField(max_length=18, verbose_name="The aircraft model")),
                (
                    "flying_hours",
                    models.FloatField(default=0.0, verbose_name="Hours Flown in the current reporting period"),
                ),
                ("fmc_hours", models.FloatField(verbose_name="Hours FMC in reporting period")),
                ("field_hours", models.FloatField(verbose_name="Hours in 'FIELD' status in reporting period")),
                ("pmcm_hours", models.FloatField(verbose_name="Hours in 'PMCM' status in reporting period")),
                ("pmcs_hours", models.FloatField(verbose_name="Hours in 'PMCS' status in reporting period")),
                ("dade_hours", models.FloatField(verbose_name="Hours in 'DADE' status in reporting period")),
                ("sust_hours", models.FloatField(verbose_name="Hours in 'SUST' status in reporting period")),
                ("nmcs_hours", models.FloatField(verbose_name="Hours in 'NMCS' status in reporting period")),
                (
                    "nmcm_hours",
                    models.FloatField(
                        verbose_name="Hours in 'NMCM' status in reporting period (sum of DADE, SUST, and FIELD)"
                    ),
                ),
                ("total_hours_in_status_per_month", models.FloatField(verbose_name="Total number of hours in a month")),
                (
                    "total_reportable_hours_in_month",
                    models.FloatField(verbose_name="Totel number of reporting hours available. (Subracted DADE)"),
                ),
                ("last_updated", models.DateTimeField(verbose_name="The time the record was last updated")),
                ("source", models.CharField(max_length=16, verbose_name="The source for this record")),
                (
                    "aircraft",
                    models.ForeignKey(
                        db_column="serial_number",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "reporting_uic",
                    models.ForeignKey(
                        db_column="reporting_uic", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit"
                    ),
                ),
            ],
            options={
                "verbose_name": "DA 1352",
                "verbose_name_plural": "DA 1352s",
                "db_table": "aircraft_da_1352s",
            },
        ),
        migrations.AddConstraint(
            model_name="da_1352",
            constraint=models.UniqueConstraint(
                fields=("aircraft", "reporting_uic", "reporting_month"), name="aircraft_monthly_report"
            ),
        ),
    ]
