# Generated by Django 4.2.2 on 2024-08-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0030_equipmentmodel_alter_equipment_serial_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="field_sync_status",
            field=models.JSONField(default=dict, verbose_name="Defines whether individual fields should update"),
        ),
        migrations.AddField(
            model_name="historicalaircraft",
            name="field_sync_status",
            field=models.JSONField(default=dict, verbose_name="Defines whether individual fields should update"),
        ),
    ]
