# Generated by Django 3.2.6 on 2023-03-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0005_auto_20230129_0331"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskforce",
            name="id",
        ),
        migrations.AlterField(
            model_name="inspection",
            name="inspection_name",
            field=models.CharField(
                max_length=64, verbose_name="Inspection Display Name"
            ),
        ),
        migrations.AlterField(
            model_name="taskforce",
            name="uic",
            field=models.OneToOneField(
                db_column="uic",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="auto_dsr.unit",
            ),
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "last_conducted_hours",
                    models.FloatField(
                        verbose_name="Aircraft Hours When last conducted"
                    ),
                ),
                (
                    "hours_interval",
                    models.IntegerField(
                        verbose_name="Maximum Flying Hours between phase"
                    ),
                ),
                (
                    "next_due_hours",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Aircraft Hours the Phase must begin before",
                    ),
                ),
                (
                    "phase_type",
                    models.CharField(
                        choices=[
                            ("PMI1", "UH-60 PMI One"),
                            ("PMI2", "UH-60 PMI Two"),
                            ("FM1", "CH-47 PMI One"),
                            ("FM2", "CH-47 PMI Two"),
                            ("FM3", "CH-47 PMI Three"),
                            ("GEN", "Generic PMI"),
                        ],
                        default="GEN",
                        max_length=4,
                        verbose_name="Phase Inspection Type",
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        blank=True,
                        db_column="serial",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auto_dsr.aircraft",
                    ),
                ),
            ],
        ),
    ]
