# Generated by Django 3.2.6 on 2023-04-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0005_auto_20230129_0331"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReassignedAircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "changed_on",
                    models.DateTimeField(verbose_name="The time the change occured"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        db_column="changed_by_dodid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "new_uic",
                    models.ForeignKey(
                        db_column="new_uic",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="added_aircraft",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "previous_uic",
                    models.ForeignKey(
                        db_column="previous_uic",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="removed_aircraft",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "serial_number",
                    models.ForeignKey(
                        db_column="serial_number",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="auto_dsr.aircraft",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reassigned Aircraft",
                "db_table": "reassigned_aircraft",
            },
        ),
    ]
