# Generated by Django 3.2.6 on 2023-03-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0007_alter_phase_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phase",
            name="id",
        ),
        migrations.AlterField(
            model_name="phase",
            name="serial",
            field=models.OneToOneField(
                db_column="serial",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="auto_dsr.aircraft",
            ),
        ),
    ]
