# Generated by Django 4.2.2 on 2023-06-19 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0006_reassignedaircraft"),
        ("auto_dsr", "0008_auto_20230323_0950"),
    ]

    operations = []
