# Generated by Django 4.2.2 on 2023-07-11 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0009_merge_0006_reassignedaircraft_0008_auto_20230323_0950"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="AutoGenerated Unique Id",
                    ),
                ),
                ("login_time", models.DateTimeField(verbose_name="User Login Time")),
            ],
            options={
                "db_table": "user_logins",
            },
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.UniqueConstraint(
                fields=("serial", "inspection_name"), name="inspection_for_serial"
            ),
        ),
        migrations.AddField(
            model_name="login",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="auto_dsr.user",
            ),
        ),
    ]
