# Generated by Django 4.2.2 on 2023-07-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0010_login_inspection_inspection_for_serial_login_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(db_column='unit_uic', default='WDYFAA', on_delete=django.db.models.deletion.DO_NOTHING, to='auto_dsr.unit'),
            preserve_default=False,
        ),
    ]
