# Generated by Django 4.2.2 on 2023-07-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0011_user_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True, verbose_name='Flag to identify Griffin admin users'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Generated Unique Id')),
                ('access_level', models.CharField(choices=[('Read', 'Read'), ('Write', 'Write'), ('Admin', 'Admin')], default='Read', max_length=5, verbose_name="User's Role for this unit")),
                ('unit', models.ForeignKey(db_column='unit_uic', on_delete=django.db.models.deletion.CASCADE, to='auto_dsr.unit')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='auto_dsr.user')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
    ]
