# Generated by Django 4.2.2 on 2023-08-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0012_user_is_admin_userrole'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user_id', 'unit'), name='unique_role_in_unit'),
        ),
    ]
