# Generated by Django 4.2.2 on 2023-08-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0013_userrole_unique_role_in_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='access_level',
            field=models.CharField(choices=[('Read', 'Read'), ('Write', 'Write'), ('Admin', 'Admin')], default='Read', max_length=5, verbose_name="User's Requested Role for this unit"),
        ),
    ]
