# Generated by Django 4.2.2 on 2023-08-31 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0015_remove_aircrafteditlog_serial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPhaseOrder',
            fields=[
                ('uic', models.OneToOneField(db_column='uic', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auto_dsr.unit')),
                ('phase_order', models.JSONField(verbose_name='A list of all aircraft in the unit in phase flow order')),
                ('last_updated', models.DateTimeField(verbose_name='Last User To Update Phase Schedule')),
                ('last_changed_by_user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='auto_dsr.user')),
            ],
            options={
                'db_table': 'unit_phase_orders',
            },
        ),
    ]
