# Generated by Django 4.2.2 on 2023-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0018_taskforce_readiness_uic"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userrequest",
            constraint=models.UniqueConstraint(
                fields=("user_id", "uic"), name="user_request_in_unit"
            ),
        ),
    ]
