# Generated by Django 4.2.2 on 2023-10-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0019_userrequest_user_request_in_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="nick_name",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Unit Nick Name"),
        ),
    ]
