# Generated by Django 4.2.2 on 2024-02-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0020_unit_nick_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="echelon",
            field=models.CharField(
                choices=[
                    ("TM", "Team"),
                    ("SQD", "Squad"),
                    ("SEC", "Section"),
                    ("PLT", "Platoon"),
                    ("DET", "Detachment"),
                    ("CO", "Company"),
                    ("BN", "Battalion"),
                    ("BDE", "Brigade"),
                    ("DIV", "Division"),
                    ("CORPS", "Corps"),
                    ("MACOM", "Major Command"),
                    ("CNTR", "Center"),
                    ("ARMY", "Army"),
                    ("DRU", "Direct Reporting Unit"),
                    ("ASCC", "Army Service Component Command"),
                    ("ACOM", "Army Command"),
                    ("HQ", "Headquarters"),
                    ("MILSVC", "Military Service"),
                    ("STATE", "State Army National Guard"),
                    ("FACILITY", "Aviation Support Facility"),
                    ("MSC", "Major Subordinate Command"),
                    ("CONTAINER", "Container for Organizing Units"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=16,
                verbose_name="Unit Echelon",
            ),
        ),
    ]
