# Generated by Django 4.2.2 on 2024-03-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0022_acdexport"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name="Location Abbreviation"),
        ),
        migrations.AddField(
            model_name="location",
            name="alternate_name",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Alternate Location Name"),
        ),
        migrations.AddField(
            model_name="location",
            name="short_name",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Location Short Name"),
        ),
    ]
