# Generated by Django 4.2.2 on 2024-04-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0023_location_abbreviation_location_alternate_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersetting",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="usersetting",
            name="key",
        ),
        migrations.RemoveField(
            model_name="usersetting",
            name="value",
        ),
        migrations.AddField(
            model_name="usersetting",
            name="preferences",
            field=models.JSONField(
                default=dict, verbose_name="Storing user preferences by functionality with associated dictionary"
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="unit",
            field=models.ForeignKey(
                db_column="unit_uic", default=None, on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.unit"
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="usersetting",
            constraint=models.UniqueConstraint(fields=("user", "unit"), name="user_setting_unique_user_unit"),
        ),
        migrations.AlterModelTable(
            name="usersetting",
            table="user_setting",
        ),
    ]
