# Generated by Django 4.2.2 on 2024-07-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0026_auto_20240610_0957"),
    ]

    operations = [
        migrations.AddField(
            model_name="acdexport",
            name="upload_type",
            field=models.CharField(default="xlsx", max_length=4, verbose_name="The type of upload being conducted"),
            preserve_default=False,
        ),
    ]
