# Generated by Django 5.0.1 on 2024-07-04 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0028_remove_user_can_edit_delete_canedit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("title", models.CharField(max_length=128, verbose_name="Position title")),
                ("abbreviation", models.CharField(max_length=16, verbose_name="Position abbreviation")),
            ],
            options={
                "db_table": "auto_dsr_positions",
            },
        ),
        migrations.CreateModel(
            name="UserPosition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
            ],
            options={
                "db_table": "auto_dsr_user_positions",
            },
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(fields=("title",), name="position_titles"),
        ),
        migrations.AddField(
            model_name="userposition",
            name="position",
            field=models.ForeignKey(
                db_column="position_id", on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.position"
            ),
        ),
        migrations.AddField(
            model_name="userposition",
            name="unit",
            field=models.ForeignKey(
                db_column="unit_uic", on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.unit"
            ),
        ),
        migrations.AddField(
            model_name="userposition",
            name="user",
            field=models.ForeignKey(
                db_column="user_id", on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.user"
            ),
        ),
        migrations.AddConstraint(
            model_name="userposition",
            constraint=models.UniqueConstraint(fields=("unit", "position"), name="position_in_unit"),
        ),
    ]
