# Generated by Django 5.0.1 on 2024-07-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0029_position_userposition_position_position_titles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='slogan',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Unit Slogan'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='DOD email'),
        ),
    ]
