# Generated by Django 5.0.1 on 2024-07-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0027_acdexport_upload_type'),
        ('auto_dsr', '0030_unit_slogan_user_email'),
    ]

    operations = [
    ]
