# Generated by Django 4.2.2 on 2025-01-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0031_merge_20240725_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receive_emails",
            field=models.BooleanField(default=False, verbose_name="Receive E-mail notifications"),
        ),
    ]
