# Generated by Django 4.2.2 on 2025-02-05 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0032_user_recieve_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrequest",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="date_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="status",
            field=models.CharField(
                choices=[("Archived", "Archived"), ("New", "New"), ("Pending", "Pending"), ("Closed", "Closed")],
                default="New",
                max_length=8,
                verbose_name="Status of the request",
            ),
        ),
    ]
