# Generated by Django 4.2.2 on 2025-02-17 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("uas", "0011_historicaluav_equipment_number_uav_equipment_number"),
        ("auto_dsr", "0033_userrequest_date_created_userrequest_date_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttransferrequest",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="object_transfer_requests_updated",
                to="auto_dsr.user",
            ),
        ),
        migrations.AddField(
            model_name="objecttransferrequest",
            name="last_updated_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="objecttransferrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Archived", "Archived"),
                    ("New", "New"),
                    ("Pending", "Pending"),
                    ("Updated", "Updated"),
                    ("Closed", "Closed"),
                ],
                default="New",
                max_length=8,
                verbose_name="Status of the request",
            ),
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Archived", "Archived"),
                    ("New", "New"),
                    ("Pending", "Pending"),
                    ("Updated", "Updated"),
                    ("Closed", "Closed"),
                ],
                default="New",
                max_length=8,
                verbose_name="Status of the request",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalObjectTransferRequest",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="Auto Unique Id")),
                (
                    "requested_object_type",
                    models.CharField(
                        choices=[("AIR", "Aircraft"), ("UAC", "UAC"), ("UAV", "UAV")],
                        max_length=5,
                        verbose_name="The type of object being requested",
                    ),
                ),
                (
                    "originating_unit_approved",
                    models.BooleanField(
                        default=False,
                        verbose_name="Boolean indicating if the originating unit has approved the transfer",
                    ),
                ),
                (
                    "destination_unit_approved",
                    models.BooleanField(
                        default=False,
                        verbose_name="Boolean indicating if the destination unit has approved the transfer",
                    ),
                ),
                (
                    "permanent_transfer",
                    models.BooleanField(
                        default=False,
                        verbose_name="Boolean indicating if the transfer will remove instances of other units tracking on the originating unit hierarchy.",
                    ),
                ),
                ("date_requested", models.DateField(verbose_name="Date the Transfer Request was created")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Archived", "Archived"),
                            ("New", "New"),
                            ("Pending", "Pending"),
                            ("Updated", "Updated"),
                            ("Closed", "Closed"),
                        ],
                        default="New",
                        max_length=8,
                        verbose_name="Status of the request",
                    ),
                ),
                ("last_updated_datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "destination_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="destination_unit_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "originating_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="originating_unit_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "requested_aircraft",
                    models.ForeignKey(
                        blank=True,
                        db_column="requested_aircraft_serial_number",
                        db_constraint=False,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "requested_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="requsted_by_user_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "requested_uac",
                    models.ForeignKey(
                        blank=True,
                        db_column="requested_uac_serial_number",
                        db_constraint=False,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="uas.uac",
                    ),
                ),
                (
                    "requested_uav",
                    models.ForeignKey(
                        blank=True,
                        db_column="requested_uav_serial_number",
                        db_constraint=False,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="uas.uav",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical object transfer request",
                "verbose_name_plural": "historical object transfer requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
