# Generated by Django 4.2.2 on 2025-02-24 18:40

import auto_dsr.model_utils.da2407_export_upload
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0034_objecttransferrequest_last_updated_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DA2407Export",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("upload_type", models.CharField(max_length=4, verbose_name="The type of upload being conducted")),
                ("uploaded_at", models.DateTimeField(verbose_name="The timestamp when this file was uploaded")),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        upload_to=auto_dsr.model_utils.da2407_export_upload.da_2407_export_upload_to,
                        verbose_name="Uploaded 2407 Export File",
                    ),
                ),
                (
                    "succeeded",
                    models.BooleanField(
                        default=False, verbose_name="A Boolean flag indicating if the upload succeeded"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_dodid", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.user"
                    ),
                ),
            ],
            options={
                "db_table": "da_2407_exports",
            },
        ),
    ]
