# Generated by Django 4.2.2 on 2025-03-06 16:22

from django.db import migrations, models


def remove_level(apps, schema_editor):
    """
    Removing the level would be handled by django as this is a new field on this table.
    """
    pass


def add_level(apps, schema_editor):
    """
    Adding level to all existing units.
    """
    UnitTable = apps.get_model("auto_dsr", "Unit")
    for unit in UnitTable.objects.all():
        level = 0
        current_unit = unit.parent_uic

        while current_unit != None:
            level += 1
            current_unit = current_unit.parent_uic

        unit.level = level
        unit.save()


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0035_da2407export"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="level",
            field=models.IntegerField(default=0, verbose_name="This unit's depth in the tree/hierarchy"),
        ),
        migrations.RunPython(add_level, remove_level),
    ]
