# Generated by Django 4.2.2 on 2025-03-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0036_unit_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="similar_units",
            field=models.JSONField(default=list, verbose_name="A list of units deemed similar by KNN Model"),
        ),
    ]
