# Generated by Django 4.2.2 on 2025-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0037_unit_similar_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawSyncTimestamp",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("table", models.CharField(max_length=64, verbose_name="Table name")),
                (
                    "most_recent_sync",
                    models.DateTimeField(verbose_name="Timestamp of the most recent data fetched for this table"),
                ),
            ],
            options={
                "verbose_name": "Raw Sync Timestamp",
                "verbose_name_plural": "Raw Sync Timestamps",
                "db_table": "raw_sync_timestamps",
            },
        ),
    ]
