# Generated by Django 4.2.21 on 2025-09-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0038_rawsynctimestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="global_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="global_unit_user",
                to="auto_dsr.unit",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="job_description",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Job Description"),
        ),
    ]
