# Generated by Django 4.2.21 on 2025-09-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0038_rawsynctimestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(null=True, verbose_name="Last Login Event for this user"),
        ),
    ]
