# Generated by Django 4.2.21 on 2025-09-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0038_rawsynctimestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteUnit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="uic",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="favorite_unit",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_unit",
                        to="auto_dsr.user",
                    ),
                ),
            ],
        ),
    ]
