# Generated by Django 4.2.21 on 2025-10-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0039_favoriteunit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavoriteUnit",
        ),
    ]
