# Generated by Django 4.2.21 on 2025-09-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0039_user_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="granted_on",
            field=models.DateField(blank=True, null=True, verbose_name="When was the last role granted"),
        ),
    ]
