# Generated by Django 4.2.21 on 2025-10-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0039_user_global_unit_user_job_description"),
        ("auto_dsr", "0040_userrole_granted_on"),
    ]

    operations = []
