# Generated by Django 4.2.21 on 2025-10-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0040_delete_favoriteunit"),
        ("auto_dsr", "0041_merge_20251001_1012"),
    ]

    operations = []
