# Generated by Django 4.2.25 on 2025-10-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0042_merge_20251002_1106'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrequest',
            name='user_request_in_unit',
        ),
        migrations.AddConstraint(
            model_name='userrequest',
            constraint=models.UniqueConstraint(fields=('user_id', 'uic', 'status'), name='user_request_in_unit'),
        ),
    ]
