# Generated by Django 4.2.4 on 2023-08-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_alter_soldiertasklists_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='task_lists',
        ),
        migrations.DeleteModel(
            name='SoldierTasklists',
        ),
    ]
