# Generated by Django 4.2.4 on 2023-11-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_soldier_pfc_dor_soldier_pv2_dor_soldier_sfc_dor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='child_uics',
            field=models.JSONField(default=list, verbose_name='A list of all immediate child uics to this unit.'),
        ),
        migrations.AddField(
            model_name='unit',
            name='nick_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Unit Nick Name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent_uics',
            field=models.JSONField(default=list, verbose_name='A list of all uics over this one in the hierarchy.'),
        ),
        migrations.AddField(
            model_name='unit',
            name='subordinate_uics',
            field=models.JSONField(default=list, verbose_name='A list of all uics subordinate to this one.'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Generated Unique Id')),
                ('access_level', models.CharField(choices=[('Basic', 'Basic'), ('Evaluator', 'Evaluator'), ('Manager', 'Manager')], default='Basic', max_length=9, verbose_name="User's Role for this unit")),
                ('unit', models.ForeignKey(db_column='unit_uic', on_delete=django.db.models.deletion.CASCADE, to='personnel.unit')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='personnel.soldier')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('access_level', models.CharField(choices=[('Basic', 'Basic'), ('Evaluator', 'Evaluator'), ('Manager', 'Manager')], default='Basic', max_length=9, verbose_name="User's Requested Role for this unit")),
                ('uic', models.ForeignKey(db_column='uic', on_delete=django.db.models.deletion.CASCADE, to='personnel.unit')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='personnel.soldier')),
            ],
            options={
                'db_table': 'user_requests',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='AutoGenerated Unique Id')),
                ('login_time', models.DateTimeField(verbose_name='User Login Time')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.soldier')),
            ],
            options={
                'db_table': 'user_logins',
            },
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user_id', 'unit'), name='unique_role_in_unit'),
        ),
        migrations.AddConstraint(
            model_name='userrequest',
            constraint=models.UniqueConstraint(fields=('user_id', 'uic'), name='user_request_in_unit'),
        ),
    ]
