# Generated by Django 4.2.4 on 2023-11-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_unit_child_uics_unit_nick_name_unit_parent_uics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='is_maintainer',
            field=models.BooleanField(default=True, verbose_name='Flag to identify Maintainers'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='access_level',
            field=models.CharField(choices=[('Viewer', 'Viewer'), ('Evaluator', 'Evaluator'), ('Manager', 'Manager')], default='Viewer', max_length=9, verbose_name="User's Requested Role for this unit"),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='access_level',
            field=models.CharField(choices=[('Viewer', 'Viewer'), ('Evaluator', 'Evaluator'), ('Manager', 'Manager')], default='Viewer', max_length=9, verbose_name="User's Role for this unit"),
        ),
    ]
