# Generated by Django 4.2.4 on 2024-03-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_soldiertransferrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='birth_month',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December'), ('UNK', 'Unknown')], default='UNK', max_length=3, verbose_name='Birth Month'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='dod_email',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='DOD Email'),
        ),
    ]
