# Generated by Django 4.2.2 on 2024-05-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_soldier_birth_month_soldier_dod_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='mos',
            field=models.CharField(blank=True, choices=[('15B', 'Aircraft Power Plant Repairer'), ('15D', 'Aircraft Powertrain Repairer'), ('15E', 'RQ-7 Unmanned Aircraft Systems Repairer'), ('15F', 'Aircraft Electrician'), ('15G', 'Aircraft Structural Repairer'), ('15H', 'Aircraft Pneudraulics Repairer'), ('15M', 'MQ-1 unmanned Aircraft Systems Repairer'), ('15N', 'Avionic Mechanic'), ('15R', 'AH-64 Attach Helicopter Repairer'), ('15T', 'UH-60 Utility Helicopter Repairer'), ('15U', 'CH-47 Cargo Helicopter Repairer'), ('15Y', 'AH-64 Armament/Electrical/Avionic Systems Repairer')], max_length=4, null=True, verbose_name='MOS'),
        ),
    ]
