# Generated by Django 4.2.4 on 2024-08-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0016_historicalsoldier_historicalsoldierflag_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsoldierflag",
            name="available_for_mx",
        ),
        migrations.RemoveField(
            model_name="historicalsoldierflag",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalsoldierflag",
            name="mx_restrictions",
        ),
        migrations.RemoveField(
            model_name="soldierflag",
            name="available_for_mx",
        ),
        migrations.RemoveField(
            model_name="soldierflag",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="soldierflag",
            name="mx_restrictions",
        ),
        migrations.AddField(
            model_name="historicalsoldierflag",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                db_column="last_modified_by",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="personnel.soldier",
            ),
        ),
        migrations.AddField(
            model_name="historicalsoldierflag",
            name="mx_availability",
            field=models.CharField(
                choices=[
                    ("Available", "Soldier is available to conduct MX"),
                    ("Limited", "Soldier is available but limited"),
                    ("Unavailable", "Soldier is unavailable"),
                ],
                default="Unavailable",
                max_length=25,
                verbose_name="Soldier Availability to conduct MX",
            ),
        ),
        migrations.AddField(
            model_name="historicalsoldierflag",
            name="tasking_flag_info",
            field=models.CharField(
                blank=True,
                choices=[("Internal", "Internal Tasking"), ("External", "External Tasking")],
                max_length=25,
                null=True,
                verbose_name="Tasking Flag Info",
            ),
        ),
        migrations.AddField(
            model_name="soldierflag",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                db_column="last_modified_by",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="created_modified_flags",
                to="personnel.soldier",
            ),
        ),
        migrations.AddField(
            model_name="soldierflag",
            name="mx_availability",
            field=models.CharField(
                choices=[
                    ("Available", "Soldier is available to conduct MX"),
                    ("Limited", "Soldier is available but limited"),
                    ("Unavailable", "Soldier is unavailable"),
                ],
                default="Unavailable",
                max_length=25,
                verbose_name="Soldier Availability to conduct MX",
            ),
        ),
        migrations.AddField(
            model_name="soldierflag",
            name="tasking_flag_info",
            field=models.CharField(
                blank=True,
                choices=[("Internal", "Internal Tasking"), ("External", "External Tasking")],
                max_length=25,
                null=True,
                verbose_name="Tasking Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsoldierflag",
            name="admin_flag_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Leave", "Soldier on leave"),
                    ("TDY", "Soldier is on TDY"),
                    ("SFL TAP", "Soldier is in Soldier For Life - Transition Assistance Program"),
                    ("CSP", "Soldier is in the Career Skills Program"),
                    ("ASAP", "Soldier is in the Army Substance Abuse Prevention Program"),
                    ("Pending Negative Action", "Soldier is pending negative action"),
                    ("Active Investigation", "Soldier is under investigation"),
                    ("Other", "Other Administrative Flag"),
                ],
                max_length=25,
                null=True,
                verbose_name="Administrative Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsoldierflag",
            name="flag_type",
            field=models.CharField(
                choices=[
                    ("Administrative", "Administrative Flag"),
                    ("Unit/Position", "Unit/Positional Flag"),
                    ("Tasking", "Tasking Flag"),
                    ("Other", "Other Flag Type"),
                ],
                default="Other",
                max_length=15,
                verbose_name="Type of Soldier Flag",
            ),
        ),
        migrations.AlterField(
            model_name="soldierflag",
            name="admin_flag_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Leave", "Soldier on leave"),
                    ("TDY", "Soldier is on TDY"),
                    ("SFL TAP", "Soldier is in Soldier For Life - Transition Assistance Program"),
                    ("CSP", "Soldier is in the Career Skills Program"),
                    ("ASAP", "Soldier is in the Army Substance Abuse Prevention Program"),
                    ("Pending Negative Action", "Soldier is pending negative action"),
                    ("Active Investigation", "Soldier is under investigation"),
                    ("Other", "Other Administrative Flag"),
                ],
                max_length=25,
                null=True,
                verbose_name="Administrative Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="soldierflag",
            name="flag_type",
            field=models.CharField(
                choices=[
                    ("Administrative", "Administrative Flag"),
                    ("Unit/Position", "Unit/Positional Flag"),
                    ("Tasking", "Tasking Flag"),
                    ("Other", "Other Flag Type"),
                ],
                default="Other",
                max_length=15,
                verbose_name="Type of Soldier Flag",
            ),
        ),
    ]
