# Generated by Django 4.2.2 on 2024-08-21 16:27

from django.db import migrations, models
import django.db.models.deletion

from personnel.model_utils import MosCode


def import_mos_to_foreign_key(apps, schema_editor):
    Soldier = apps.get_model("personnel", "Soldier")
    MOSCode = apps.get_model("personnel", "MOSCode")
    for soldier in Soldier.objects.all():
        try:
            mos, created = MOSCode.objects.get_or_create(mos=soldier.legacy_mos)

            if created and mos.mos in MosCode.values:
                mos.mos_description = MosCode(mos.mos).label
                mos.save()
        except:
            mos = None
        soldier.mos = mos
        soldier.save()

def import_foreign_key_to_mos(apps, schema_editor):
    Soldier = apps.get_model("personnel", "Soldier")
    for soldier in Soldier.objects.all():
        try:
            if soldier.mos:
                mos = soldier.mos.mos
            else:
                mos = None

            if mos and mos not in MosCode.values:
                mos = None

            soldier.legacy_mos = mos

            soldier.save()

        except:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0019_soldierflag_unit_flags_unique_when_soldier_is_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="MOSCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Generated Unique Id")),
                ("mos", models.CharField(max_length=10, verbose_name="MOS")),
                ("mos_description", models.CharField(max_length=128, verbose_name="MOS Description")),
                ("amtp_mos", models.BooleanField(default=False, verbose_name="Current MOS for AMTP based purposes")),
                ("ictl_mos", models.BooleanField(default=False, verbose_name="Current MOS for ICTL based purposes")),
            ],
            options={
                "db_table": "personnel_mos_codes",
            },
        ),
        migrations.AddConstraint(
            model_name="moscode",
            constraint=models.UniqueConstraint(fields=("mos",), name="unique_mos_code"),
        ),
        migrations.RenameField(
            model_name="historicalsoldier",
            old_name="mos",
            new_name="legacy_mos",
        ),
        migrations.RenameField(
            model_name="soldier",
            old_name="mos",
            new_name="legacy_mos",
        ),
        migrations.AddField(
            model_name="historicalsoldier",
            name="mos",
            field=models.ForeignKey(
                blank=True,
                db_column="mos",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="personnel.moscode",
            ),
        ),
        migrations.AddField(
            model_name="soldier",
            name="mos",
            field=models.ForeignKey(
                blank=True,
                db_column="mos",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="personnel.moscode",
            ),
        ),
        migrations.RunPython(import_mos_to_foreign_key, import_foreign_key_to_mos),
        migrations.RemoveField(
            model_name="historicalsoldier",
            name="legacy_mos",
        ),
        migrations.RemoveField(
            model_name="soldier",
            name="legacy_mos",
        ),
    ]
