# Generated by Django 4.2.2 on 2023-08-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0015_remove_aircrafteditlog_serial_and_more'),
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DA_1352',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_month', models.DateField(verbose_name='The month the report is in reference to')),
                ('model_name', models.CharField(max_length=18, verbose_name='The month the report is in reference to')),
                ('flying_hours', models.FloatField(default=0.0, verbose_name='Hours Flown in the current reporting period')),
                ('fmc_hours', models.FloatField(verbose_name='Hours FMC in reporting period')),
                ('field_hours', models.FloatField(verbose_name="Hours in 'FIELD' status in reporting period")),
                ('pmcm_hours', models.FloatField(verbose_name="Hours in 'PMCM' status in reporting period")),
                ('pmcs_hours', models.FloatField(verbose_name="Hours in 'PMCS' status in reporting period")),
                ('dade_hours', models.FloatField(verbose_name="Hours in 'DADE' status in reporting period")),
                ('sust_hours', models.FloatField(verbose_name="Hours in 'SUST' status in reporting period")),
                ('nmcs_hours', models.FloatField(verbose_name="Hours in 'NMCS' status in reporting period")),
                ('nmcm_hours', models.FloatField(verbose_name="Hours in 'NMCM' status in reporting period (sum of DADE, SUST, and FIELD)")),
                ('total_hours_in_status_per_month', models.FloatField(verbose_name='Total number of reportable hours in a month')),
                ('reporting_uic', models.ForeignKey(db_column='reporting_uic', on_delete=django.db.models.deletion.DO_NOTHING, to='auto_dsr.unit')),
                ('serial_number', models.ForeignKey(db_column='serial_number', on_delete=django.db.models.deletion.DO_NOTHING, to='aircraft.aircraft')),
            ],
            options={
                'verbose_name': 'DA 1352',
                'verbose_name_plural': 'DA 1352s',
                'db_table': 'raw_1352',
            },
        ),
    ]
