# Generated by Django 4.2.2 on 2023-08-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_da_1352'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unitaircraft',
            constraint=models.UniqueConstraint(fields=('serial', 'uic'), name='aircraft_in_unit'),
        ),
    ]
