# Generated by Django 4.2.2 on 2023-09-10 23:42

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0017_unit_child_uics_unit_parent_uics_and_more"),
        ("aircraft", "0004_alter_aircraft_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="current_unit",
            field=models.ForeignKey(
                db_column="current_unit_uic",
                default="WDARFF",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="currently_assigned_aircraft",
                to="auto_dsr.unit",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aircraft",
            name="last_export_upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1775, 6, 14, 0, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Last time this aircraft was updated from an ACD Export Upload",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aircraft",
            name="last_update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1775, 6, 14, 0, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Last Edit on this Aircraft made in Griffin",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="uic",
            field=models.ManyToManyField(
                related_name="aircraft",
                through="aircraft.UnitAircraft",
                to="auto_dsr.unit",
            ),
        ),
    ]
