# Generated by Django 4.2.2 on 2023-11-25 19:16

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0020_unit_nick_name"),
        ("aircraft", "0005_aircraft_current_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppliedModification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FMC", "Fully Mission Capable"),
                            ("PMC", "Partially Mission Capable"),
                            ("PMCM", "Partially Mission Capable - Maintenance"),
                            ("PMCS", "Partially Mission Capable - Sustainment"),
                            ("NMC", "Non Mission Capable"),
                            ("NMCS", "Non Mission Capable - Supply"),
                            ("NMCM", "Non Mission Capable - Maintenance"),
                            ("MTF", "Maintenance Test Flight"),
                            ("UNK", "Unknown"),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name="The status of the modification (if applicable)",
                    ),
                ),
                (
                    "installed",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Logical Binary value to track if a modification is installed on this aircraft.",
                    ),
                ),
                (
                    "count",
                    models.FloatField(
                        blank=True, null=True, verbose_name="The count describing the modification's usage"
                    ),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        db_column="aircraft_serial_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.aircraft",
                    ),
                ),
            ],
            options={
                "db_table": "aircraft_applied_modifications",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "serial_number",
                    models.CharField(
                        max_length=32, primary_key=True, serialize=False, verbose_name="Equipment Serial Number"
                    ),
                ),
                ("model", models.CharField(max_length=16, verbose_name="Equipment Model")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FMC", "Fully Mission Capable"),
                            ("PMC", "Partially Mission Capable"),
                            ("PMCM", "Partially Mission Capable - Maintenance"),
                            ("PMCS", "Partially Mission Capable - Sustainment"),
                            ("NMC", "Non Mission Capable"),
                            ("NMCS", "Non Mission Capable - Supply"),
                            ("NMCM", "Non Mission Capable - Maintenance"),
                            ("MTF", "Maintenance Test Flight"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=5,
                        verbose_name="Equipment Status",
                    ),
                ),
                ("value", models.FloatField(blank=True, default=0, null=True, verbose_name="Current Value for Equip")),
                (
                    "value_code",
                    models.CharField(
                        choices=[
                            ("HRS", "Hours"),
                            ("RNDS", "Rounds"),
                            ("CYCLES", "Cycles"),
                            ("STARTS", "Starts"),
                            ("OTH", "Other"),
                            ("UNK", "Unknown"),
                        ],
                        default="HRS",
                        max_length=8,
                        verbose_name="Equipment Value Code",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="User provided Remarks for a given piece of Equipment",
                    ),
                ),
                (
                    "date_down",
                    models.DateField(blank=True, null=True, verbose_name="Date Equipment entered an NMC status"),
                ),
                (
                    "ecd",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date Equipment is expected to enter an FMC status"
                    ),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True,
                        db_column="aircraft_serial_number",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "current_unit",
                    models.ForeignKey(
                        db_column="current_unit_uic",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="currently_assigned_equipment",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Equipment",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "number",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Message identifying code (ie. ASAM-001)",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("SAFETY", "Safety"), ("MAINTENANCE", "Maintenance"), ("OTHER", "Other")],
                        default="SAFETY",
                        max_length=16,
                        verbose_name="The type of message (safety, maintenance, etc.)",
                    ),
                ),
                ("publication_date", models.DateField(verbose_name="The date the message was published")),
                (
                    "compliance_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="The date by which the message's instructions must be complied with",
                    ),
                ),
                (
                    "contents",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="The text contents of the message"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Modification",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="The Aircraft Modification's name (ie. Wings, Tanks, FRIES)",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Status", "Status"),
                            ("Install", "Installable"),
                            ("Count", "Count"),
                            ("Categorical", "Categorical"),
                            ("Other", "Other"),
                        ],
                        default="Status",
                        max_length=16,
                        verbose_name="The type of modification to aid in tracking",
                    ),
                ),
                (
                    "applied_to_aircraft",
                    models.ManyToManyField(through="aircraft.AppliedModification", to="aircraft.aircraft"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitEquipment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "display_on_dsr",
                    models.BooleanField(
                        default=False, verbose_name="Logical if the equipment should be shown on the unit's DSR"
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        db_column="equipment_serial_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.equipment",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.unit"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Unit Equipment",
                "db_table": "unit_equipment",
            },
        ),
        migrations.CreateModel(
            name="ModificationCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("name", models.CharField(max_length=32, verbose_name="The category name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="A brief description of the modification category",
                    ),
                ),
                (
                    "modification",
                    models.ForeignKey(
                        db_column="modification_name",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.modification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aircraft Modification Cateogry",
                "verbose_name_plural": "Aircraft Modification Categories",
                "db_table": "aircraft_modification_categories",
            },
        ),
        migrations.CreateModel(
            name="MessageCompliance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="User provided Remarks for the given piece of Equipment",
                    ),
                ),
                (
                    "display_on_dsr",
                    models.BooleanField(default=False, verbose_name="Logic to display message remarks on the DSR"),
                ),
                (
                    "complete",
                    models.BooleanField(
                        default=False, verbose_name="Tracks if the aircraft has completed the message's requirements"
                    ),
                ),
                (
                    "completed_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="The date the aircraft completed the message's requirements"
                    ),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        db_column="aircraft_serial_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        db_column="message_number", on_delete=django.db.models.deletion.CASCADE, to="aircraft.message"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aircraft Message Compliance",
                "verbose_name_plural": "Aircraft Messages Compliance",
                "db_table": "aircraft_message_compliance",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="applicable_aircraft",
            field=models.ManyToManyField(through="aircraft.MessageCompliance", to="aircraft.aircraft"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="tracked_by_unit",
            field=models.ManyToManyField(through="aircraft.UnitEquipment", to="auto_dsr.unit"),
        ),
        migrations.AddField(
            model_name="appliedmodification",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="modification_category_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aircraft.modificationcategory",
            ),
        ),
        migrations.AddField(
            model_name="appliedmodification",
            name="modification",
            field=models.ForeignKey(
                db_column="modification_name", on_delete=django.db.models.deletion.CASCADE, to="aircraft.modification"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitequipment",
            constraint=models.UniqueConstraint(fields=("equipment", "unit"), name="equipment_in_unit"),
        ),
        migrations.AddConstraint(
            model_name="modificationcategory",
            constraint=models.UniqueConstraint(
                fields=("modification", "name"), name="unique_modification_category_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="modification",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="unique_modification_name_lower"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagecompliance",
            constraint=models.UniqueConstraint(fields=("aircraft", "message"), name="message_applies_to_aircraft"),
        ),
    ]
