# Generated by Django 4.2.2 on 2023-12-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0006_appliedmodification_equipment_message_modification_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="modificationcategory",
            name="unique_modification_category_name",
        ),
        migrations.RenameField(
            model_name='modificationcategory',
            old_name='name',
            new_name='value',
        ),
        migrations.AddConstraint(
            model_name="modificationcategory",
            constraint=models.UniqueConstraint(
                fields=("modification", "value"), name="unique_modification_category_value"
            ),
        ),
    ]
