# Generated by Django 4.2.2 on 2024-01-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0007_rename_modificationcategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedmodification",
            name="other",
            field=models.CharField(
                blank=True,
                max_length=2048,
                null=True,
                verbose_name="The value representation for any other user Modification",
            ),
        ),
        migrations.AlterField(
            model_name="modificationcategory",
            name="value",
            field=models.CharField(max_length=32, verbose_name="The category value"),
        ),
        migrations.AddConstraint(
            model_name="appliedmodification",
            constraint=models.UniqueConstraint(fields=("modification", "aircraft"), name="modification_on_aircraft"),
        ),
    ]
