# Generated by Django 4.2.2 on 2024-02-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0009_message_classification_message_confirmation_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftInspection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "last_completed_on",
                    models.DateField(blank=True, null=True, verbose_name="The date the inspection last occured on"),
                ),
                (
                    "next_due_on",
                    models.DateField(blank=True, null=True, verbose_name="The date the inspection is due by"),
                ),
                (
                    "last_completed_at",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="The reading for numerical frequency types when the inspection was last conducted",
                    ),
                ),
                (
                    "next_due_at",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="The reading for numerical frequency types by which the inspection must be conducted again",
                    ),
                ),
            ],
            options={
                "db_table": "aircraft_inspections",
            },
        ),
        migrations.CreateModel(
            name="InspectionReference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "dsr_display_name",
                    models.CharField(max_length=32, verbose_name="The text to display on the DSR for this inspection"),
                ),
                (
                    "description",
                    models.CharField(max_length=1028, verbose_name="Verbose Description of the inspection"),
                ),
                (
                    "code",
                    models.CharField(max_length=5, verbose_name="The alphanumeric code for the inspection, ie. A400"),
                ),
                (
                    "model",
                    models.CharField(max_length=16, verbose_name="The equipment model the inspection is performed on"),
                ),
                (
                    "regulation_reference",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="The inspection reference document"
                    ),
                ),
                (
                    "tracking_frequency_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Aircraft Hours", "Aircraft Hours"),
                            ("Hoist Hours", "Hoist Hours"),
                            ("Engine Hours", "Engine Hours"),
                            ("APU Hours", "Auxiliary Power Unit Hours"),
                            ("Aircraft Cycles", "Aircraft Cycles"),
                            ("Hoist Cycles", "Hoist Cycles"),
                            ("APU Starts", "Auxiliary Power Unit Starts"),
                            ("M230 Rounds", "M230 Rounds"),
                            ("Landings", "Aircraft Landings"),
                            ("Flights", "Aircraft Flights"),
                        ],
                        default="Aircraft Hours",
                        max_length=16,
                        null=True,
                        verbose_name="The category of frequency (days, hours, etc)",
                    ),
                ),
                (
                    "tracking_frequency",
                    models.FloatField(
                        blank=True, null=True, verbose_name="The numerical value of the frequency between inspections"
                    ),
                ),
                (
                    "calendar_frequency_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Days", "Calendar Days"),
                            ("Months", "Calendar Months"),
                            ("MonthsLastDay", "Last Day of Months"),
                            ("Years", "Calendar Years"),
                        ],
                        default="Days",
                        max_length=16,
                        null=True,
                        verbose_name="The calendar based category of frequency (days, months, etc)",
                    ),
                ),
                (
                    "calendar_frequency",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="The numerical value of the calendar frequency between inspections",
                    ),
                ),
            ],
            options={
                "db_table": "aircraft_inspection_references",
            },
        ),
        migrations.AddConstraint(
            model_name="inspectionreference",
            constraint=models.UniqueConstraint(
                fields=("code", "model", "tracking_frequency_type", "calendar_frequency_type"),
                name="inspection_for_model_at_frequency",
            ),
        ),
        migrations.AddField(
            model_name="aircraftinspection",
            name="aircraft",
            field=models.ForeignKey(
                blank=True,
                db_column="aircraft_serial_number",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspections",
                related_query_name="inspection",
                to="aircraft.aircraft",
            ),
        ),
        migrations.AddField(
            model_name="aircraftinspection",
            name="reference",
            field=models.ForeignKey(
                db_column="inspection_reference_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applied_inspections",
                related_query_name="applied_inspection",
                to="aircraft.inspectionreference",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftinspection",
            constraint=models.UniqueConstraint(fields=("aircraft", "reference"), name="inspection_due_for_aircraft"),
        ),
    ]
