# Generated by Django 4.2.2 on 2024-03-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0010_aircraftinspection_inspectionreference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="in_phase",
            field=models.BooleanField(
                default=False, verbose_name="An indicator for if the aircraft is currently in phase"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="phase_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="The date the current phase began (if the aircraft is in phase)"
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="should_sync",
            field=models.BooleanField(
                default=True, verbose_name="An indicator if the aircraft should be updated automatically"
            ),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="status",
            field=models.CharField(
                choices=[
                    ("FMC", "Fully Mission Capable"),
                    ("PMC", "Partially Mission Capable"),
                    ("PMCM", "Partially Mission Capable - Maintenance"),
                    ("PMCS", "Partially Mission Capable - Sustainment"),
                    ("NMC", "Non Mission Capable"),
                    ("NMCS", "Non Mission Capable - Supply"),
                    ("NMCM", "Non Mission Capable - Maintenance"),
                    ("FIELD", "Field"),
                    ("SUST", "Sustainment"),
                    ("DADE", "Department of the Army Directed Event"),
                    ("MTF", "Maintenance Test Flight"),
                    ("MOC", "Maintenance Operational Check"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=5,
                verbose_name="Maintenance Status (FMC, NMC)",
            ),
        ),
    ]
