# Generated by Django 4.2.2 on 2024-03-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0011_aircraft_in_phase_aircraft_phase_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecompliance',
            name='status',
            field=models.CharField(choices=[('UNCOMPLIANT', 'Uncompliant'), ('INIT_PASS', 'Initial Compliance - Pass'), ('INIT_FAIL', 'Initial Compliance - Fail'), ('FINAL', 'Final Compliance')], default='UNCOMPLIANT', max_length=16, verbose_name='The Compliance Status for this Message Compliance'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('SAFETY', 'Safety'), ('MAINTENANCE', 'Maintenance'), ('SOF', 'Safety of Flight'), ('ASAM', 'Aviation Safety'), ('AMAM', 'Aviation Maintenance Action Message'), ('GEN_AMAM', 'General Aviation Maintenance Action Message'), ('EASB', 'Emergency Alert Service Bulletin'), ('SIN', 'Safety Information Notice'), ('MIM', 'Maintenance Information Notice'), ('AWR', 'Air Worthiness Release'), ('OTHER', 'Other')], default='SAFETY', max_length=16, verbose_name='The type of message (safety, maintenance, etc.)'),
        ),
    ]
