# Generated by Django 4.2.2 on 2024-03-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0022_acdexport"),
        ("aircraft", "0012_messagecompliance_status_alter_message_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftTransferRequest",
            fields=[
                (
                    "requested_aircraft",
                    models.OneToOneField(
                        db_column="requested_aircraft_serial_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "originating_unit_approved",
                    models.BooleanField(
                        default=False,
                        verbose_name="Boolean indicating if the originating unit has approved the transfer",
                    ),
                ),
                (
                    "destination_unit_approved",
                    models.BooleanField(
                        default=False,
                        verbose_name="Boolean indicating if the destination unit has approved the transfer",
                    ),
                ),
                (
                    "permanent_transfer",
                    models.BooleanField(
                        default=False,
                        verbose_name="Boolean indicating if the transfer will remove instances of UnitAircraft on the originating unit hierarchy.",
                    ),
                ),
                ("date_requested", models.DateField(verbose_name="Date the Transfer Request was created")),
                (
                    "destination_unit",
                    models.ForeignKey(
                        db_column="destination_unit_uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_aircraft_transfer_requests",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "originating_unit",
                    models.ForeignKey(
                        db_column="originating_unit_uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_aircraft_transfer_requests",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "requested_by_user",
                    models.ForeignKey(
                        db_column="requsted_by_user_id", on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.user"
                    ),
                ),
            ],
            options={
                "db_table": "aircraft_transfer_requests",
            },
        ),
        migrations.CreateModel(
            name="AircraftTransferLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "permanent_transfer",
                    models.BooleanField(verbose_name="Boolean indicating if the transfer was permanent"),
                ),
                ("date_requested", models.DateField(verbose_name="Date the Transfer Request was created")),
                ("decision_date", models.DateField(verbose_name="Date the request was either approved or denied")),
                (
                    "transfer_approved",
                    models.BooleanField(
                        verbose_name="Boolean indicating if the aircraft transferr was approved or denied"
                    ),
                ),
                (
                    "destination_unit",
                    models.ForeignKey(
                        db_column="destination_unit_uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_aircraft_transfer_request_log",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "originating_unit",
                    models.ForeignKey(
                        db_column="originating_unit_uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_aircraft_transfer_request_log",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "requested_aircraft",
                    models.ForeignKey(
                        db_column="requested_aircraft_serial_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.aircraft",
                    ),
                ),
            ],
            options={
                "db_table": "aircraft_transfer_log",
            },
        ),
    ]
