# Generated by Django 4.2.2 on 2024-02-14 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0012_messagecompliance_status_alter_message_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Equipment",
        ),
        migrations.DeleteModel(
            name="UnitEquipment",
        ),
    ]
