# Generated by Django 4.2.2 on 2024-03-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0022_acdexport'),
        ('aircraft', '0013_remove_unitequipment_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('serial_number', models.CharField(max_length=32, verbose_name='Equipment Serial Number')),
                ('model', models.CharField(max_length=16, verbose_name='Equipment Model')),
                ('status', models.CharField(choices=[('FMC', 'Fully Mission Capable'), ('PMC', 'Partially Mission Capable'), ('PMCM', 'Partially Mission Capable - Maintenance'), ('PMCS', 'Partially Mission Capable - Sustainment'), ('NMC', 'Non Mission Capable'), ('NMCS', 'Non Mission Capable - Supply'), ('NMCM', 'Non Mission Capable - Maintenance'), ('MTF', 'Maintenance Test Flight'), ('UNK', 'Unknown')], default='UNK', max_length=5, verbose_name='Equipment Status')),
                ('value', models.FloatField(default=0, verbose_name='Current Value for Equip')),
                ('value_code', models.CharField(choices=[('HRS', 'Hours'), ('RNDS', 'Rounds'), ('CYCLES', 'Cycles'), ('STARTS', 'Starts'), ('OTH', 'Other'), ('UNK', 'Unknown')], default='HRS', max_length=8, verbose_name='Equipment Value Code')),
                ('remarks', models.TextField(blank=True, max_length=2048, null=True, verbose_name='User provided Remarks for a given piece of Equipment')),
                ('date_down', models.DateField(blank=True, null=True, verbose_name='Date Equipment entered an NMC status')),
                ('ecd', models.DateField(blank=True, null=True, verbose_name='Date Equipment is expected to enter an FMC status')),
                ('should_sync', models.BooleanField(default=True, verbose_name='An indicator if the equipment should be updated automatically')),
                ('last_sync_time', models.DateTimeField(verbose_name='Last Sync from ACN')),
                ('last_export_upload_time', models.DateTimeField(verbose_name='Last time this equipment was updated from an ACD Export Upload')),
                ('last_update_time', models.DateTimeField(verbose_name='Last edit to this equipment made in Griffin')),
                ('current_unit', models.ForeignKey(db_column='current_unit_uic', on_delete=django.db.models.deletion.PROTECT, related_name='currently_assigned_equipment', to='auto_dsr.unit')),
                ('installed_on_aircraft', models.ForeignKey(blank=True, db_column='installed_on_aircraft_serial_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircraft')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='UnitEquipment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('display_on_dsr', models.BooleanField(default=False, verbose_name="Logical if the equipment should be shown on the unit's DSR")),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, to='aircraft.equipment')),
                ('unit', models.ForeignKey(db_column='unit_uic', on_delete=django.db.models.deletion.CASCADE, to='auto_dsr.unit')),
            ],
            options={
                'verbose_name_plural': 'Unit Equipment',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='tracked_by_unit',
            field=models.ManyToManyField(through='aircraft.UnitEquipment', to='auto_dsr.unit'),
        ),
        migrations.AddConstraint(
            model_name='unitequipment',
            constraint=models.UniqueConstraint(fields=('equipment', 'unit'), name='equipment_in_unit'),
        ),
    ]
