# Generated by Django 4.2.2 on 2024-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0015_merge_20240320_1259"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="value",
            field=models.FloatField(default=0, verbose_name="Current Value for Equipment"),
        ),
    ]
