# Generated by Django 5.0.1 on 2024-06-09 17:14

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0016_alter_equipment_value"),
        ("auto_dsr", "0024_rename_user_id_usersetting_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="begin_time",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="length",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="serial",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="uic",
        ),
        migrations.AddField(
            model_name="flight",
            name="aircraft",
            field=models.ForeignKey(
                db_column="aircraft_serial",
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="aircraft.aircraft",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="The DateTime this flight ended"),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_DS_hours",
            field=models.FloatField(default=0, verbose_name="The number of daytime system hours flown for this flight"),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_D_hours",
            field=models.FloatField(default=0, verbose_name="The number of daytime hours flown for this flight"),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_H_hours",
            field=models.FloatField(default=0, verbose_name="The number of hooded hours flown for this flight"),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_NG_hours",
            field=models.FloatField(default=0, verbose_name="The number of night goggles hours flown for this flight"),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_NS_hours",
            field=models.FloatField(default=0, verbose_name="The number of night system hours flown for this flight"),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_N_hours",
            field=models.FloatField(default=0, verbose_name="The number of night time hours flown for this flight"),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_S_hours",
            field=models.FloatField(default=0, verbose_name="The number of system hours flown for this flight"),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_W_hours",
            field=models.FloatField(default=0, verbose_name="The number of weather hours flown for this flight"),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_codes",
            field=models.JSONField(default=list, verbose_name="list of flight codes as for this filght"),
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_id",
            field=models.CharField(default=0, max_length=64, verbose_name="The flight id of the flight"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="intermediate_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="The DateTime of an intermediate stop in the flight"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="mission_type",
            field=models.CharField(
                choices=[
                    ("TRAINING", "Training"),
                    ("SERVICE", "Service"),
                    ("COMBAT", "Combat"),
                    ("IMMINENT_DANGER", "Imminent Danger"),
                    ("RELAY", "Relay"),
                    ("COVID_OPERATION", "Coronavirus Operation"),
                    ("ACCEPTANCE_TEST_FLIGHT", "Acceptance Test Flight"),
                    ("EXPERIMENTAL_TEST_FLIGHT", "Experimental Test Flight"),
                    ("MAINTENANCE_TEST_FLIGHT", "Maintenance Test Flight"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=32,
                verbose_name="The mission type for this flight",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="The DateTime this flight began"),
        ),
        migrations.AddField(
            model_name="flight",
            name="status_date",
            field=models.DateTimeField(
                default=datetime.datetime(1776, 7, 4, 0, 0, tzinfo=datetime.timezone.utc),
                verbose_name="When the flight status was set",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="total_hours",
            field=models.IntegerField(default=0, verbose_name="The total number of hours for this flight"),
        ),
        migrations.AddField(
            model_name="flight",
            name="unit",
            field=models.ForeignKey(
                db_column="unit_uic", default=0, on_delete=django.db.models.deletion.PROTECT, to="auto_dsr.unit"
            ),
            preserve_default=False,
        ),
    ]
