# Generated by Django 5.0.1 on 2024-06-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0017_remove_flight_begin_time_remove_flight_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='end_datetime',
            new_name='stop_datetime',
        ),
    ]
