# Generated by Django 4.2.2 on 2024-07-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0019_flight_flight_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="da_1352",
            name="source",
            field=models.CharField(max_length=16, null=True, verbose_name="The source for this record"),
        ),
        migrations.AddField(
            model_name="da_1352",
            name="total_reportable_hours_in_month",
            field=models.FloatField(
                null=True, verbose_name="Totel number of reporting hours available. (Subracted DADE)"
            ),
        ),
    ]
