# Generated by Django 4.2.2 on 2024-07-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0020_da_1352_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="da_1352",
            name="source",
            field=models.CharField(max_length=16, verbose_name="The source for this record"),
        ),
        migrations.AlterField(
            model_name="da_1352",
            name="total_reportable_hours_in_month",
            field=models.FloatField(verbose_name="Totel number of reporting hours available. (Subracted DADE)"),
        ),
    ]
