# Generated by Django 4.2.2 on 2024-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0024_alter_raw_da_1352_options_da_1352_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="da_1352",
            name="last_updated",
            field=models.DateTimeField(null=True, verbose_name="The time the record was last updated"),
        ),
    ]
