# Generated by Django 4.2.2 on 2024-07-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0025_alter_da_1352_last_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="da_1352",
            old_name="aircraft",
            new_name="serial_number",
        ),
    ]
