# Generated by Django 4.2.2 on 2024-07-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0026_rename_aircraft_da_1352_serial_number"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="da_1352",
            name="aircraft_monthly_report",
        ),
        migrations.AddConstraint(
            model_name="da_1352",
            constraint=models.UniqueConstraint(
                fields=("serial_number", "reporting_uic", "reporting_month"), name="aircraft_monthly_report"
            ),
        ),
    ]
