# Generated by Django 5.0.1 on 2024-07-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0027_remove_da_1352_aircraft_monthly_report_and_more'),
        ('auto_dsr', '0031_merge_20240725_1331'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='da_1352',
            name='aircraft_monthly_report',
        ),
        migrations.AddConstraint(
            model_name='da_1352',
            constraint=models.UniqueConstraint(fields=('serial_number', 'reporting_month'), name='aircraft_monthly_report'),
        ),
    ]
