# Generated by Django 5.0.1 on 2024-07-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0028_remove_da_1352_aircraft_monthly_report_and_more'),
        ('auto_dsr', '0031_merge_20240725_1331'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='da_1352',
            index=models.Index(fields=['reporting_month'], name='aircraft_da_reporti_87635b_idx'),
        ),
    ]
