# Generated by Django 5.0.1 on 2024-07-31 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0029_da_1352_aircraft_da_reporti_87635b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('name', models.CharField(max_length=32, verbose_name='The model name (ie. BFT)')),
            ],
            options={
                'verbose_name': 'Equipment Model',
                'verbose_name_plural': 'Equipment Models',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Equipment Serial Number'),
        ),
        migrations.AddConstraint(
            model_name='equipmentmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='equipment_model_name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(db_column='equipment_model_id', on_delete=django.db.models.deletion.CASCADE, to='aircraft.equipmentmodel'),
        ),
    ]
