# Generated by Django 4.2.2 on 2024-09-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0032_alter_aircraft_field_sync_status_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inspectionreference",
            name="inspection_for_model_at_frequency",
        ),
        migrations.RemoveField(
            model_name="inspectionreference",
            name="calendar_frequency",
        ),
        migrations.RemoveField(
            model_name="inspectionreference",
            name="calendar_frequency_type",
        ),
        migrations.RemoveField(
            model_name="inspectionreference",
            name="dsr_display_name",
        ),
        migrations.RemoveField(
            model_name="inspectionreference",
            name="regulation_reference",
        ),
        migrations.RemoveField(
            model_name="inspectionreference",
            name="tracking_frequency_type",
        ),
        migrations.AddField(
            model_name="inspectionreference",
            name="extension_value",
            field=models.FloatField(blank=True, null=True, verbose_name="The numerical value of the extension amount"),
        ),
        migrations.AddField(
            model_name="inspectionreference",
            name="schedule_back",
            field=models.FloatField(
                blank=True, null=True, verbose_name="The numerical value of the late inspection period allowed"
            ),
        ),
        migrations.AddField(
            model_name="inspectionreference",
            name="schedule_front",
            field=models.FloatField(
                blank=True, null=True, verbose_name="The numerical value of the early inspection period allowed"
            ),
        ),
        migrations.AddField(
            model_name="inspectionreference",
            name="tracking_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aircraft Hours", "Aircraft Hours"),
                    ("Hoist Hours", "Hoist Hours"),
                    ("Engine Hours", "Engine Hours"),
                    ("APU Hours", "Auxiliary Power Unit Hours"),
                    ("Aircraft Cycles", "Aircraft Cycles"),
                    ("Hoist Cycles", "Hoist Cycles"),
                    ("APU Starts", "Auxiliary Power Unit Starts"),
                    ("Rounds", "Rounds"),
                    ("Landings", "Aircraft Landings"),
                    ("Flights", "Aircraft Flights"),
                    ("Days", "Calendar Days"),
                    ("Months", "Calendar Months"),
                    ("MonthsLastDay", "Last Day of Months"),
                    ("Years", "Calendar Years"),
                ],
                max_length=16,
                null=True,
                verbose_name="The category of frequency (days, hours, etc)",
            ),
        ),
        migrations.AddField(
            model_name="inspectionreference",
            name="writeup_back",
            field=models.FloatField(
                blank=True, null=True, verbose_name="The numerical value of the late writeup period allowed"
            ),
        ),
        migrations.AddField(
            model_name="inspectionreference",
            name="writeup_front",
            field=models.FloatField(
                blank=True, null=True, verbose_name="The numerical value of the early writeup period allowed"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionreference",
            constraint=models.UniqueConstraint(
                fields=("code", "model", "tracking_type"), name="inspection_for_model_at_frequency"
            ),
        ),
    ]
