# Generated by Django 4.2.2 on 2024-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0033_remove_inspectionreference_inspection_for_model_at_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionreference",
            name="is_phase",
            field=models.BooleanField(default=False, verbose_name="A flag to indentify phase inspections"),
        ),
    ]
