# Generated by Django 4.2.2 on 2024-09-12 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0034_inspectionreference_is_phase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airframe",
            fields=[
                (
                    "mds",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Full Mission Design Series for airframe",
                    ),
                ),
                (
                    "model",
                    models.CharField(max_length=16, verbose_name="Model designation without specific sub-variant"),
                ),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("BLACK HAWK", "BLACK HAWK"),
                            ("APACHE", "APACHE"),
                            ("CHINOOK", "CHINOOK"),
                            ("LAKOTA", "LAKOTA"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=16,
                        verbose_name="Model family that airframe fall under",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inspectionreference",
            name="airframe",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="aircraft.airframe"
            ),
        ),
    ]
