# Generated by Django 4.2.2 on 2024-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0035_airframe_inspectionreference_airframe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectionreference",
            name="is_phase",
            field=models.BooleanField(
                default=False, verbose_name="Whether the inspection is considered phase maintenance"
            ),
        ),
    ]
