# Generated by Django 4.2.2 on 2024-09-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0036_alter_inspectionreference_is_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionreference",
            name="common_name",
            field=models.CharField(default="", max_length=16, verbose_name="Name inspection is colloquially known by"),
            preserve_default=False,
        ),
    ]
