# Generated by Django 4.2.2 on 2024-10-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0037_inspectionreference_common_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="airframe",
            field=models.ForeignKey(
                blank=True,
                db_column="airframe_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aircraft.airframe",
            ),
        ),
        migrations.AddField(
            model_name="historicalaircraft",
            name="airframe",
            field=models.ForeignKey(
                blank=True,
                db_column="airframe_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="aircraft.airframe",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionreference",
            name="is_phase",
            field=models.BooleanField(default=False, verbose_name="A flag to indentify phase inspections"),
        ),
    ]
