# Generated by Django 4.2.2 on 2024-10-22 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0038_aircraft_airframe_historicalaircraft_airframe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="airframe",
            field=models.ForeignKey(
                blank=True,
                db_column="airframe_mds",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aircraft.airframe",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaircraft",
            name="airframe",
            field=models.ForeignKey(
                blank=True,
                db_column="airframe_mds",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="aircraft.airframe",
            ),
        ),
    ]
