# Generated by Django 4.2.2 on 2024-11-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0039_alter_aircraft_airframe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawShortLife",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "aircraft_serial",
                    models.CharField(max_length=16, verbose_name="Serial number of aircraft that comp. belongs to"),
                ),
                (
                    "aircraft_model",
                    models.CharField(max_length=16, verbose_name="Model of aircraft that component exists on"),
                ),
                ("work_unit_code", models.CharField(max_length=16, verbose_name="Work unit code related to component")),
                (
                    "nomenclature",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="The nomenclature of the part short life pertains to",
                    ),
                ),
                ("part_number", models.CharField(max_length=32, verbose_name="Part number short life pertains to")),
                (
                    "component_serial_number",
                    models.CharField(max_length=32, verbose_name="Serial number of component short life pertains to"),
                ),
                (
                    "tracker_display_name",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Type of interval on which short life is tracked",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Type of component"),
                ),
                ("current_value", models.FloatField(verbose_name="Current value of tracked interval for part")),
                (
                    "replacement_due_aircraft_hours",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Numerical value of when replacement is required"
                    ),
                ),
                (
                    "FH_remaining",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Flying hours between current hours and when replacement is due",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Short Life",
                "verbose_name_plural": "Raw Short Life Records",
                "db_table": "raw_short_life",
            },
        ),
        migrations.CreateModel(
            name="RawSurvivalPredictions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "aircraft_model",
                    models.CharField(max_length=16, verbose_name="Model of aircraft for which prediction applies"),
                ),
                ("work_unit_code", models.CharField(max_length=16, verbose_name="Work unit code related to component")),
                (
                    "serial_number",
                    models.CharField(max_length=32, verbose_name="Serial number of component prediction pertains to"),
                ),
                ("part_number", models.CharField(max_length=32, verbose_name="Part number prediction pertains to")),
                ("horizon_5", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_10", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_15", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_20", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_25", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_30", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_35", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_40", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_45", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_50", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_55", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_60", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_65", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_70", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_75", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_80", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_85", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_90", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_95", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_100", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
            ],
            options={
                "verbose_name": "Raw Survival Prediction",
                "verbose_name_plural": "Raw Survival Predictions",
                "db_table": "raw_surv_preds",
            },
        ),
        migrations.CreateModel(
            name="SurvivalPredictions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("work_unit_code", models.CharField(max_length=16, verbose_name="Work unit code related to component")),
                (
                    "comp_serial_number",
                    models.CharField(max_length=32, verbose_name="Serial number of component prediction pertains to"),
                ),
                ("part_number", models.CharField(max_length=32, verbose_name="Part number prediction pertains to")),
                (
                    "nomenclature",
                    models.CharField(max_length=32, verbose_name="The month the report is in reference to"),
                ),
                ("horizon_5", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_10", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_15", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_20", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_25", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_30", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_35", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_40", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_45", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_50", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_55", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_60", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_65", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_70", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_75", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_80", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_85", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_90", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_95", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("horizon_100", models.FloatField(verbose_name="Survival Prediction at 5 flight hours")),
                ("last_updated", models.DateTimeField(null=True, verbose_name="The time the record was last updated")),
                (
                    "aircraft",
                    models.ForeignKey(
                        db_column="serial_number",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="aircraft.aircraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survival Prediction",
                "verbose_name_plural": "Survival Predictions",
                "db_table": "surv_preds",
            },
        ),
        migrations.CreateModel(
            name="ShortLife",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("work_unit_code", models.CharField(max_length=16, verbose_name="Work unit code related to component")),
                (
                    "nomenclature",
                    models.CharField(max_length=32, verbose_name="The nomenclature of the part short life pertains to"),
                ),
                ("part_number", models.CharField(max_length=32, verbose_name="Part number short life pertains to")),
                (
                    "comp_serial_number",
                    models.CharField(max_length=32, verbose_name="Serial number of component short life pertains to"),
                ),
                (
                    "tracker_display_name",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Type of interval on which short life is tracked",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Type of component"),
                ),
                ("current_value", models.FloatField(verbose_name="Current value of tracked interval for part")),
                (
                    "replacement_due",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Numerical value of when replacement is required"
                    ),
                ),
                (
                    "flying_hours_remaining",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Flying hours between current hours and when replacement is due",
                    ),
                ),
                ("last_updated", models.DateTimeField(null=True, verbose_name="The time the record was last updated")),
                (
                    "aircraft",
                    models.ForeignKey(
                        db_column="serial_number",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="aircraft.aircraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Short Life",
                "verbose_name_plural": "Short Life Records",
                "db_table": "aircraft_short_life",
            },
        ),
    ]
