# Generated by Django 4.2.2 on 2024-11-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0040_rawshortlife_rawsurvivalpredictions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_10",
            field=models.FloatField(default=1, verbose_name="Standard Error at 10 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_100",
            field=models.FloatField(default=1, verbose_name="Standard Error at 100 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_15",
            field=models.FloatField(default=1, verbose_name="Standard Error at 15 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_20",
            field=models.FloatField(default=1, verbose_name="Standard Error at 20 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_25",
            field=models.FloatField(default=1, verbose_name="Standard Error at 25 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_30",
            field=models.FloatField(default=1, verbose_name="Standard Error at 30 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_35",
            field=models.FloatField(default=1, verbose_name="Standard Error at 35 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_40",
            field=models.FloatField(default=1, verbose_name="Standard Error at 40 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_45",
            field=models.FloatField(default=1, verbose_name="Standard Error at 45 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_5",
            field=models.FloatField(default=1, verbose_name="Standard Error at 5 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_50",
            field=models.FloatField(default=1, verbose_name="Standard Error at 50 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_55",
            field=models.FloatField(default=1, verbose_name="Standard Error at 55 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_60",
            field=models.FloatField(default=1, verbose_name="Standard Error at 60 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_65",
            field=models.FloatField(default=1, verbose_name="Standard Error at 65 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_70",
            field=models.FloatField(default=1, verbose_name="Standard Error at 70 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_75",
            field=models.FloatField(default=1, verbose_name="Standard Error at 75 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_80",
            field=models.FloatField(default=1, verbose_name="Standard Error at 80 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_85",
            field=models.FloatField(default=1, verbose_name="Standard Error at 85 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_90",
            field=models.FloatField(default=1, verbose_name="Standard Error at 90 flight hours"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survivalpredictions",
            name="std_err_95",
            field=models.FloatField(default=1, verbose_name="Standard Error at 95 flight hours"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_10",
            field=models.FloatField(verbose_name="Survival Prediction at 10 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_100",
            field=models.FloatField(verbose_name="Survival Prediction at 100 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_15",
            field=models.FloatField(verbose_name="Survival Prediction at 15 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_20",
            field=models.FloatField(verbose_name="Survival Prediction at 20 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_25",
            field=models.FloatField(verbose_name="Survival Prediction at 25 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_30",
            field=models.FloatField(verbose_name="Survival Prediction at 30 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_35",
            field=models.FloatField(verbose_name="Survival Prediction at 35 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_40",
            field=models.FloatField(verbose_name="Survival Prediction at 40 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_45",
            field=models.FloatField(verbose_name="Survival Prediction at 45 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_50",
            field=models.FloatField(verbose_name="Survival Prediction at 50 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_55",
            field=models.FloatField(verbose_name="Survival Prediction at 55 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_60",
            field=models.FloatField(verbose_name="Survival Prediction at 60 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_65",
            field=models.FloatField(verbose_name="Survival Prediction at 65 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_70",
            field=models.FloatField(verbose_name="Survival Prediction at 70 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_75",
            field=models.FloatField(verbose_name="Survival Prediction at 75 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_80",
            field=models.FloatField(verbose_name="Survival Prediction at 80 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_85",
            field=models.FloatField(verbose_name="Survival Prediction at 85 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_90",
            field=models.FloatField(verbose_name="Survival Prediction at 90 flight hours"),
        ),
        migrations.AlterField(
            model_name="rawsurvivalpredictions",
            name="horizon_95",
            field=models.FloatField(verbose_name="Survival Prediction at 95 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_10",
            field=models.FloatField(verbose_name="Survival Prediction at 10 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_100",
            field=models.FloatField(verbose_name="Survival Prediction at 100 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_15",
            field=models.FloatField(verbose_name="Survival Prediction at 15 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_20",
            field=models.FloatField(verbose_name="Survival Prediction at 20 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_25",
            field=models.FloatField(verbose_name="Survival Prediction at 25 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_30",
            field=models.FloatField(verbose_name="Survival Prediction at 30 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_35",
            field=models.FloatField(verbose_name="Survival Prediction at 35 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_40",
            field=models.FloatField(verbose_name="Survival Prediction at 40 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_45",
            field=models.FloatField(verbose_name="Survival Prediction at 45 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_50",
            field=models.FloatField(verbose_name="Survival Prediction at 50 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_55",
            field=models.FloatField(verbose_name="Survival Prediction at 55 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_60",
            field=models.FloatField(verbose_name="Survival Prediction at 60 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_65",
            field=models.FloatField(verbose_name="Survival Prediction at 65 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_70",
            field=models.FloatField(verbose_name="Survival Prediction at 70 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_75",
            field=models.FloatField(verbose_name="Survival Prediction at 75 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_80",
            field=models.FloatField(verbose_name="Survival Prediction at 80 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_85",
            field=models.FloatField(verbose_name="Survival Prediction at 85 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_90",
            field=models.FloatField(verbose_name="Survival Prediction at 90 flight hours"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="horizon_95",
            field=models.FloatField(verbose_name="Survival Prediction at 95 flight hours"),
        ),
    ]
