# Generated by Django 4.2.2 on 2024-11-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0041_survivalpredictions_std_err_10_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawshortlife",
            name="nomenclature",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="The nomenclature of the part short life pertains to",
            ),
        ),
        migrations.AlterField(
            model_name="shortlife",
            name="nomenclature",
            field=models.CharField(max_length=128, verbose_name="The nomenclature of the part short life pertains to"),
        ),
        migrations.AlterField(
            model_name="survivalpredictions",
            name="nomenclature",
            field=models.CharField(max_length=128, verbose_name="The month the report is in reference to"),
        ),
    ]
