# Generated by Django 4.2.2 on 2024-12-02 12:41

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0031_merge_20240725_1331"),
        ("aircraft", "0042_alter_rawshortlife_nomenclature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawFault",
            fields=[
                ("id", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("serial_Number", models.CharField(blank=True, max_length=64, null=True, verbose_name="Serial Number")),
                ("uic", models.CharField(blank=True, max_length=8, null=True, verbose_name="Unit")),
                ("fault_discovered_by", models.CharField(max_length=64, verbose_name="Fault Discovered By")),
                ("edipi", models.CharField(blank=True, max_length=16, null=True, verbose_name="EDIPI")),
                ("dod_email", models.CharField(blank=True, max_length=128, null=True, verbose_name="DoD Email")),
                ("status_code_value", models.CharField(max_length=2, verbose_name="Status Code Value")),
                (
                    "status_code_meaning",
                    models.CharField(blank=True, max_length=16, null=True, verbose_name="Status Code Meaning"),
                ),
                (
                    "system_code_value",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="System Code Value"),
                ),
                (
                    "system_code_meaning",
                    models.CharField(blank=True, max_length=32, null=True, verbose_name="System Code Meaning"),
                ),
                (
                    "when_discovered_code_value",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="When Discovered Code Value"),
                ),
                (
                    "when_discovered_code_meaning",
                    models.CharField(max_length=128, verbose_name="When Discovered Code Meaning"),
                ),
                (
                    "how_recognized_code_value",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="How Recognized Code Value"),
                ),
                (
                    "how_recognized_code_meaning",
                    models.CharField(blank=True, max_length=128, null=True, verbose_name="How Recognized Code Meaning"),
                ),
                (
                    "malfunction_effect_code_value",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Malfunction Effect Code Value"),
                ),
                (
                    "malfunction_effect_code_meaning",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Malfunction Effect Code Meaning"
                    ),
                ),
                (
                    "failure_code_value",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Failure Code Value"),
                ),
                (
                    "failure_code_meaning",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="Failure Code Meaning"),
                ),
                (
                    "corrective_action_code_value",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Corrective Action Code Value"),
                ),
                (
                    "corrective_action_code_meaning",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Corrective Action Code Meaning"
                    ),
                ),
                (
                    "ti_maintenance_level_code_value",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="TI Maintenance Code Value"),
                ),
                (
                    "ti_maintenance_level_code_meaning",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="TI Maintenance Code Meaning"),
                ),
                ("reason", models.IntegerField(verbose_name="Reason")),
                ("discovery_date_time", models.DateTimeField(verbose_name="Discovery Date/Time")),
                ("corrective_date_time", models.DateTimeField(verbose_name="Corrective Date/Time")),
                ("status", models.CharField(max_length=1, verbose_name="Status")),
                ("remarks", models.TextField(max_length=2048, verbose_name="Remarks")),
                (
                    "maintenance_delay",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="Maintenance Delay"),
                ),
                (
                    "fault_work_unit_code",
                    models.CharField(blank=True, max_length=24, null=True, verbose_name="Fault Work Unit Code"),
                ),
                ("source", models.CharField(blank=True, max_length=8, null=True, verbose_name="Source")),
            ],
        ),
        migrations.RemoveField(
            model_name="fault",
            name="open",
        ),
        migrations.RemoveField(
            model_name="fault",
            name="open_date",
        ),
        migrations.RemoveField(
            model_name="fault",
            name="serial",
        ),
        migrations.RemoveField(
            model_name="fault",
            name="severity",
        ),
        migrations.AddField(
            model_name="fault",
            name="aircraft",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, related_name="faults", to="aircraft.aircraft"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fault",
            name="corrective_action_code_meaning",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Corrective Action Code Meaning"),
        ),
        migrations.AddField(
            model_name="fault",
            name="corrective_action_code_value",
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name="Corrective Action Code Value"),
        ),
        migrations.AddField(
            model_name="fault",
            name="corrective_date_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Corrective Date/Time"),
        ),
        migrations.AddField(
            model_name="fault",
            name="discovery_date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 12, 41, 38, 274224, tzinfo=datetime.timezone.utc),
                verbose_name="Discovery Date/Time",
            ),
        ),
        migrations.AddField(
            model_name="fault",
            name="dod_email",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="DoD Email"),
        ),
        migrations.AddField(
            model_name="fault",
            name="edipi",
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="EDIPI"),
        ),
        migrations.AddField(
            model_name="fault",
            name="failure_code_meaning",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Failure Code Meaning"),
        ),
        migrations.AddField(
            model_name="fault",
            name="failure_code_value",
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name="Failure Code Value"),
        ),
        migrations.AddField(
            model_name="fault",
            name="fault_discovered_by",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Fault Discovered By"),
        ),
        migrations.AddField(
            model_name="fault",
            name="fault_work_unit_code",
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name="Fault Work Unit Code"),
        ),
        migrations.AddField(
            model_name="fault",
            name="how_recognized_code_meaning",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="How Recognized Code Meaning"),
        ),
        migrations.AddField(
            model_name="fault",
            name="how_recognized_code_value",
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name="How Recognized Code Value"),
        ),
        migrations.AddField(
            model_name="fault",
            name="maintenance_delay",
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Maintenance Delay"),
        ),
        migrations.AddField(
            model_name="fault",
            name="malfunction_effect_code_meaning",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Malfunction Effect Code Meaning"
            ),
        ),
        migrations.AddField(
            model_name="fault",
            name="malfunction_effect_code_value",
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name="Malfunction Effect Code Value"),
        ),
        migrations.AddField(
            model_name="fault",
            name="reason",
            field=models.IntegerField(default=100, verbose_name="Reason"),
        ),
        migrations.AddField(
            model_name="fault",
            name="source",
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name="Source"),
        ),
        migrations.AddField(
            model_name="fault",
            name="status",
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name="Status"),
        ),
        migrations.AddField(
            model_name="fault",
            name="status_code_meaning",
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="Status Code Meaning"),
        ),
        migrations.AddField(
            model_name="fault",
            name="status_code_value",
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name="Status Code Value"),
        ),
        migrations.AddField(
            model_name="fault",
            name="system_code_meaning",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="System Code Meaning"),
        ),
        migrations.AddField(
            model_name="fault",
            name="system_code_value",
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name="System Code Value"),
        ),
        migrations.AddField(
            model_name="fault",
            name="ti_maintenance_level_code_meaning",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="TI Maintenance Code Meaning"),
        ),
        migrations.AddField(
            model_name="fault",
            name="ti_maintenance_level_code_value",
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name="TI Maintenance Code Value"),
        ),
        migrations.AddField(
            model_name="fault",
            name="unit",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, related_name="faults", to="auto_dsr.unit"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fault",
            name="when_discovered_code_meaning",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="When Discovered Code Meaning"),
        ),
        migrations.AddField(
            model_name="fault",
            name="when_discovered_code_value",
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name="When Discovered Code Value"),
        ),
        migrations.AlterField(
            model_name="fault",
            name="remarks",
            field=models.TextField(max_length=2048, verbose_name="Remarks"),
        ),
    ]
