# Generated by Django 4.2.2 on 2024-12-13 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0043_rawfault_remove_fault_open_remove_fault_open_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraftinspection",
            name="last_completed_on",
            field=models.DateField(blank=True, null=True, verbose_name="The date the inspection last occurred on"),
        ),
        migrations.AlterField(
            model_name="fault",
            name="discovery_date_time",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Discovery Date/Time"),
        ),
        migrations.AlterField(
            model_name="fault",
            name="status_code_value",
            field=models.CharField(
                choices=[
                    ("NS", "No Status"),
                    ("CLR", "Cleared"),
                    ("TICL", "Technical Inspector Cleared"),
                    ("DI", "Diagonal"),
                    ("DA", "Dash"),
                    ("E", "Admin Deadline"),
                    ("X", "Deadline - Non Mission Capable"),
                    ("CX", "Circle X"),
                    ("NUKE", "Nuclear Containment"),
                    ("CHEM", "Chemical Containment"),
                    ("BIO", "Biological Containment"),
                ],
                default="NS",
                max_length=8,
                verbose_name="Status Code Value",
            ),
        ),
        migrations.AlterField(
            model_name="inspectionreference",
            name="is_phase",
            field=models.BooleanField(default=False, verbose_name="A flag to identify phase inspections"),
        ),
        migrations.AlterField(
            model_name="raw_da_1352",
            name="model_name",
            field=models.CharField(max_length=18, verbose_name="The aircraft model the report is in reference to."),
        ),
        migrations.AlterField(
            model_name="rawfault",
            name="status_code_value",
            field=models.CharField(max_length=8, verbose_name="Status Code Value"),
        ),
    ]
