# Generated by Django 4.2.2 on 2025-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0044_alter_aircraftinspection_last_completed_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="equipment_number",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="Aircraft Equipment Number"),
        ),
        migrations.AddField(
            model_name="historicalaircraft",
            name="equipment_number",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="Aircraft Equipment Number"),
        ),
    ]
