# Generated by Django 4.2.2 on 2025-02-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0033_userrequest_date_created_userrequest_date_updated_and_more"),
        ("notifications", "0002_alter_transferrequestnotification_transfer_request"),
        ("aircraft", "0045_aircraft_equipment_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircrafttransferrequest",
            name="destination_unit",
        ),
        migrations.RemoveField(
            model_name="aircrafttransferrequest",
            name="originating_unit",
        ),
        migrations.RemoveField(
            model_name="aircrafttransferrequest",
            name="requested_aircraft",
        ),
        migrations.RemoveField(
            model_name="aircrafttransferrequest",
            name="requested_by_user",
        ),
        migrations.AddField(
            model_name="aircraft",
            name="owning_unit",
            field=models.ForeignKey(
                blank=True,
                db_column="owning_unit_uic",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="currently_owned_aircraft",
                to="auto_dsr.unit",
            ),
        ),
        migrations.AddField(
            model_name="historicalaircraft",
            name="owning_unit",
            field=models.ForeignKey(
                blank=True,
                db_column="owning_unit_uic",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auto_dsr.unit",
            ),
        ),
        migrations.DeleteModel(
            name="AircraftTransferLog",
        ),
        migrations.DeleteModel(
            name="AircraftTransferRequest",
        ),
    ]
