# Generated by Django 4.2.2 on 2025-02-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0046_remove_aircrafttransferrequest_destination_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="The DateTime this flight began"
            ),
        ),
    ]
