# Generated by Django 4.2.2 on 2025-02-24 18:40

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0035_da2407export"),
        ("aircraft", "0047_alter_flight_start_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDA_2407",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="Auto Unique Id")),
                ("uic_work_order_number", models.CharField(max_length=16, verbose_name="UIC work order number")),
                ("work_order_number", models.CharField(max_length=16, verbose_name="Work order number")),
                ("shop", models.CharField(max_length=128, verbose_name="Name of shop responsible for MX")),
                (
                    "deficiency",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="User provided deficiency for a given work order",
                    ),
                ),
                (
                    "malfunction_desc",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="User provided malfunction description for a given work order",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="User provided remarks for a given work order",
                    ),
                ),
                ("submitted_datetime", models.DateTimeField(verbose_name="The DateTime this work order was submitted")),
                ("accepted_datetime", models.DateTimeField(verbose_name="The DateTime this work order was submitted")),
                (
                    "work_start_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="The Datetime work began on this work order"
                    ),
                ),
                (
                    "when_discovered",
                    models.CharField(max_length=128, verbose_name="Action being taken when malfunction was discovered"),
                ),
                (
                    "how_discovered",
                    models.CharField(max_length=128, verbose_name="How user identified the malfunction"),
                ),
                ("is_archived", models.BooleanField(default=False, verbose_name="Whether the work order is archived")),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True,
                        db_column="serial_number",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "customer_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="customer_unit_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "support_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="support_unit_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical d a_2407",
                "verbose_name_plural": "historical d a_2407s",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DA_2407",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("uic_work_order_number", models.CharField(max_length=16, verbose_name="UIC work order number")),
                ("work_order_number", models.CharField(max_length=16, verbose_name="Work order number")),
                ("shop", models.CharField(max_length=128, verbose_name="Name of shop responsible for MX")),
                (
                    "deficiency",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="User provided deficiency for a given work order",
                    ),
                ),
                (
                    "malfunction_desc",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="User provided malfunction description for a given work order",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="User provided remarks for a given work order",
                    ),
                ),
                ("submitted_datetime", models.DateTimeField(verbose_name="The DateTime this work order was submitted")),
                ("accepted_datetime", models.DateTimeField(verbose_name="The DateTime this work order was submitted")),
                (
                    "work_start_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="The Datetime work began on this work order"
                    ),
                ),
                (
                    "when_discovered",
                    models.CharField(max_length=128, verbose_name="Action being taken when malfunction was discovered"),
                ),
                (
                    "how_discovered",
                    models.CharField(max_length=128, verbose_name="How user identified the malfunction"),
                ),
                ("is_archived", models.BooleanField(default=False, verbose_name="Whether the work order is archived")),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True,
                        db_column="serial_number",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "customer_unit",
                    models.ForeignKey(
                        db_column="customer_unit_uic",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="da_2407_customer_units",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "support_unit",
                    models.ForeignKey(
                        db_column="support_unit_uic",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="da_2407_support_units",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
        ),
    ]
