# Generated by Django 4.2.2 on 2025-02-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0048_historicalda_2407_da_2407"),
    ]

    operations = [
        migrations.AddField(
            model_name="da_2407",
            name="workflow_state",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Current workflow state of the work order"
            ),
        ),
        migrations.AddField(
            model_name="historicalda_2407",
            name="workflow_state",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Current workflow state of the work order"
            ),
        ),
    ]
