# Generated by Django 4.2.2 on 2025-02-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0049_da_2407_workflow_state_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawfault",
            old_name="serial_Number",
            new_name="serial_number",
        ),
        migrations.AddField(
            model_name="fault",
            name="vantage_id",
            field=models.CharField(db_index=True, default="0000-0000-0000", max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="rawfault",
            name="corrective_date_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Corrective Date/Time"),
        ),
        migrations.AlterField(
            model_name="rawfault",
            name="discovery_date_time",
            field=models.DateTimeField(db_index=True, verbose_name="Discovery Date/Time"),
        ),
    ]
