# Generated by Django 4.2.2 on 2025-02-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0050_rename_serial_number_rawfault_serial_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawsurvivalpredictions",
            name="System",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="rawsurvivalpredictions",
            name="Training_Date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawsurvivalpredictions",
            name="aircraft_sn",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="rawsurvivalpredictions",
            name="est_risk",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawsurvivalpredictions",
            name="est_surv",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawsurvivalpredictions",
            name="last_known_command",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="rawsurvivalpredictions",
            name="last_known_uic",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="rawsurvivalpredictions",
            name="p_surv_tsli",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawsurvivalpredictions",
            name="tsli",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
