# Generated by Django 4.2.2 on 2025-03-11 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0051_rawsurvivalpredictions_system_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="airframe",
            field=models.ForeignKey(
                blank=True,
                db_column="airframe_mds",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aircraft",
                to="aircraft.airframe",
            ),
        ),
    ]
