# Generated by Django 4.2.2 on 2025-03-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0052_alter_aircraft_airframe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="remarks",
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name="Remarks"),
        ),
        migrations.AlterField(
            model_name="fault",
            name="vantage_id",
            field=models.CharField(db_index=True, default="0000-0000-0000", max_length=42, unique=True),
        ),
    ]
