# Generated by Django 4.2.2 on 2025-03-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0038_rawsynctimestamp"),
        ("aircraft", "0053_alter_fault_remarks_alter_fault_vantage_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAWPartLongevity",
            fields=[
                ("aircraft_serial", models.CharField(max_length=12, verbose_name="Aircraft Serial Number")),
                ("x_2410_id", models.IntegerField(primary_key=True, serialize=False, verbose_name="2410 ID")),
                ("work_unit_code", models.CharField(max_length=24, verbose_name="Work Unit Code")),
                ("part_number", models.CharField(max_length=32, verbose_name="Part Number")),
                ("serial_number", models.CharField(max_length=32, verbose_name="Part Serial Number")),
                ("sys_cat", models.CharField(max_length=8, verbose_name="System Category")),
                ("x_uic", models.CharField(max_length=8, verbose_name="UIC responsible fore maintenance")),
                ("x_aircraft_model", models.CharField(max_length=24, verbose_name="Aircraft Model")),
                (
                    "last_known_uic",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Last Known UIC"),
                ),
                ("maintenance_action_date", models.DateTimeField(verbose_name="Maintenance Date")),
                ("outcome_fh", models.FloatField()),
                ("outcome_causal", models.BooleanField(default=False)),
                ("consq", models.CharField(blank=True, max_length=24, null=True, verbose_name="Consequence")),
                (
                    "uic",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="UIC of owning aircraft unit"),
                ),
            ],
            options={
                "db_table": "raw_aircraft_part_longevity",
            },
        ),
        migrations.CreateModel(
            name="PartLongevity",
            fields=[
                ("x_2410_id", models.IntegerField(primary_key=True, serialize=False, verbose_name="2410 ID")),
                ("work_unit_code", models.CharField(max_length=24, verbose_name="Work Unit Code")),
                ("part_number", models.CharField(max_length=32, verbose_name="Part Number")),
                ("serial_number", models.CharField(max_length=32, verbose_name="Part Serial Number")),
                ("sys_cat", models.CharField(max_length=8, verbose_name="System Category")),
                ("maintenance_action_date", models.DateTimeField(verbose_name="Maintenance Date")),
                ("outcome_fh", models.FloatField()),
                ("outcome_causal", models.BooleanField(default=False)),
                ("consq", models.CharField(blank=True, max_length=24, null=True, verbose_name="Consequence")),
                ("aircraft", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="aircraft.aircraft")),
                (
                    "last_known_uic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="last_known_parts",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "responsible_uic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="responsible_for_parts",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="part_longevity",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "db_table": "aircraft_part_longevity",
            },
        ),
    ]
