# Generated by Django 4.2.2 on 2025-04-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0054_rawpartlongevity_partlongevity"),
    ]

    operations = [
        migrations.CreateModel(
            name="LCF_341_01_LifeLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(max_length=24, verbose_name="Model Name")),
                ("nomenclature", models.CharField(max_length=124, verbose_name="Nomenclature")),
                ("part_number", models.CharField(max_length=42, verbose_name="Part Number")),
                ("nsn", models.CharField(blank=True, max_length=16, null=True, verbose_name="NSN")),
                ("cage", models.CharField(max_length=8, verbose_name="Cage")),
                ("wuc", models.CharField(max_length=16, verbose_name="Work Unit Code")),
                ("tracking_type", models.CharField(blank=True, max_length=12, null=True, verbose_name="Tracking Type")),
                ("maot", models.FloatField(blank=True, null=True, verbose_name="MAOT")),
                ("tbo", models.FloatField(blank=True, null=True, verbose_name="TBO")),
                (
                    "component_type",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Component Type"),
                ),
            ],
            options={
                "db_table": "lcf_341_01_life_limit",
            },
        ),
        migrations.CreateModel(
            name="RAWLCF_341_01_LifeLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(max_length=24, verbose_name="Model Name")),
                ("nomenclature", models.CharField(max_length=124, verbose_name="Nomenclature")),
                ("part_number", models.CharField(max_length=42, verbose_name="Part Number")),
                ("nsn", models.CharField(blank=True, max_length=16, null=True, verbose_name="NSN")),
                ("cage", models.CharField(max_length=8, verbose_name="Cage")),
                ("wuc", models.CharField(max_length=16, verbose_name="Work Unit Code")),
                ("tracking_type", models.CharField(blank=True, max_length=12, null=True, verbose_name="Tracking Type")),
                ("maot", models.FloatField(blank=True, null=True, verbose_name="MAOT")),
                ("tbo", models.FloatField(blank=True, null=True, verbose_name="TBO")),
                (
                    "component_type",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Component Type"),
                ),
                ("remark", models.CharField(blank=True, max_length=4000, null=True, verbose_name="Remarks")),
                ("form16", models.CharField(blank=True, max_length=2, null=True, verbose_name="Form 16")),
                ("nha16", models.CharField(blank=True, max_length=2, null=True, verbose_name="NHA16")),
                ("tc_16", models.CharField(blank=True, max_length=2, null=True, verbose_name="tc16")),
                ("cc_16", models.CharField(blank=True, max_length=2, null=True, verbose_name="cc16")),
                ("form16_1", models.CharField(blank=True, max_length=2, null=True, verbose_name="tc16 1")),
                ("nha16_1", models.CharField(blank=True, max_length=2, null=True, verbose_name="NHA16 1")),
                ("form16_2", models.CharField(blank=True, max_length=2, null=True, verbose_name="tc16 2")),
                ("nha16_2", models.CharField(blank=True, max_length=2, null=True, verbose_name="NHA16 2")),
                ("da2408_16", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-16")),
                ("da2408_16_1", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-16 1")),
                ("da2408_16_2", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-16 2")),
                ("da2408_33", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-33")),
                ("da2410", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2410")),
                ("da2408_xx", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408 XX")),
                ("da2408_20", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-20 ")),
                ("da2408_4_1", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-4 1")),
                ("da2408_19", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-19")),
                ("da2408_19_1", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-19 1")),
                ("da2408_19_2", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-19 2")),
                ("da2408_19_3", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-19 3")),
                ("da2408_19_X", models.CharField(blank=True, max_length=2, null=True, verbose_name="DA2408-19 X")),
                (
                    "daactuateddevice",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Da Actuated Device"),
                ),
            ],
            options={
                "db_table": "raw_lcf_341_01_life_limit",
            },
        ),
    ]
