# Generated by Django 4.2.2 on 2025-05-12 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0038_rawsynctimestamp"),
        ("aircraft", "0055_lcf_341_01_lifelimit_rawlcf_341_01_lifelimit"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAWMaintenanceBase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="Aircraft Serial Number"),
                ),
                ("id_13_2", models.CharField(max_length=64, verbose_name="Vantage ID")),
                (
                    "discovery_date_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date/Time Discovered"),
                ),
                ("closed_date_time", models.DateTimeField(verbose_name="Date/Time Closed")),
                ("man_hours", models.FloatField(verbose_name="Number of man hours spent")),
                (
                    "personnel_dodid",
                    models.CharField(max_length=24, verbose_name="DODID of person performing maintenance"),
                ),
                (
                    "action_code_value",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Action Code"),
                ),
                ("closed_date", models.DateField(verbose_name="Date Close")),
                ("closed_rp", models.CharField(max_length=24, verbose_name="Closed RP")),
                ("model_name", models.CharField(blank=True, max_length=24, null=True, verbose_name="Model Name")),
                ("uic", models.CharField(blank=True, max_length=8, null=True, verbose_name="UIC")),
            ],
            options={
                "db_table": "raw_maintenance_base",
            },
        ),
        migrations.CreateModel(
            name="RAWMaintenanceTotals",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uic", models.CharField(max_length=8, verbose_name="UIC")),
                ("model_name", models.CharField(max_length=24, verbose_name="Model Name")),
                ("closed_rp", models.CharField(max_length=24, verbose_name="Closed RP")),
                ("total_hours", models.FloatField(verbose_name="Total Hours")),
            ],
            options={
                "db_table": "raw_maintenance_totals",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTotals",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(blank=True, max_length=24, null=True, verbose_name="Model Name")),
                ("closed_rp", models.CharField(max_length=24, verbose_name="Closed RP")),
                ("total_hours", models.FloatField(verbose_name="Total Hours")),
                ("uic", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit")),
            ],
            options={
                "db_table": "maintenance_totals",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceBase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_13_2", models.CharField(max_length=64, verbose_name="Vantage ID")),
                (
                    "discovery_date_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date/Time Discovered"),
                ),
                ("closed_date_time", models.DateTimeField(verbose_name="Date/Time Closed")),
                ("man_hours", models.FloatField(verbose_name="Number of man hours spent")),
                (
                    "personnel_dodid",
                    models.CharField(max_length=24, verbose_name="DODID of person performing maintenance"),
                ),
                (
                    "action_code_value",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Action Code"),
                ),
                ("closed_date", models.DateField(verbose_name="Date Close")),
                ("closed_rp", models.DateField(verbose_name="Closed RP")),
                ("model_name", models.CharField(blank=True, max_length=24, null=True, verbose_name="Model Name")),
                (
                    "serial_number",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="aircraft.aircraft"),
                ),
                ("uic", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit")),
            ],
            options={
                "db_table": "maintenance_base",
            },
        ),
    ]
