# Generated by Django 4.2.21 on 2025-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0055_lcf_341_01_lifelimit_rawlcf_341_01_lifelimit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lcf_341_01_lifelimit",
            name="model_name",
            field=models.CharField(db_index=True, max_length=24, verbose_name="Model Name"),
        ),
        migrations.AlterField(
            model_name="lcf_341_01_lifelimit",
            name="part_number",
            field=models.CharField(db_index=True, max_length=42, verbose_name="Part Number"),
        ),
        migrations.AlterField(
            model_name="partlongevity",
            name="part_number",
            field=models.CharField(db_index=True, max_length=32, verbose_name="Part Number"),
        ),
    ]
