# Generated by Django 4.2.21 on 2025-05-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0038_rawsynctimestamp"),
        ("aircraft", "0056_alter_lcf_341_01_lifelimit_model_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAWStock",
            fields=[
                ("uic", models.CharField(blank=True, max_length=8, null=True, verbose_name="UIC")),
                ("dodacc", models.CharField(blank=True, max_length=8, null=True, verbose_name="DOD ACC")),
                (
                    "gcss_internal_material_number",
                    models.CharField(max_length=24, verbose_name="Internal Material Number"),
                ),
                ("plant", models.CharField(max_length=8, verbose_name="Plant")),
                ("mrp_area_id", models.CharField(max_length=12, verbose_name="MRP Area ID")),
                ("storage_location", models.CharField(max_length=8, verbose_name="Storage Location")),
                ("batch", models.CharField(max_length=12, verbose_name="Batch")),
                ("unrestricted_stock", models.FloatField(verbose_name="Unrestricted Stock")),
                ("restricted_stock", models.FloatField(verbose_name="Restricted Stock")),
                ("stock_in_transfer", models.FloatField(verbose_name="Stock In Transfer")),
                ("stock_in_quality_inspection", models.FloatField(verbose_name="Stock In Quality Inspection")),
                ("blocked_stock", models.FloatField(verbose_name="Blocked Stock")),
                ("centaur_sync_timestamp", models.DateTimeField(verbose_name="Sync Timestamp")),
                ("total_stock", models.FloatField(verbose_name="Total Stock")),
                ("is_bench_stock", models.BooleanField(verbose_name="Is stock bench stock")),
                ("storage_bin", models.CharField(blank=True, max_length=12, null=True, verbose_name="Storage Bin")),
                ("is_serviceable_batch", models.BooleanField(verbose_name="Serviceable Batch")),
                (
                    "serviceable_batches",
                    models.CharField(blank=True, max_length=12, null=True, verbose_name="Serviceable Batches"),
                ),
                (
                    "non_serviceable_batches",
                    models.CharField(blank=True, max_length=12, null=True, verbose_name="Non Serviceable Batches"),
                ),
                ("serviceable_stock", models.FloatField(verbose_name="Serviceable Stock")),
                ("non_serviceable_stock", models.FloatField(verbose_name="Non Serviceable Stock")),
                (
                    "num_serviceable_zero_balance_batches",
                    models.FloatField(verbose_name="Number of Serviceable Zero Balance Batches"),
                ),
                (
                    "num_non_serviceable_zero_balance_batches",
                    models.FloatField(verbose_name="Number of Non Serviceable Zero Balance Batches"),
                ),
                ("sloc_class", models.CharField(blank=True, max_length=4, null=True, verbose_name="SLOC Class")),
                ("sloc_types", models.JSONField(verbose_name="SLOC Types")),
                ("sloc_fe_abbr", models.CharField(max_length=12, verbose_name="SLOC FE Abbr")),
                ("sloc_fe_name", models.CharField(max_length=64, verbose_name="SLOC FE Name")),
                ("ric", models.CharField(blank=True, max_length=4, null=True, verbose_name="RIC")),
                ("support_ric", models.CharField(blank=True, max_length=4, null=True, verbose_name="Support RIC")),
                ("sloc_description", models.CharField(max_length=24, verbose_name="SLOC Description")),
                (
                    "derived_dodaac",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Derived DOD ACC"),
                ),
                (
                    "sloc_description_uic",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="SLOC Description UIC"),
                ),
                ("mrp_type", models.CharField(blank=True, max_length=4, null=True, verbose_name="MRP Type")),
                ("reorder_point", models.FloatField(verbose_name="Reorder Point")),
                ("safety_stock", models.FloatField(verbose_name="Safety Stock")),
                ("has_storage_bin", models.BooleanField(verbose_name="Has Storage Bin")),
                ("is_shop_stock", models.BooleanField(verbose_name="Is Shop Stock")),
                ("is_authorized", models.BooleanField(verbose_name="Is Authorized")),
                ("authorized_stock", models.FloatField(verbose_name="Authorized Stock")),
                ("material_number", models.CharField(max_length=48, verbose_name="Material Number")),
                (
                    "material_number_type",
                    models.CharField(blank=True, max_length=24, null=True, verbose_name="Material Number Type"),
                ),
                (
                    "material_description",
                    models.CharField(blank=True, max_length=48, null=True, verbose_name="Material Description"),
                ),
                (
                    "line_item_number",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Line Item Number"),
                ),
                (
                    "material_number_with_fsc",
                    models.CharField(blank=True, max_length=48, null=True, verbose_name="Material Number with FSC"),
                ),
                (
                    "material_number_with_fsc_type",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Material Number with FSC Type"),
                ),
                ("recovery_code", models.CharField(blank=True, max_length=4, null=True, verbose_name="Recovery Code")),
                ("unit_price", models.FloatField(verbose_name="Unit Price")),
                ("unserviceable_credit_value", models.FloatField(verbose_name="Unserviceable Credit Value")),
                ("serviceable_credit_value", models.FloatField(verbose_name="Serviceable Credit Value")),
                (
                    "serviceable_exchange_credit_price",
                    models.FloatField(verbose_name="Serviceable Exchange Credit Price"),
                ),
                ("sc_name", models.CharField(blank=True, max_length=24, null=True, verbose_name="SC Name")),
                ("total_stock_valuation", models.FloatField(verbose_name="Total Stock Valuation")),
                (
                    "stock_id",
                    models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name="Stock ID"),
                ),
            ],
            options={
                "db_table": "raw_stock",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("dodacc", models.CharField(blank=True, max_length=8, null=True, verbose_name="DOD ACC")),
                (
                    "gcss_internal_material_number",
                    models.CharField(max_length=24, verbose_name="Internal Material Number"),
                ),
                ("plant", models.CharField(max_length=8, verbose_name="Plant")),
                ("mrp_area_id", models.CharField(max_length=12, verbose_name="MRP Area ID")),
                ("storage_location", models.CharField(max_length=8, verbose_name="Storage Location")),
                ("batch", models.CharField(max_length=12, verbose_name="Batch")),
                ("unrestricted_stock", models.FloatField(verbose_name="Unrestricted Stock")),
                ("restricted_stock", models.FloatField(verbose_name="Restricted Stock")),
                ("stock_in_transfer", models.FloatField(verbose_name="Stock In Transfer")),
                ("stock_in_quality_inspection", models.FloatField(verbose_name="Stock In Quality Inspection")),
                ("blocked_stock", models.FloatField(verbose_name="Blocked Stock")),
                ("centaur_sync_timestamp", models.DateTimeField(verbose_name="Sync Timestamp")),
                ("total_stock", models.FloatField(verbose_name="Total Stock")),
                ("is_bench_stock", models.BooleanField(verbose_name="Is stock bench stock")),
                ("storage_bin", models.CharField(blank=True, max_length=12, null=True, verbose_name="Storage Bin")),
                ("is_serviceable_batch", models.BooleanField(verbose_name="Serviceable Batch")),
                (
                    "serviceable_batches",
                    models.CharField(blank=True, max_length=12, null=True, verbose_name="Serviceable Batches"),
                ),
                (
                    "non_serviceable_batches",
                    models.CharField(blank=True, max_length=12, null=True, verbose_name="Non Serviceable Batches"),
                ),
                ("serviceable_stock", models.FloatField(verbose_name="Serviceable Stock")),
                ("non_serviceable_stock", models.FloatField(verbose_name="Non Serviceable Stock")),
                (
                    "num_serviceable_zero_balance_batches",
                    models.FloatField(verbose_name="Number of Serviceable Zero Balance Batches"),
                ),
                (
                    "num_non_serviceable_zero_balance_batches",
                    models.FloatField(verbose_name="Number of Non Serviceable Zero Balance Batches"),
                ),
                ("sloc_class", models.CharField(blank=True, max_length=4, null=True, verbose_name="SLOC Class")),
                ("sloc_types", models.JSONField(verbose_name="SLOC Types")),
                ("sloc_fe_abbr", models.CharField(max_length=12, verbose_name="SLOC FE Abbr")),
                ("sloc_fe_name", models.CharField(max_length=64, verbose_name="SLOC FE Name")),
                ("ric", models.CharField(blank=True, max_length=4, null=True, verbose_name="RIC")),
                ("support_ric", models.CharField(blank=True, max_length=4, null=True, verbose_name="Support RIC")),
                ("sloc_description", models.CharField(max_length=24, verbose_name="SLOC Description")),
                (
                    "derived_dodaac",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Derived DOD ACC"),
                ),
                ("mrp_type", models.CharField(blank=True, max_length=4, null=True, verbose_name="MRP Type")),
                ("reorder_point", models.FloatField(verbose_name="Reorder Point")),
                ("safety_stock", models.FloatField(verbose_name="Safety Stock")),
                ("has_storage_bin", models.BooleanField(verbose_name="Has Storage Bin")),
                ("is_shop_stock", models.BooleanField(verbose_name="Is Shop Stock")),
                ("is_authorized", models.BooleanField(verbose_name="Is Authorized")),
                ("authorized_stock", models.FloatField(verbose_name="Authorized Stock")),
                ("material_number", models.CharField(max_length=48, verbose_name="Material Number")),
                (
                    "material_number_type",
                    models.CharField(blank=True, max_length=24, null=True, verbose_name="Material Number Type"),
                ),
                (
                    "material_description",
                    models.CharField(blank=True, max_length=48, null=True, verbose_name="Material Description"),
                ),
                (
                    "line_item_number",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Line Item Number"),
                ),
                (
                    "material_number_with_fsc",
                    models.CharField(blank=True, max_length=48, null=True, verbose_name="Material Number with FSC"),
                ),
                (
                    "material_number_with_fsc_type",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Material Number with FSC Type"),
                ),
                ("recovery_code", models.CharField(blank=True, max_length=4, null=True, verbose_name="Recovery Code")),
                ("unit_price", models.FloatField(verbose_name="Unit Price")),
                ("unserviceable_credit_value", models.FloatField(verbose_name="Unserviceable Credit Value")),
                ("serviceable_credit_value", models.FloatField(verbose_name="Serviceable Credit Value")),
                (
                    "serviceable_exchange_credit_price",
                    models.FloatField(verbose_name="Serviceable Exchange Credit Price"),
                ),
                ("sc_name", models.CharField(blank=True, max_length=24, null=True, verbose_name="SC Name")),
                ("total_stock_valuation", models.FloatField(verbose_name="Total Stock Valuation")),
                (
                    "stock_id",
                    models.CharField(max_length=48, primary_key=True, serialize=False, verbose_name="Stock ID"),
                ),
                (
                    "sloc_description_uic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unit_sloc_stock",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unit_stock",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "db_table": "stock",
            },
        ),
    ]
