# Generated by Django 4.2.21 on 2025-05-22 13:39

from django.db import migrations, models
import django.db.models.deletion

from aircraft.model_utils.phase_types import PhaseTypes


def remove_ordering(apps, schema_editor):
    """
    Removing of the ordering is not required as this is a new table.
    """
    pass


def create_ordering(apps, schema_editor):
    """
    Create initial ordering based on Shiny app
    """
    PriorOrdering = apps.get_model("auto_dsr", "UnitPhaseOrder")
    AircraftTable = apps.get_model("aircraft", "Aircraft")
    NewOrdering = apps.get_model("aircraft", "UnitPhaseFlowOrdering")

    # Get all existing Phase Ordering Objects
    for ordering in PriorOrdering.objects.all():
        order = 0
        # Get all current unit aircraft.
        unit_air = AircraftTable.objects.filter(uic=ordering.uic).values_list("serial", flat=True)
        # Loop through all existing ordering
        for serial in ordering.phase_order:
            # If the unit currently owns the aircraft and the aircraft exists, create the new ordering object
            if serial in unit_air and AircraftTable.objects.filter(serial=serial).count() > 0:
                NewOrdering.objects.create(
                    serial=AircraftTable.objects.get(serial=serial),
                    uic=ordering.uic,
                    phase_order=order,
                    last_changed_by_user=ordering.last_changed_by_user,
                    last_updated=ordering.last_updated,
                )
                # Post increment order so the ordering starts at 0
                order += 1


def remove_next_phase(apps, schema_editor):
    """
    Removing of the next phase type is not required as this is a new field.
    """
    pass


def update_next_phase(apps, schema_editor):
    """
    Create initial next phase type for existing aircraft
    """
    AircraftTable = apps.get_model("aircraft", "Aircraft")

    # Get all existing Phase Ordering Objects
    for aircraft in AircraftTable.objects.all():
        if "-60" in aircraft.model:
            aircraft.next_phase_type = PhaseTypes.PMI1
        elif "-47" in aircraft.model:
            aircraft.next_phase_type = PhaseTypes.C2
        else:
            aircraft.next_phase_type = PhaseTypes.GENERIC
        aircraft.save()


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0038_rawsynctimestamp"),
        ("aircraft", "0056_alter_lcf_341_01_lifelimit_model_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="next_phase_type",
            field=models.CharField(
                choices=[
                    ("PMI1", "UH-60 PMI One"),
                    ("PMI2", "UH-60 PMI Two"),
                    ("C2", "640HR PHASE - C2"),
                    ("C5", "640HR PHASE - C4"),
                    ("FM1", "CH-47 PMI One"),
                    ("FM2", "CH-47 PMI Two"),
                    ("FM3", "CH-47 PMI Three"),
                    ("GEN", "Generic PMI"),
                ],
                default="GEN",
                max_length=4,
                verbose_name="Phase Inspection Type",
            ),
        ),
        migrations.AddField(
            model_name="historicalaircraft",
            name="next_phase_type",
            field=models.CharField(
                choices=[
                    ("PMI1", "UH-60 PMI One"),
                    ("PMI2", "UH-60 PMI Two"),
                    ("C2", "640HR PHASE - C2"),
                    ("C5", "640HR PHASE - C4"),
                    ("FM1", "CH-47 PMI One"),
                    ("FM2", "CH-47 PMI Two"),
                    ("FM3", "CH-47 PMI Three"),
                    ("GEN", "Generic PMI"),
                ],
                default="GEN",
                max_length=4,
                verbose_name="Phase Inspection Type",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="phase_type",
            field=models.CharField(
                choices=[
                    ("PMI1", "UH-60 PMI One"),
                    ("PMI2", "UH-60 PMI Two"),
                    ("C2", "640HR PHASE - C2"),
                    ("C5", "640HR PHASE - C4"),
                    ("FM1", "CH-47 PMI One"),
                    ("FM2", "CH-47 PMI Two"),
                    ("FM3", "CH-47 PMI Three"),
                    ("GEN", "Generic PMI"),
                ],
                default="GEN",
                max_length=4,
                verbose_name="Phase Inspection Type",
            ),
        ),
        migrations.CreateModel(
            name="UnitPhaseFlowOrdering",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phase_order", models.IntegerField()),
                ("last_updated", models.DateTimeField(verbose_name="Last User To Update Phase Schedule")),
                (
                    "last_changed_by_user",
                    models.ForeignKey(
                        db_column="user_id", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.user"
                    ),
                ),
                ("serial", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="aircraft.aircraft")),
                (
                    "uic",
                    models.ForeignKey(
                        db_column="uic", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit"
                    ),
                ),
            ],
            options={
                "db_table": "unit_phase_flow_order",
            },
        ),
        migrations.RunPython(create_ordering, remove_ordering),
        migrations.RunPython(update_next_phase, remove_next_phase),
    ]
