# Generated by Django 4.2.21 on 2025-05-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0056_rawmaintenancebase_rawmaintenancetotals_and_more"),
        ("aircraft", "0057_aircraft_next_phase_type_and_more"),
        ("aircraft", "0057_rawstock_stock"),
    ]

    operations = []
