# Generated by Django 4.2.21 on 2025-08-25 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0058_merge_20250523_1408"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "mod_type",
            },
        ),
        migrations.CreateModel(
            name="AircraftMod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "mod_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="aircraft_mods", to="aircraft.modtype"
                    ),
                ),
            ],
            options={
                "db_table": "aicraft_mods",
            },
        ),
    ]
