# Generated by Django 4.2.4 on 2024-11-21 12:56

import django.db.models.deletion
from django.db import migrations, models

import utils.logo_upload_to


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "uic",
                    models.CharField(
                        max_length=9, primary_key=True, serialize=False, verbose_name="Unit Identification Code"
                    ),
                ),
                ("short_name", models.CharField(max_length=64, verbose_name="Unit Short Name")),
                ("display_name", models.CharField(max_length=128, verbose_name="Unit Display Name")),
                ("nick_name", models.CharField(blank=True, max_length=64, null=True, verbose_name="Unit Nick Name")),
                (
                    "echelon",
                    models.CharField(
                        choices=[
                            ("TM", "Team"),
                            ("SQD", "Squad"),
                            ("SEC", "Section"),
                            ("PLT", "Platoon"),
                            ("DET", "Detachment"),
                            ("CO", "Company"),
                            ("ACT", "Activity"),
                            ("AUG", "Augmentation"),
                            ("BN", "Battalion"),
                            ("BDE", "Brigade"),
                            ("DIV", "Division"),
                            ("CORPS", "Corps"),
                            ("MACOM", "Major Command"),
                            ("CNTR", "Center"),
                            ("ARMY", "Army"),
                            ("ELEMT", "Element"),
                            ("FMS", "Field Maintenance Shop"),
                            ("GROUP", "Group"),
                            ("SCH", "Army School"),
                            ("DRU", "Direct Reporting Unit"),
                            ("ASCC", "Army Service Component Command"),
                            ("ACOM", "Army Command"),
                            ("HQ", "Headquarters"),
                            ("DIR", "Directorate"),
                            ("INST", "Institute"),
                            ("OFC", "Office"),
                            ("TF", "Task Force"),
                            ("AGENCY", "Agency"),
                            ("MILSVC", "Military Service"),
                            ("STATE", "State Army National Guard"),
                            ("FACILITY", "Aviation Support Facility"),
                            ("MSC", "Major Subordinate Command"),
                            ("UC", "Unified Command"),
                            ("CONTAINER", "Container for Organizing Units"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=16,
                        verbose_name="Unit Echelon",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.logo_upload_to.unit_logo_upload_to,
                        verbose_name="Unit logo",
                    ),
                ),
                (
                    "compo",
                    models.CharField(
                        choices=[
                            ("1", "Active"),
                            ("2", "Guard"),
                            ("3", "Reserve"),
                            ("TF", "Task Force"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=16,
                        verbose_name="Unit Component Classification",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="United States State abbreviation."
                    ),
                ),
                ("start_date", models.DateField(default="1775-07-14", verbose_name="Unit origination Date")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="Unit end Date")),
                ("level", models.IntegerField(verbose_name="This unit's depth in the tree/hierarchy")),
                (
                    "parent_uics",
                    models.JSONField(default=list, verbose_name="List of all uics over this one in the hierarchy."),
                ),
                (
                    "child_uics",
                    models.JSONField(default=list, verbose_name="List of all immediate child uics to this unit."),
                ),
                (
                    "subordinate_uics",
                    models.JSONField(default=list, verbose_name="List of all uics subordinate to this one."),
                ),
                ("as_of_logical_time", models.IntegerField(verbose_name="Logical time of last update")),
                (
                    "parent_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_unit_uic",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="units.unit",
                    ),
                ),
            ],
        ),
    ]
