# Generated by Django 4.2.21 on 2025-10-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0042_merge_20251002_1106"),
        ("units", "0002_favoriteunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoriteunit",
            name="unit",
            field=models.ForeignKey(
                db_column="uic",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="favorite_unit",
                to="auto_dsr.unit",
            ),
        ),
    ]
