# Generated by Django 4.2.2 on 2024-05-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhp', '0008_rename_rawforscomannual_rawannualprojection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawannualprojection',
            name='source',
            field=models.CharField(default='FORSCOM', max_length=16, verbose_name='The source providing these projections'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawcostfactor',
            name='source',
            field=models.CharField(default='FORSCOM', max_length=16, verbose_name='The source providing these projections'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmonthlyforecast',
            name='source',
            field=models.CharField(default='FORSCOM', max_length=16, verbose_name='The source providing these projections'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawannualprojection',
            name='unit_type',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Unit Type'),
        ),
    ]
