# Generated by Django 4.2.2 on 2024-05-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhp', '0010_alter_rawcostfactor_cost_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyprojection',
            name='source',
            field=models.CharField(default='FORSCOM', max_length=16, verbose_name='The source providing these projections'),
            preserve_default=False,
        ),
    ]
