# Generated by Django 4.2.2 on 2024-09-12 19:33

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aircraft", "0035_airframe_inspectionreference_airframe"),
        ("auto_dsr", "0031_merge_20240725_1331"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_start", models.DateTimeField(verbose_name="Day/time of Event Start")),
                ("event_end", models.DateTimeField(blank=True, null=True, verbose_name="Day/time of Event End")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="User established notes about Event"
                    ),
                ),
                (
                    "alt_poc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="alt_poc_events",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "poc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="poc_events",
                        to="auto_dsr.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonsaEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name of DONSA")),
            ],
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="MaintenanceEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
            ],
            bases=("events.event",),
        ),
        migrations.CreateModel(
            name="MaintenanceLane",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("name", models.CharField(max_length=64, verbose_name="MTN Lane Name")),
                (
                    "contractor",
                    models.BooleanField(
                        default=False, verbose_name="Whether the maintenance is conducted by contractors"
                    ),
                ),
                (
                    "internal",
                    models.BooleanField(
                        default=True, verbose_name="Whether the maintenance is conducted by unit organic team"
                    ),
                ),
                ("airframes", models.ManyToManyField(related_name="maintenance_lanes", to="aircraft.airframe")),
                (
                    "location",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="auto_dsr.location"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.unit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalTrainingEvent",
            fields=[
                (
                    "event_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="events.event",
                    ),
                ),
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("event_start", models.DateTimeField(verbose_name="Day/time of Event Start")),
                ("event_end", models.DateTimeField(blank=True, null=True, verbose_name="Day/time of Event End")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="User established notes about Event"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name of training event")),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "alt_poc",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "poc",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="unit_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical training event",
                "verbose_name_plural": "historical training events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMaintenanceEvent",
            fields=[
                (
                    "event_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="events.event",
                    ),
                ),
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("event_start", models.DateTimeField(verbose_name="Day/time of Event Start")),
                ("event_end", models.DateTimeField(blank=True, null=True, verbose_name="Day/time of Event End")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="User established notes about Event"
                    ),
                ),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True,
                        db_column="aircraft_serial",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "alt_poc",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="aircraft.inspection",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        blank=True,
                        db_column="maintenance_lane",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="events.maintenancelane",
                    ),
                ),
                (
                    "poc",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical maintenance event",
                "verbose_name_plural": "historical maintenance events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDonsaEvent",
            fields=[
                (
                    "event_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="events.event",
                    ),
                ),
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("event_start", models.DateTimeField(verbose_name="Day/time of Event Start")),
                ("event_end", models.DateTimeField(blank=True, null=True, verbose_name="Day/time of Event End")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="User established notes about Event"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name of DONSA")),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "alt_poc",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "poc",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="unit_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical donsa event",
                "verbose_name_plural": "historical donsa events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TrainingEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.event",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name of training event")),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.unit"
                    ),
                ),
            ],
            bases=("events.event",),
        ),
        migrations.AddConstraint(
            model_name="maintenancelane",
            constraint=models.UniqueConstraint(fields=("unit", "name"), name="unique_lane_per_unit"),
        ),
        migrations.AddField(
            model_name="maintenanceevent",
            name="aircraft",
            field=models.ForeignKey(
                db_column="aircraft_serial", on_delete=django.db.models.deletion.CASCADE, to="aircraft.aircraft"
            ),
        ),
        migrations.AddField(
            model_name="maintenanceevent",
            name="inspection",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="aircraft.inspection"
            ),
        ),
        migrations.AddField(
            model_name="maintenanceevent",
            name="lane",
            field=models.ForeignKey(
                db_column="maintenance_lane", on_delete=django.db.models.deletion.CASCADE, to="events.maintenancelane"
            ),
        ),
        migrations.AddField(
            model_name="donsaevent",
            name="unit",
            field=models.ForeignKey(
                db_column="unit_uic", on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.unit"
            ),
        ),
    ]
