# Generated by Django 4.2.2 on 2024-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmaintenanceevent",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("25", "25 Hr"),
                    ("40", "40 Hr"),
                    ("50", "50 Hr"),
                    ("100", "100 Hr"),
                    ("120", "120 Hr"),
                    ("125", "125 Hr"),
                    ("160", "160 Hr"),
                    ("250", "250 Hr"),
                    ("320", "320 Hr"),
                    ("400", "400 Hr"),
                    ("480", "480 Hr"),
                    ("500", "500 Hr"),
                    ("640", "640 Hr"),
                    ("960", "960 Hr"),
                    ("1920", "1920 Hr"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=12,
                verbose_name="Maintenance Type",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceevent",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("25", "25 Hr"),
                    ("40", "40 Hr"),
                    ("50", "50 Hr"),
                    ("100", "100 Hr"),
                    ("120", "120 Hr"),
                    ("125", "125 Hr"),
                    ("160", "160 Hr"),
                    ("250", "250 Hr"),
                    ("320", "320 Hr"),
                    ("400", "400 Hr"),
                    ("480", "480 Hr"),
                    ("500", "500 Hr"),
                    ("640", "640 Hr"),
                    ("960", "960 Hr"),
                    ("1920", "1920 Hr"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=12,
                verbose_name="Maintenance Type",
            ),
        ),
    ]
