# Generated by Django 4.2.2 on 2024-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_historicalmaintenanceevent_maintenance_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmaintenanceevent",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("25HR INSP", "25 Hr"),
                    ("40HR INSP", "40 Hr"),
                    ("50HR INSP", "50 Hr"),
                    ("100HR INSP", "100 Hr"),
                    ("120HR INSP", "120 Hr"),
                    ("125HR INSP", "125 Hr"),
                    ("160HR INSP", "160 Hr"),
                    ("250HR INSP", "250 Hr"),
                    ("320HR INSP", "320 Hr"),
                    ("400HR INSP", "400 Hr"),
                    ("480HR PHASE", "480 Hr"),
                    ("500HR PHASE", "500 Hr"),
                    ("640HR PHASE", "640 Hr"),
                    ("800HR PHASE", "800 Hr"),
                    ("960HR PHASE", "960 Hr"),
                    ("1920HR PHASE", "1920 Hr"),
                    ("48MO PHASE", "48 Mo"),
                    ("DADE", "DADE"),
                    ("GEN PHASE", "Gen Phase"),
                    ("RESET", "Reset"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=12,
                verbose_name="Maintenance Type",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceevent",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("25HR INSP", "25 Hr"),
                    ("40HR INSP", "40 Hr"),
                    ("50HR INSP", "50 Hr"),
                    ("100HR INSP", "100 Hr"),
                    ("120HR INSP", "120 Hr"),
                    ("125HR INSP", "125 Hr"),
                    ("160HR INSP", "160 Hr"),
                    ("250HR INSP", "250 Hr"),
                    ("320HR INSP", "320 Hr"),
                    ("400HR INSP", "400 Hr"),
                    ("480HR PHASE", "480 Hr"),
                    ("500HR PHASE", "500 Hr"),
                    ("640HR PHASE", "640 Hr"),
                    ("800HR PHASE", "800 Hr"),
                    ("960HR PHASE", "960 Hr"),
                    ("1920HR PHASE", "1920 Hr"),
                    ("48MO PHASE", "48 Mo"),
                    ("DADE", "DADE"),
                    ("GEN PHASE", "Gen Phase"),
                    ("RESET", "Reset"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=12,
                verbose_name="Maintenance Type",
            ),
        ),
    ]
