# Generated by Django 4.2.2 on 2024-09-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0037_inspectionreference_common_name"),
        ("events", "0004_alter_historicalmaintenanceevent_maintenance_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmaintenanceevent",
            name="inspection_reference",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="aircraft.inspectionreference",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceevent",
            name="inspection_reference",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="aircraft.inspectionreference"
            ),
        ),
    ]
