# Generated by Django 4.2.2 on 2024-10-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_historicalmaintenanceevent_inspection_reference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSeries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "DAILY"),
                            ("WEEKLY", "WEEKLY"),
                            ("MONTHLY", "MONTHLY"),
                            ("WEEKDAYS", "WEEKDAYS"),
                        ],
                        default="WEEKLY",
                        max_length=12,
                        verbose_name="Frequency of recurrence",
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1, verbose_name="Interval between recurrences")),
                (
                    "days_of_week",
                    models.JSONField(blank=True, null=True, verbose_name="Which days upon which the events occur"),
                ),
                ("end_date", models.DateTimeField(blank=True, null=True, verbose_name="End date for the recurrence")),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="series",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="events.eventseries"
            ),
        ),
        migrations.AddField(
            model_name="historicaldonsaevent",
            name="series",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="events.eventseries",
            ),
        ),
        migrations.AddField(
            model_name="historicalmaintenanceevent",
            name="series",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="events.eventseries",
            ),
        ),
        migrations.AddField(
            model_name="historicaltrainingevent",
            name="series",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="events.eventseries",
            ),
        ),
    ]
