# Generated by Django 4.2.2 on 2024-10-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_eventseries_event_series_historicaldonsaevent_series_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmaintenanceevent",
            name="maintenance_type",
            field=models.CharField(
                choices=[("INSP", "Inspection"), ("OTHER", "Other")],
                default="OTHER",
                max_length=12,
                verbose_name="Maintenance Type",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceevent",
            name="maintenance_type",
            field=models.CharField(
                choices=[("INSP", "Inspection"), ("OTHER", "Other")],
                default="OTHER",
                max_length=12,
                verbose_name="Maintenance Type",
            ),
        ),
    ]
