# Generated by Django 4.2.2 on 2024-10-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0031_merge_20240725_1331"),
        ("events", "0007_alter_historicalmaintenanceevent_maintenance_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="alt_poc",
            field=models.ForeignKey(
                blank=True,
                db_column="alt_poc_edipi",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="alt_poc_events",
                to="auto_dsr.user",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="poc",
            field=models.ForeignKey(
                blank=True,
                db_column="poc_edipi",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="poc_events",
                to="auto_dsr.user",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldonsaevent",
            name="alt_poc",
            field=models.ForeignKey(
                blank=True,
                db_column="alt_poc_edipi",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auto_dsr.user",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldonsaevent",
            name="poc",
            field=models.ForeignKey(
                blank=True,
                db_column="poc_edipi",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auto_dsr.user",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmaintenanceevent",
            name="alt_poc",
            field=models.ForeignKey(
                blank=True,
                db_column="alt_poc_edipi",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auto_dsr.user",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmaintenanceevent",
            name="poc",
            field=models.ForeignKey(
                blank=True,
                db_column="poc_edipi",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auto_dsr.user",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrainingevent",
            name="alt_poc",
            field=models.ForeignKey(
                blank=True,
                db_column="alt_poc_edipi",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auto_dsr.user",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrainingevent",
            name="poc",
            field=models.ForeignKey(
                blank=True,
                db_column="poc_edipi",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auto_dsr.user",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelane",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Maintenance Lane Name"),
        ),
    ]
