# Generated by Django 4.2.2 on 2025-01-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0031_merge_20240725_1331"),
        ("events", "0008_alter_event_alt_poc_alter_event_poc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donsaevent",
            name="applies_to",
            field=models.ManyToManyField(related_name="donsa_event", to="auto_dsr.unit"),
        ),
        migrations.AddField(
            model_name="historicalmaintenanceevent",
            name="name",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, verbose_name="Name of Maintenance Event"
            ),
        ),
        migrations.AddField(
            model_name="historicaltrainingevent",
            name="training_type",
            field=models.CharField(
                choices=[("EXERCISE", "Exercise"), ("OPERATION", "Operation"), ("OTHER", "Other")],
                default="OTHER",
                max_length=16,
                verbose_name="Type Of Training",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceevent",
            name="name",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, verbose_name="Name of Maintenance Event"
            ),
        ),
        migrations.AddField(
            model_name="trainingevent",
            name="applies_to",
            field=models.ManyToManyField(related_name="training_event", to="auto_dsr.unit"),
        ),
        migrations.AddField(
            model_name="trainingevent",
            name="training_type",
            field=models.CharField(
                choices=[("EXERCISE", "Exercise"), ("OPERATION", "Operation"), ("OTHER", "Other")],
                default="OTHER",
                max_length=16,
                verbose_name="Type Of Training",
            ),
        ),
    ]
