# Generated by Django 4.2.2 on 2025-01-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0045_aircraft_equipment_number_and_more"),
        ("auto_dsr", "0031_merge_20240725_1331"),
        ("events", "0009_donsaevent_applies_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltrainingevent",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auto_dsr.location",
            ),
        ),
        migrations.AddField(
            model_name="trainingevent",
            name="aircraft",
            field=models.ManyToManyField(blank=True, null=True, related_name="training_event", to="aircraft.aircraft"),
        ),
        migrations.AddField(
            model_name="trainingevent",
            name="location",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.location"
            ),
        ),
    ]
