# Generated by Django 4.2.2 on 2025-01-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0045_aircraft_equipment_number_and_more"),
        ("auto_dsr", "0031_merge_20240725_1331"),
        ("events", "0010_historicaltrainingevent_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingevent",
            name="aircraft",
            field=models.ManyToManyField(blank=True, related_name="training_event", to="aircraft.aircraft"),
        ),
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "requested_maintenance_type",
                    models.CharField(
                        choices=[("INSP", "Inspection"), ("OTHER", "Other")],
                        default="OTHER",
                        max_length=12,
                        verbose_name="Maintenance Type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=64,
                        null=True,
                        verbose_name="Name of requested Maintenance Event",
                    ),
                ),
                (
                    "requested_start",
                    models.DateTimeField(verbose_name="Requested Day/time of the start of the maintenance"),
                ),
                (
                    "requested_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Requested Day/time of the end of the maintenance"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="User established notes about the request"
                    ),
                ),
                ("date_requested", models.DateField(verbose_name="Date the Maintenance Request was created")),
                ("decision_date", models.DateField(verbose_name="Date the request was either approved or denied")),
                (
                    "maintenance_approved",
                    models.BooleanField(verbose_name="Boolean indicating if the request was approved or denied"),
                ),
                (
                    "alt_poc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="maintenance_requests_alt_poc",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "poc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="maintenance_requests_poc",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "requested_aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "requested_by_uic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "requested_by_user",
                    models.ForeignKey(
                        db_column="requested_by_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="auto_dsr.user",
                    ),
                ),
                (
                    "requested_inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="aircraft.inspection",
                    ),
                ),
                (
                    "requested_inspection_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="maintenance_requests",
                        to="aircraft.inspectionreference",
                    ),
                ),
                (
                    "requested_maintenance_lane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="events.maintenancelane",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_requests",
            },
        ),
    ]
