# Generated by Django 4.2.2 on 2025-03-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("personnel", "0001_initial"),
        ("personnel", "0002_graderank_rawreadinesslevel_rawreadinessskill_and_more"),
        ("personnel", "0003_alter_rawreadinessskill_positions_posco_and_more"),
        ("personnel", "0004_alter_mtoe_authorized_strength_and_more"),
        ("personnel", "0005_soldier_rawreadinessskill_first_name_and_more"),
    ]

    initial = True

    dependencies = [
        ("aircraft", "0051_rawsurvivalpredictions_system_and_more"),
        ("auto_dsr", "0033_userrequest_date_created_userrequest_date_updated_and_more"),
        ("auto_dsr", "0038_rawsynctimestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAWMTOE",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unit_identification_code", models.CharField(max_length=8, verbose_name="Unit")),
                ("document_number", models.CharField(max_length=16, verbose_name="Unit")),
                ("fiscal_year", models.IntegerField(verbose_name="Fiscal Year")),
                ("change_number", models.IntegerField(verbose_name="Change Number")),
                ("major_army_command_codes", models.CharField(max_length=4, verbose_name="Major Army Command Codes")),
                (
                    "paragraph_no_1",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Paragraph Number 1"),
                ),
                (
                    "paragraph_no_3",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Paragraph Number 3"),
                ),
                (
                    "required_strength",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Required Strength"),
                ),
                (
                    "authorized_strength",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Authorized Strength"),
                ),
                ("identity_code", models.CharField(blank=True, max_length=2, null=True, verbose_name="Identity Code")),
                ("position_code", models.CharField(blank=True, max_length=8, null=True, verbose_name="Position Code")),
                (
                    "army_mgmt_structure_code",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Army Management Structure Code"
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=4, null=True, verbose_name="Grade")),
                ("branch", models.CharField(blank=True, max_length=4, null=True, verbose_name="Branch")),
                ("asi01", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 1")),
                ("asi02", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 2")),
                ("asi03", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 3")),
                ("asi04", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 4")),
                ("line_number", models.CharField(blank=True, max_length=6, null=True, verbose_name="Line Number")),
                (
                    "special_qualification_id",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Special Qualification Identifier"
                    ),
                ),
            ],
            options={
                "db_table": "raw_mtoe",
            },
        ),
        migrations.CreateModel(
            name="MTOE",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("document_number", models.CharField(max_length=16, verbose_name="Unit")),
                ("fiscal_year", models.IntegerField(verbose_name="Fiscal Year")),
                ("change_number", models.IntegerField(verbose_name="Change Number")),
                ("major_army_command_codes", models.CharField(max_length=4, verbose_name="Major Army Command Codes")),
                (
                    "paragraph_no_1",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Paragraph Number 1"),
                ),
                (
                    "paragraph_no_3",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Paragraph Number 3"),
                ),
                (
                    "required_strength",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Required Strength"),
                ),
                (
                    "authorized_strength",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Authorized Strength"),
                ),
                ("identity_code", models.CharField(blank=True, max_length=2, null=True, verbose_name="Identity Code")),
                ("position_code", models.CharField(blank=True, max_length=8, null=True, verbose_name="Position Code")),
                (
                    "army_mgmt_structure_code",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Army Management Structure Code"
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=4, null=True, verbose_name="Grade")),
                ("branch", models.CharField(blank=True, max_length=4, null=True, verbose_name="Branch")),
                ("asi01", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 1")),
                ("asi02", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 2")),
                ("asi03", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 3")),
                ("asi04", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 4")),
                ("line_number", models.CharField(blank=True, max_length=6, null=True, verbose_name="Line Number")),
                (
                    "special_qualification_id",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Special Qualification Identifier"
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="unit_mtoes", to="auto_dsr.unit"
                    ),
                ),
            ],
            options={
                "db_table": "mtoe",
            },
        ),
        migrations.AddConstraint(
            model_name="mtoe",
            constraint=models.UniqueConstraint(
                fields=("uic", "paragraph_no_1", "paragraph_no_3", "line_number", "position_code"), name="unique_mtoe"
            ),
        ),
        migrations.CreateModel(
            name="GradeRank",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True, verbose_name="Rank Code"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="Rank Description"),
                ),
            ],
            options={
                "db_table": "personnel_grade_ranks",
            },
        ),
        migrations.CreateModel(
            name="RAWReadinessLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dodid", models.CharField(max_length=10, verbose_name="DOD ID")),
                ("acft_mds", models.CharField(blank=True, max_length=16, null=True, verbose_name="Aircraft MDS")),
                ("rl_type", models.CharField(max_length=4, verbose_name="Readiness Level Type")),
                ("readiness_level", models.CharField(max_length=4, verbose_name="Readiness Level")),
                ("instructor_dodid", models.CharField(max_length=10, verbose_name="Instructor DOD ID")),
                ("rl_start_date", models.DateTimeField(verbose_name="Readiness Level Start Date/Time")),
                (
                    "rl_end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Readiness Level End Date/Time"),
                ),
            ],
            options={
                "db_table": "raw_readiness_level",
            },
        ),
        migrations.CreateModel(
            name="RAWSkill",
            fields=[
                (
                    "asi_code",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True, verbose_name="Skill Code"
                    ),
                ),
                (
                    "text_description",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="Skill Description"),
                ),
            ],
            options={
                "db_table": "raw_personnel_skills",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "asi_code",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True, verbose_name="Skill Code"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="Skill Description"),
                ),
            ],
            options={
                "db_table": "personnel_skills",
            },
        ),
        migrations.RemoveField(
            model_name="mtoe",
            name="asi01",
        ),
        migrations.RemoveField(
            model_name="mtoe",
            name="asi02",
        ),
        migrations.RemoveField(
            model_name="mtoe",
            name="asi03",
        ),
        migrations.RemoveField(
            model_name="mtoe",
            name="asi04",
        ),
        migrations.AddField(
            model_name="mtoe",
            name="asi_codes",
            field=models.ManyToManyField(related_name="mtoe_skills", to="personnel.skill"),
        ),
        migrations.AlterField(
            model_name="mtoe",
            name="grade",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="personnel.graderank"
            ),
        ),
        migrations.AlterField(
            model_name="mtoe",
            name="authorized_strength",
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name="Authorized Strength"),
        ),
        migrations.AlterField(
            model_name="mtoe",
            name="required_strength",
            field=models.IntegerField(blank=True, null=True, verbose_name="Required Strength"),
        ),
        migrations.CreateModel(
            name="Soldier",
            fields=[
                ("dodid", models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name="DOD ID")),
                ("first_name", models.CharField(blank=True, max_length=32, null=True, verbose_name="First Name")),
                ("last_name", models.CharField(blank=True, max_length=32, null=True, verbose_name="Last Name")),
                ("positions_posco", models.CharField(blank=True, max_length=8, null=True, verbose_name="Position")),
                ("mos", models.CharField(blank=True, max_length=4, null=True, verbose_name="Primary Specialty")),
                ("asi_codes", models.ManyToManyField(related_name="personnel_readiness_skills", to="personnel.skill")),
                (
                    "grade_rank",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="personnel.graderank"
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="unit_readiness_skills",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.user"
                    ),
                ),
            ],
            options={
                "db_table": "soldier",
            },
        ),
        migrations.CreateModel(
            name="RAWReadinessSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uic", models.CharField(max_length=8, verbose_name="UIC")),
                ("dodid", models.CharField(max_length=10, unique=True, verbose_name="DOD ID")),
                ("grade_rank", models.CharField(blank=True, max_length=4, null=True, verbose_name="Grade Rank Code")),
                ("positions_posco", models.CharField(blank=True, max_length=8, null=True, verbose_name="Position")),
                ("asi_codes", models.JSONField(blank=True, null=True, verbose_name="ASI Codes")),
                ("mos", models.CharField(blank=True, max_length=4, null=True, verbose_name="Primary Specialty")),
                ("first_name", models.CharField(blank=True, max_length=32, null=True, verbose_name="First Name")),
                ("last_name", models.CharField(blank=True, max_length=32, null=True, verbose_name="Last Name")),
            ],
            options={
                "db_table": "raw_readiness_skills",
            },
        ),
        migrations.CreateModel(
            name="ReadinessLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dodid", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="personnel.soldier")),
                ("rl_type", models.CharField(max_length=4, verbose_name="Readiness Level Type")),
                ("readiness_level", models.CharField(max_length=4, verbose_name="Readiness Level")),
                ("instructor_dodid", models.CharField(max_length=10, verbose_name="Instructor DOD ID")),
                ("rl_start_date", models.DateTimeField(verbose_name="Readiness Level Start Date/Time")),
                (
                    "rl_end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Readiness Level End Date/Time"),
                ),
                ("airframe", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="aircraft.airframe")),
            ],
            options={
                "db_table": "readiness_level",
            },
        ),
    ]
