# Generated by Django 4.2.2 on 2025-02-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auto_dsr", "0033_userrequest_date_created_userrequest_date_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAWMTOE",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unit_identification_code", models.CharField(max_length=8, verbose_name="Unit")),
                ("document_number", models.CharField(max_length=16, verbose_name="Unit")),
                ("fiscal_year", models.IntegerField(verbose_name="Fiscal Year")),
                ("change_number", models.IntegerField(verbose_name="Change Number")),
                ("major_army_command_codes", models.CharField(max_length=4, verbose_name="Major Army Command Codes")),
                (
                    "paragraph_no_1",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Paragraph Number 1"),
                ),
                (
                    "paragraph_no_3",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Paragraph Number 3"),
                ),
                (
                    "required_strength",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Required Strength"),
                ),
                (
                    "authorized_strength",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Authorized Strength"),
                ),
                ("identity_code", models.CharField(blank=True, max_length=2, null=True, verbose_name="Identity Code")),
                ("position_code", models.CharField(blank=True, max_length=8, null=True, verbose_name="Position Code")),
                (
                    "army_mgmt_structure_code",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Army Management Structure Code"
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=4, null=True, verbose_name="Grade")),
                ("branch", models.CharField(blank=True, max_length=4, null=True, verbose_name="Branch")),
                ("asi01", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 1")),
                ("asi02", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 2")),
                ("asi03", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 3")),
                ("asi04", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 4")),
                ("line_number", models.CharField(blank=True, max_length=6, null=True, verbose_name="Line Number")),
                (
                    "special_qualification_id",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Special Qualification Identifier"
                    ),
                ),
            ],
            options={
                "db_table": "raw_mtoe",
            },
        ),
        migrations.CreateModel(
            name="MTOE",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("document_number", models.CharField(max_length=16, verbose_name="Unit")),
                ("fiscal_year", models.IntegerField(verbose_name="Fiscal Year")),
                ("change_number", models.IntegerField(verbose_name="Change Number")),
                ("major_army_command_codes", models.CharField(max_length=4, verbose_name="Major Army Command Codes")),
                (
                    "paragraph_no_1",
                    models.CharField(blank=True, max_length=2, null=True, verbose_name="Paragraph Number 1"),
                ),
                (
                    "paragraph_no_3",
                    models.CharField(blank=True, max_length=8, null=True, verbose_name="Paragraph Number 3"),
                ),
                (
                    "required_strength",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Required Strength"),
                ),
                (
                    "authorized_strength",
                    models.CharField(blank=True, max_length=4, null=True, verbose_name="Authorized Strength"),
                ),
                ("identity_code", models.CharField(blank=True, max_length=2, null=True, verbose_name="Identity Code")),
                ("position_code", models.CharField(blank=True, max_length=8, null=True, verbose_name="Position Code")),
                (
                    "army_mgmt_structure_code",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Army Management Structure Code"
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=4, null=True, verbose_name="Grade")),
                ("branch", models.CharField(blank=True, max_length=4, null=True, verbose_name="Branch")),
                ("asi01", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 1")),
                ("asi02", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 2")),
                ("asi03", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 3")),
                ("asi04", models.CharField(blank=True, max_length=4, null=True, verbose_name="ASICO 4")),
                ("line_number", models.CharField(blank=True, max_length=6, null=True, verbose_name="Line Number")),
                (
                    "special_qualification_id",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Special Qualification Identifier"
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="unit_mtoes", to="auto_dsr.unit"
                    ),
                ),
            ],
            options={
                "db_table": "mtoe",
            },
        ),
        migrations.AddConstraint(
            model_name="mtoe",
            constraint=models.UniqueConstraint(
                fields=("uic", "paragraph_no_1", "paragraph_no_3", "line_number", "position_code"), name="unique_mtoe"
            ),
        ),
    ]
