# Generated by Django 4.2.2 on 2025-03-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0051_rawsurvivalpredictions_system_and_more"),
        ("auto_dsr", "0038_rawsynctimestamp"),
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeRank",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True, verbose_name="Rank Code"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="Rank Description"),
                ),
            ],
            options={
                "db_table": "personnel_grade_ranks",
            },
        ),
        migrations.CreateModel(
            name="RAWReadinessLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dodid", models.CharField(max_length=10, verbose_name="DOD ID")),
                ("acft_mds", models.CharField(blank=True, max_length=16, null=True, verbose_name="Aircraft MDS")),
                ("rl_type", models.CharField(max_length=4, verbose_name="Readiness Level Type")),
                ("readiness_level", models.CharField(max_length=4, verbose_name="Readiness Level")),
                ("instructor_dodid", models.CharField(max_length=10, verbose_name="Instructor DOD ID")),
                ("rl_start_date", models.DateTimeField(verbose_name="Readiness Level Start Date/Time")),
                (
                    "rl_end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Readiness Level End Date/Time"),
                ),
            ],
            options={
                "db_table": "raw_readiness_level",
            },
        ),
        migrations.CreateModel(
            name="RAWReadinessSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uic", models.CharField(max_length=8, verbose_name="UIC")),
                ("dodid", models.CharField(max_length=10, unique=True, verbose_name="DOD ID")),
                ("grade_rank", models.CharField(blank=True, max_length=4, null=True, verbose_name="Grade Rank Code")),
                ("positions_posco", models.CharField(blank=True, max_length=4, null=True, verbose_name="Position")),
                ("asi_codes", models.JSONField(blank=True, null=True, verbose_name="ASI Codes")),
                ("mos", models.CharField(blank=True, max_length=4, null=True, verbose_name="Primary Specialty")),
            ],
            options={
                "db_table": "raw_readiness_skills",
            },
        ),
        migrations.CreateModel(
            name="RAWSkill",
            fields=[
                (
                    "asi_code",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True, verbose_name="Skill Code"
                    ),
                ),
                (
                    "text_description",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="Skill Description"),
                ),
            ],
            options={
                "db_table": "raw_personnel_skills",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "asi_code",
                    models.CharField(
                        max_length=8, primary_key=True, serialize=False, unique=True, verbose_name="Skill Code"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True, verbose_name="Skill Description"),
                ),
            ],
            options={
                "db_table": "personnel_skills",
            },
        ),
        migrations.RemoveField(
            model_name="mtoe",
            name="asi01",
        ),
        migrations.RemoveField(
            model_name="mtoe",
            name="asi02",
        ),
        migrations.RemoveField(
            model_name="mtoe",
            name="asi03",
        ),
        migrations.RemoveField(
            model_name="mtoe",
            name="asi04",
        ),
        migrations.CreateModel(
            name="ReadinessSkill",
            fields=[
                ("dodid", models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name="DOD ID")),
                ("positions_posco", models.CharField(blank=True, max_length=4, null=True, verbose_name="Position")),
                ("mos", models.CharField(blank=True, max_length=4, null=True, verbose_name="Primary Specialty")),
                ("asi_codes", models.ManyToManyField(related_name="personnel_readiness_skills", to="personnel.skill")),
                (
                    "grade_rank",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="personnel.graderank"
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="unit_readiness_skills",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "db_table": "readiness_skills",
            },
        ),
        migrations.CreateModel(
            name="ReadinessLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dodid", models.CharField(max_length=10, verbose_name="DOD ID")),
                ("rl_type", models.CharField(max_length=4, verbose_name="Readiness Level Type")),
                ("readiness_level", models.CharField(max_length=4, verbose_name="Readiness Level")),
                ("instructor_dodid", models.CharField(max_length=10, verbose_name="Instructor DOD ID")),
                ("rl_start_date", models.DateTimeField(verbose_name="Readiness Level Start Date/Time")),
                (
                    "rl_end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Readiness Level End Date/Time"),
                ),
                ("airframe", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="aircraft.airframe")),
            ],
            options={
                "db_table": "readiness_level",
            },
        ),
        migrations.AddField(
            model_name="mtoe",
            name="asi_codes",
            field=models.ManyToManyField(related_name="mtoe_skills", to="personnel.skill"),
        ),
        migrations.AlterField(
            model_name="mtoe",
            name="grade",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="personnel.graderank"
            ),
        ),
    ]
