# Generated by Django 4.2.2 on 2025-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0002_graderank_rawreadinesslevel_rawreadinessskill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawreadinessskill",
            name="positions_posco",
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="readinessskill",
            name="positions_posco",
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name="Position"),
        ),
    ]
