# Generated by Django 4.2.2 on 2025-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0003_alter_rawreadinessskill_positions_posco_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mtoe",
            name="authorized_strength",
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name="Authorized Strength"),
        ),
        migrations.AlterField(
            model_name="mtoe",
            name="required_strength",
            field=models.IntegerField(blank=True, null=True, verbose_name="Required Strength"),
        ),
    ]
