# Generated by Django 4.2.2 on 2025-03-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0038_rawsynctimestamp"),
        ("personnel", "0004_alter_mtoe_authorized_strength_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Soldier",
            fields=[
                ("dodid", models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name="DOD ID")),
                ("first_name", models.CharField(blank=True, max_length=32, null=True, verbose_name="First Name")),
                ("last_name", models.CharField(blank=True, max_length=32, null=True, verbose_name="Last Name")),
                ("positions_posco", models.CharField(blank=True, max_length=8, null=True, verbose_name="Position")),
                ("mos", models.CharField(blank=True, max_length=4, null=True, verbose_name="Primary Specialty")),
                ("asi_codes", models.ManyToManyField(related_name="personnel_readiness_skills", to="personnel.skill")),
                (
                    "grade_rank",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="personnel.graderank"
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="unit_readiness_skills",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.user"
                    ),
                ),
            ],
            options={
                "db_table": "soldier",
            },
        ),
        migrations.AddField(
            model_name="rawreadinessskill",
            name="first_name",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="First Name"),
        ),
        migrations.AddField(
            model_name="rawreadinessskill",
            name="last_name",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="Last Name"),
        ),
        migrations.DeleteModel(
            name="ReadinessSkill",
        ),
        migrations.AlterField(
            model_name="readinesslevel",
            name="dodid",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="personnel.soldier"),
        ),
    ]
