# Generated by Django 4.2.2 on 2025-03-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0001_squashed_0005_soldier_rawreadinessskill_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mtoe",
            name="authorized_strength",
            field=models.IntegerField(blank=True, null=True, verbose_name="Authorized Strength"),
        ),
        migrations.AlterField(
            model_name="rawreadinesslevel",
            name="instructor_dodid",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Instructor DOD ID"),
        ),
        migrations.AlterField(
            model_name="readinesslevel",
            name="instructor_dodid",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Instructor DOD ID"),
        ),
    ]
