from abc import ABC
from reports.base.report_format import ReportFormat


class ReportConfig(ABC):
    """
    A ReportConfig object defines the abstract interface to configure a report generated by Griffin
    """

    format: ReportFormat
    debug: bool

    def __init__(self, format: ReportFormat, debug: bool = False):
        self.format = format
        self.debug = debug
        return self

    def __str__(self) -> str:
        return f"DEBUG: {self.debug}\nformat: {self.format}"
