from django.urls import path

from auto_dsr.views import (
    AircraftModule,
    CreateUnit,
    ListTaskForces,
    ListTaskForceUICs,
    acd_export_page,
    acd_export_upload,
    bulk_create_user_setting,
    create_location,
    create_object_transfer_log,
    create_object_transfer_request,
    create_user,
    create_user_request,
    create_user_role,
    create_user_setting,
    customize_unit,
    da_2407_export_page,
    da_2407_export_upload,
    delete_location,
    delete_object_transfer_log,
    delete_object_transfer_request,
    delete_user_role,
    delete_user_setting,
    equipment_transfer,
    get_all_elevated_roles,
    get_all_locations,
    get_all_units,
    get_all_users,
    get_sub_units,
    get_unit_object_transfer_logs,
    get_unit_object_transfer_requests,
    get_unit_phase_order,
    read_location,
    read_object_transfer_log,
    read_object_transfer_request,
    read_unit,
    read_user,
    read_user_request,
    read_user_role,
    read_user_setting,
    record_login,
    set_unit_phase_order,
    transfer_request_adjudication,
    unit_logo_upload,
    update_location,
    update_object_transfer_log,
    update_object_transfer_request,
    update_unit,
    update_user,
    update_user_request,
    update_user_setting,
    xml_acd_export_page,
    xml_acd_export_upload,
)

urlpatterns = [
    # Auto DSR Paths
    path("modules/aircraft/<str:uic>", AircraftModule.as_view()),
    # User Management Paths
    path("user/all", get_all_users, name="get_all_users"),
    path("user/access_requests/create", create_user_request),
    path("user/access_requests/read", read_user_request),
    path("user/access_requests/update", update_user_request),
    path("user/roles/all_elevated", get_all_elevated_roles),
    path("user/roles/create/<str:user_id>", create_user_role, name="create_user_role"),
    path("user/roles/read/<str:user_id>", read_user_role),
    path("user/roles/delete/<str:user_id>", delete_user_role),
    path("user/create/<str:user_id>", create_user),
    path("user/read/<str:user_id>", read_user),
    path("user/update/<str:user_id>", update_user),
    path("user/settings/create", create_user_setting, name="create_user_setting"),
    path("user/settings/read/<str:uic>", read_user_setting, name="read_user_setting"),
    path("user/settings/update/<int:user_setting_id>", update_user_setting, name="update_user_setting"),
    path("user/settings/delete/<int:user_setting_id>", delete_user_setting, name="delete_user_setting"),
    path("user/settings/bulk_creation", bulk_create_user_setting, name="bulk_create_user_setting"),
    path("record_login/<str:user_id>", record_login),
    # Unit Management Paths
    path("units/all", get_all_units, name="get_all_units"),
    path("units/get_sub_units/<str:uic>", get_sub_units, name="get_sub_units"),
    path("units/create", CreateUnit.as_view(), name="create-unit"),
    path("units/read/<str:uic>", read_unit),
    path("units/update/<str:uic>", update_unit, name="edit_unit"),
    path("units/logo_upload", unit_logo_upload, name="upload_logo"),
    path("units/customize_unit", customize_unit, name="customize_unit"),
    path("units/task_forces", ListTaskForces.as_view(), name="list-task-forces"),
    path(
        "units/task_force_uics/",
        ListTaskForceUICs.as_view(),
        name="list-task-force-uics",
    ),
    # ACD Export Upload Paths
    path("acd_export_upload", acd_export_page, name="acd_export_upload_page"),
    path("acd_upload", acd_export_upload, name="acd_upload"),
    path("acd_xml_export_upload", xml_acd_export_page),
    path("acd_xml_upload", xml_acd_export_upload, name="acd_xml_upload"),
    path("da_2407_upload_page", da_2407_export_page, name="da_2407_upload_page"),
    path("da_2407_upload", da_2407_export_upload, name="da_2407_upload"),
    # Locations Management Paths
    path("locations/all", get_all_locations, name="get_all_locations"),
    path("locations/create", create_location, name="create_location"),
    path("locations/read/<int:id>", read_location, name="read_location"),
    path("locations/update/<int:id>", update_location, name="update_location"),
    path("locations/delete/<int:id>", delete_location, name="delete_location"),
    # Unit Phase Order Paths
    path("unit_phase_order/get/<str:unit_uic>", get_unit_phase_order),
    path("unit_phase_order/set/<str:unit_uic>", set_unit_phase_order),
    # Object Transfer Request Endpoints
    path("equipment_transfer", equipment_transfer, name="equipment_transfer"),
    path("transfer_request/create", create_object_transfer_request, name="create_object_transfer_request"),
    path(
        "transfer_request/read/<int:transfer_request_id>",
        read_object_transfer_request,
        name="read_object_transfer_request",
    ),
    path(
        "transfer_request/update/<int:transfer_request_id>",
        update_object_transfer_request,
        name="update_object_transfer_request",
    ),
    path(
        "transfer_request/delete/<int:transfer_request_id>",
        delete_object_transfer_request,
        name="delete_object_transfer_request",
    ),
    path(
        "transfer_request/adjudicate",
        transfer_request_adjudication,
        name="transfer_request_adjudication",
    ),
    path(
        "transfer_requests/<str:unit_uic>",
        get_unit_object_transfer_requests,
        name="get_unit_object_transfer_requests",
    ),
    # Object Transfer Log Endpoints
    path("transfer_logs/create", create_object_transfer_log, name="create_object_transfer_log"),
    path("transfer_logs/read/<int:transfer_log_id>", read_object_transfer_log, name="read_object_transfer_log"),
    path("transfer_logs/update/<int:transfer_log_id>", update_object_transfer_log, name="update_object_transfer_log"),
    path("transfer_logs/delete/<int:transfer_log_id>", delete_object_transfer_log, name="delete_object_transfer_log"),
    path("transfer_logs/unit/<str:unit_uic>", get_unit_object_transfer_logs, name="get_unit_object_transfer_logs"),
]
