from datetime import date
from reportlab.pdfgen.canvas import Canvas

from auto_dsr.models import Unit
from reports.daily_status_report.constants import PAGE_WIDTH, QUARTER_INCH, FOOTER_LOGO_SIZE, inch


def draw_footer(unit: Unit, canvas: Canvas, page_number: int, positions: tuple[str, str, str] = (None, None, None)):
    """
    Draws the Unit Name and header information

    @param unit: (auto_dsr.models.Unit) the Unit to draw the header for
    @param canvas: (Canvas) the canvas to draw the header on
    @param page_number: (int) the page number being drawn
    @param positions (tuple[str, str]) a tuple containing string representations of the unit OIC and NCOIC
    @param slogan: (str) (default None) the unit slogan, if provided
    """
    canvas.saveState()
    canvas.setFont("Roboto", 10)
    canvas.drawString(x=QUARTER_INCH, y=QUARTER_INCH, text=str(page_number))
    if positions[1]:
        canvas.drawString(x=QUARTER_INCH + 20, y=22, text="OIC: %s" % positions[1])
    if positions[2]:
        canvas.drawString(x=QUARTER_INCH + 20, y=10, text="NCOIC: %s" % positions[2])

    canvas.drawRightString(x=PAGE_WIDTH - inch, y=22, text="Generated by griffin.ai")
    canvas.drawRightString(x=PAGE_WIDTH - inch, y=10, text="on %s" % date.today().strftime("%d-%b-%y"))
    canvas.drawImage(
        "static/auto_dsr/img/unit_logos/ai2c.png",
        x=PAGE_WIDTH - 10,
        y=10,
        width=FOOTER_LOGO_SIZE,
        height=FOOTER_LOGO_SIZE,
        preserveAspectRatio=True,
        anchor="se",
        anchorAtXY=True,
    )
    canvas.drawImage(
        "static/auto_dsr/img/griffin-logo.png",
        x=PAGE_WIDTH - (15 + FOOTER_LOGO_SIZE),
        y=10,
        width=FOOTER_LOGO_SIZE,
        height=FOOTER_LOGO_SIZE,
        preserveAspectRatio=True,
        anchor="se",
        anchorAtXY=True,
    )
    canvas.setFont("Roboto-BoldItalic", 20)
    if unit.slogan:
        canvas.drawCentredString(x=PAGE_WIDTH / 2, y=10, text=unit.slogan)
    else:
        canvas.drawCentredString(x=PAGE_WIDTH / 2, y=10, text="Forge the Future!")
    canvas.restoreState()
