# Generated by Django 4.2.2 on 2025-04-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_pk', models.IntegerField(unique=True)),
                ('model_name', models.CharField(default='Unknown Model', max_length=100)),
                ('status', models.CharField(default='NMCM', max_length=50)),
                ('rtl', models.CharField(default='NRTL', max_length=50)),
                ('current_unit', models.CharField(default='WDDRA0', max_length=50)),
                ('total_airframe_hours', models.FloatField(default=0.0)),
                ('flight_hours', models.FloatField(default=0.0)),
                ('hours_to_phase', models.FloatField(default=0.0)),
                ('location', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True)),
                ('date_down', models.DateField()),
                ('ecd', models.DateField()),
                ('last_sync_time', models.DateTimeField(auto_now=True)),
                ('last_export_upload_time', models.DateTimeField(auto_now=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
