# Generated by Django 4.2.2 on 2025-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milds_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='EDIPI Number')),
                ('rank', models.CharField(blank=True, max_length=5, null=True, verbose_name='Rank')),
                ('first_name', models.CharField(max_length=32, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last Name')),
                ('primary_mos', models.CharField(blank=True, max_length=10, null=True, verbose_name='MOS')),
                ('current_unit', models.CharField(default='WDDRA0', max_length=50)),
                ('soldier_flag', models.CharField(max_length=15, verbose_name='Type of Soldier Flag')),
                ('flag_start_date', models.DateField(verbose_name='Start date of Flag')),
                ('flag_end_date', models.DateField(verbose_name='End date of Flag ')),
                ('flag_remarks', models.DateField(verbose_name=' End date of Flag')),
            ],
        ),
    ]
