# Generated by Django 4.2.2 on 2025-05-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milds_App', '0002_soldier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='ecd',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='flight_hours',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='hours_to_phase',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='last_export_upload_time',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='last_sync_time',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='last_update_time',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='location',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='total_airframe_hours',
        ),
        migrations.AlterField(
            model_name='soldier',
            name='flag_remarks',
            field=models.CharField(max_length=100, verbose_name='Remarks'),
        ),
    ]
