# Generated by Django 4.2.2 on 2025-05-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milds_App', '0003_remove_aircraft_ecd_remove_aircraft_flight_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='date_down',
            field=models.DateField(blank=True),
        ),
    ]
