# Generated by Django 4.2.2 on 2025-05-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milds_App', '0004_alter_aircraft_date_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='date_down',
            field=models.DateField(null=True),
        ),
    ]
