# Generated by Django 4.2.2 on 2025-05-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milds_App', '0005_alter_aircraft_date_down'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='flag_end_date',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='flag_remarks',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='flag_start_date',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='soldier_flag',
        ),
        migrations.AddField(
            model_name='soldier',
            name='is_maintainer',
            field=models.BooleanField(default=True, verbose_name='Flag to identify Maintainers'),
        ),
    ]
