# Generated by Django 4.2.2 on 2025-09-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Milds_App', '0006_remove_soldier_flag_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='is_maintainer',
            field=models.BooleanField(default=True, verbose_name='Can Maintain'),
        ),
    ]
