# Generated by Django 4.2.4 on 2023-08-17 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('uic', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Unit Identification Code')),
                ('short_name', models.CharField(max_length=64, verbose_name='Unit Short Name')),
                ('display_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Unit Display Name')),
                ('echelon', models.CharField(choices=[('PLT', 'Platoon'), ('CO', 'Company'), ('BN', 'Battalion'), ('BDE', 'Brigade'), ('DIV', 'Division'), ('CORPS', 'Corps'), ('MACOM', 'Major Command'), ('CNTR', 'Center'), ('ARMY', 'Army'), ('UNK', 'Unknown')], default='UNK', max_length=5, verbose_name='Unit Echelon')),
                ('parent_uic', models.ForeignKey(blank=True, db_column='parent_uic', null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.unit')),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='EDIPI Number')),
                ('rank', models.CharField(blank=True, choices=[('PV1', 'Private'), ('PV2', 'Private'), ('PFC', 'Private First Class'), ('SPC', 'Specialist'), ('CPL', 'Corporal'), ('SGT', 'Sergeant'), ('SSG', 'Staff Sergeant'), ('SFC', 'Sergeant First Class'), ('MSG', 'Master Sergeant'), ('1SG', 'First Sergeant'), ('SGM', 'Sergeant Major'), ('CSM', 'Command Sergeant Major'), ('SMA', 'Sergeant Major of the Army'), ('WO1', 'Warrant Officer 1'), ('CW2', 'Chief Warrant Officer 2'), ('CW3', 'Chief Warrant Officer 3'), ('CW4', 'Chief Warrant Officer 4'), ('CW5', 'Chief Warrant Officer 5'), ('2LT', 'Second Lieutenant'), ('1LT', 'First Lieutenant'), ('CPT', 'Captain'), ('MAJ', 'Major'), ('LTC', 'Lieutenant Colonel'), ('COL', 'Colonel'), ('BG', 'Brigadier General'), ('MG', 'Major General'), ('LTG', 'Lieutenant General'), ('GEN', 'General'), ('GA', 'General of the Army'), ('CTR', 'Contractor'), ('GS1', 'GS-1'), ('GS2', 'GS-2'), ('GS3', 'GS-3'), ('GS4', 'GS-4'), ('GS5', 'GS-5'), ('GS6', 'GS-6'), ('GS7', 'GS-7'), ('GS8', 'GS-8'), ('GS9', 'GS-9'), ('GS10', 'GS-10'), ('GS11', 'GS-11'), ('GS12', 'GS-12'), ('GS13', 'GS-13'), ('GS14', 'GS-14'), ('GS15', 'GS-15'), ('SES1', 'SES-1'), ('SES2', 'SES-2'), ('SES3', 'SES-3'), ('SES4', 'SES-4')], max_length=5, null=True, verbose_name='Rank')),
                ('first_name', models.CharField(max_length=32, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last Name')),
                ('mos', models.CharField(blank=True, choices=[('15B', 'Aircraft Power Plant Repairer'), ('15D', 'Aircraft Powertrain Repairer'), ('15E', 'RQ-7 Unmanned Aircraft Systems Repairer'), ('15F', 'Aircraft Electrician'), ('15G', 'Aircraft Structural Repairer'), ('15H', 'Aircraft Pneudraulics Repairer'), ('15M', 'MQ-1 unmanned Aircraft Systems Repairer'), ('15N', 'Avianic Mechanic'), ('15R', 'AH-64 Attach Helicopter Repairer'), ('15T', 'UH-60 Utility Helicopter Repairer'), ('15U', 'CH-47 Cargo Helicopter Repairer'), ('15Y', 'AH-64 Armament/Electrical/Avionic Systems Repairer')], max_length=3, null=True, verbose_name='MOS')),
                ('maintenance_level', models.CharField(blank=True, choices=[('ML0', 'Maintainer Level 0 - Apprentice'), ('ML1', 'Maintainer Level 1 - Journeyman'), ('ML2', 'Maintainer Level 2 - Repairer'), ('ML3', 'Maintainer Level 3 - Senior Repairer'), ('ML4', 'Maintainer Level 4 - Master Repairer')], max_length=3, null=True, verbose_name='Maintenance Level')),
                ('is_admin', models.BooleanField(verbose_name='Flag to identify AMTP admin users')),
                ('unit', models.ForeignKey(db_column='unit_uic', on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.unit')),
            ],
            options={
                'db_table': 'amtp_users',
            },
        ),
    ]
