# Generated by Django 4.2.4 on 2023-08-22 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '__first__'),
        ('personnel', '0002_alter_soldier_mos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierTasklists',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('ictl', models.ForeignKey(db_column='ictl_id', on_delete=django.db.models.deletion.CASCADE, to='tasks.ictl')),
                ('soldier_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='personnel.soldier')),
            ],
        ),
        migrations.AddField(
            model_name='soldier',
            name='task_lists',
            field=models.ManyToManyField(through='personnel.SoldierTasklists', to='tasks.ictl'),
        ),
    ]
