# Generated by Django 4.2.4 on 2023-08-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_soldiertasklists_soldier_task_lists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldiertasklists',
            options={'verbose_name_plural': 'soldier tasklists'},
        ),
        migrations.AlterModelTable(
            name='soldiertasklists',
            table='soldier_tasklists',
        ),
    ]
