# Generated by Django 4.2.4 on 2023-08-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_remove_soldier_task_lists_delete_soldiertasklists'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='pfc_dor',
            field=models.DateField(blank=True, null=True, verbose_name='PFC DoR'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='pv2_dor',
            field=models.DateField(blank=True, null=True, verbose_name='PV2 DoR'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='sfc_dor',
            field=models.DateField(blank=True, null=True, verbose_name='SFC DoR'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='sgt_dor',
            field=models.DateField(blank=True, null=True, verbose_name='SGT DoR'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='spc_dor',
            field=models.DateField(blank=True, null=True, verbose_name='SPC DoR'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='ssg_dor',
            field=models.DateField(blank=True, null=True, verbose_name='SSG DoR'),
        ),
    ]
