# Generated by Django 4.2.4 on 2023-12-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0008_soldier_is_maintainer_alter_userrequest_access_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="echelon",
            field=models.CharField(
                choices=[
                    ("TEAM", "Team"),
                    ("SQUAD", "Squad"),
                    ("SEC", "Section"),
                    ("PLT", "Platoon"),
                    ("CO", "Company"),
                    ("BN", "Battalion"),
                    ("BDE", "Brigade"),
                    ("DIV", "Division"),
                    ("CORPS", "Corps"),
                    ("MACOM", "Major Command"),
                    ("CNTR", "Center"),
                    ("ARMY", "Army"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=5,
                verbose_name="Unit Echelon",
            ),
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("Manager", "Manager"),
                    ("Admin", "Administrator"),
                    ("Evaluator", "Evaluator"),
                    ("Viewer", "Viewer"),
                ],
                default="Viewer",
                max_length=9,
                verbose_name="User's Requested Role for this unit",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("Manager", "Manager"),
                    ("Admin", "Administrator"),
                    ("Evaluator", "Evaluator"),
                    ("Viewer", "Viewer"),
                ],
                default="Viewer",
                max_length=9,
                verbose_name="User's Role for this unit",
            ),
        ),
    ]
