# Generated by Django 4.2.4 on 2023-12-02 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0009_alter_unit_echelon_alter_userrequest_access_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="login",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="logins",
                to="personnel.soldier",
            ),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="is_admin",
            field=models.BooleanField(verbose_name="Flag to identify AMAP admin users"),
        ),
        migrations.AlterModelTable(
            name="login",
            table="personnel_user_logins",
        ),
        migrations.AlterModelTable(
            name="soldier",
            table="personnel_amap_users",
        ),
        migrations.AlterModelTable(
            name="userrequest",
            table="personnel_user_requests",
        ),
        migrations.AlterModelTable(
            name="userrole",
            table="personnel_user_roles",
        ),
    ]
