# Generated by Django 4.2.4 on 2024-02-07 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0010_alter_login_user_id_alter_soldier_is_admin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoldierTransferRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "gaining_unit",
                    models.ForeignKey(
                        db_column="gaining_uic", on_delete=django.db.models.deletion.CASCADE, to="personnel.unit"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        db_column="requester_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_requests",
                        to="personnel.soldier",
                    ),
                ),
                (
                    "soldier",
                    models.ForeignKey(
                        db_column="soldier_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldier_requested",
                        to="personnel.soldier",
                    ),
                ),
            ],
            options={
                "db_table": "personnel_soldier_transfer_requests",
            },
        ),
        migrations.AddConstraint(
            model_name="soldiertransferrequest",
            constraint=models.UniqueConstraint(fields=("gaining_unit", "soldier"), name="transfer_request_for_unit"),
        ),
    ]
