# Generated by Django 4.2.4 on 2024-06-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0013_alter_soldier_mos"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoldierFlag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Generated Unique Id")),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("Administrative", "Administrative Flags"),
                            ("Unit/Position", "Unit/Positional Flag"),
                            ("Other", "Other Flag Type"),
                        ],
                        default="Other",
                        max_length=15,
                        verbose_name="Type of Soldier Flag",
                    ),
                ),
                (
                    "admin_flag_info",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Leave", "Soldier on leave"),
                            ("Pending Negative Action", "Soldier is pending negative action"),
                            ("Active Investigation", "Soldier is under investigation"),
                            ("Other", "Other Administrative Flag"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="Administrative Flag Info",
                    ),
                ),
                (
                    "unit_position_flag_info",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Non-Maintenance Position", "Soldier is in a Non-Maintenance position"),
                            ("Non-Maintenance Unit", "Soldier is in a unit that does not conduct maintenance"),
                            ("Other", "Other Unit / Role Related Flag"),
                        ],
                        max_length=25,
                        null=True,
                        verbose_name="Unit / Position Flag Info",
                    ),
                ),
                (
                    "available_for_mx",
                    models.BooleanField(default=True, verbose_name="Soldier is available to perform maintenance"),
                ),
                (
                    "mx_restrictions",
                    models.CharField(
                        choices=[
                            ("No Maintenance", "Soldier cannot conduct any maintenance actions"),
                            ("Select Maintenance", "Soldier can conduct select maintenance actions"),
                            ("All Maintenance", "Soldier is able to conduct all maintenance actions"),
                        ],
                        default="All Maintenance",
                        max_length=25,
                        verbose_name="MX restrictions that this flag imposes on the soldier",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date of Flag")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="End Date of Flag")),
                ("flag_remarks", models.TextField(blank=True, max_length=512, null=True, verbose_name="Entry Comment")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="flag_created_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_flags",
                        to="personnel.soldier",
                    ),
                ),
                (
                    "soldier",
                    models.ForeignKey(
                        blank=True,
                        db_column="flag_soldier_id",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldier_flags",
                        to="personnel.soldier",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="flag_unit_uic",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="personnel.unit",
                    ),
                ),
            ],
            options={
                "db_table": "personnel_soldier_flags",
            },
        ),
        migrations.AddConstraint(
            model_name="soldierflag",
            constraint=models.CheckConstraint(
                check=models.Q(("soldier__isnull", False), ("unit__isnull", False), _connector="OR"),
                name="soldier_and_unit_not_both_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="soldierflag",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("admin_flag_info__isnull", False), ("unit_position_flag_info__isnull", False), _connector="OR"
                ),
                name="admin_and_unit_position_flags_not_both_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="soldierflag",
            constraint=models.CheckConstraint(
                check=models.Q(("start_date__lte", models.F("end_date"))), name="flag_start_date_before_end_date"
            ),
        ),
    ]
