# Generated by Django 4.2.4 on 2024-06-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0014_soldierflag_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="soldierflag",
            name="admin_and_unit_position_flags_not_both_null",
        ),
        migrations.AddField(
            model_name="soldierflag",
            name="flag_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
