# Generated by Django 4.2.4 on 2024-08-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0017_remove_historicalsoldierflag_available_for_mx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsoldierflag",
            name="profile_flag_info",
            field=models.CharField(
                blank=True,
                choices=[("Temporary", "Temporary Profile"), ("Permanent", "Permanent Profile")],
                max_length=30,
                null=True,
                verbose_name="Profile Flag Info",
            ),
        ),
        migrations.AddField(
            model_name="soldierflag",
            name="profile_flag_info",
            field=models.CharField(
                blank=True,
                choices=[("Temporary", "Temporary Profile"), ("Permanent", "Permanent Profile")],
                max_length=30,
                null=True,
                verbose_name="Profile Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsoldierflag",
            name="admin_flag_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Leave", "Soldier on leave"),
                    ("TDY", "Soldier is on TDY"),
                    ("SFL TAP", "Soldier is in Soldier For Life - Transition Assistance Program"),
                    ("CSP", "Soldier is in the Career Skills Program"),
                    ("ASAP", "Soldier is in the Army Substance Abuse Prevention Program"),
                    ("Pending Negative Action", "Soldier is pending negative action"),
                    ("Active Investigation", "Soldier is under investigation"),
                    ("Other", "Other Administrative Flag"),
                ],
                max_length=30,
                null=True,
                verbose_name="Administrative Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsoldierflag",
            name="flag_type",
            field=models.CharField(
                choices=[
                    ("Administrative", "Administrative Flag"),
                    ("Unit/Position", "Unit/Positional Flag"),
                    ("Tasking", "Tasking Flag"),
                    ("Profile", "Soldier Profile"),
                    ("Other", "Other Flag Type"),
                ],
                default="Other",
                max_length=15,
                verbose_name="Type of Soldier Flag",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsoldierflag",
            name="tasking_flag_info",
            field=models.CharField(
                blank=True,
                choices=[("Internal", "Internal Tasking"), ("External", "External Tasking")],
                max_length=30,
                null=True,
                verbose_name="Tasking Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsoldierflag",
            name="unit_position_flag_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Non-Maintenance Position", "Soldier is in a Non-Maintenance position"),
                    ("Non-Maintenance Unit", "Soldier is in a unit that does not conduct maintenance"),
                    ("Other", "Other Unit / Role Related Flag"),
                ],
                max_length=30,
                null=True,
                verbose_name="Unit / Position Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="soldierflag",
            name="admin_flag_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Leave", "Soldier on leave"),
                    ("TDY", "Soldier is on TDY"),
                    ("SFL TAP", "Soldier is in Soldier For Life - Transition Assistance Program"),
                    ("CSP", "Soldier is in the Career Skills Program"),
                    ("ASAP", "Soldier is in the Army Substance Abuse Prevention Program"),
                    ("Pending Negative Action", "Soldier is pending negative action"),
                    ("Active Investigation", "Soldier is under investigation"),
                    ("Other", "Other Administrative Flag"),
                ],
                max_length=30,
                null=True,
                verbose_name="Administrative Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="soldierflag",
            name="flag_type",
            field=models.CharField(
                choices=[
                    ("Administrative", "Administrative Flag"),
                    ("Unit/Position", "Unit/Positional Flag"),
                    ("Tasking", "Tasking Flag"),
                    ("Profile", "Soldier Profile"),
                    ("Other", "Other Flag Type"),
                ],
                default="Other",
                max_length=15,
                verbose_name="Type of Soldier Flag",
            ),
        ),
        migrations.AlterField(
            model_name="soldierflag",
            name="tasking_flag_info",
            field=models.CharField(
                blank=True,
                choices=[("Internal", "Internal Tasking"), ("External", "External Tasking")],
                max_length=30,
                null=True,
                verbose_name="Tasking Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="soldierflag",
            name="unit_position_flag_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Non-Maintenance Position", "Soldier is in a Non-Maintenance position"),
                    ("Non-Maintenance Unit", "Soldier is in a unit that does not conduct maintenance"),
                    ("Other", "Other Unit / Role Related Flag"),
                ],
                max_length=30,
                null=True,
                verbose_name="Unit / Position Flag Info",
            ),
        ),
    ]
