# Generated by Django 4.2.4 on 2024-08-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0018_historicalsoldierflag_profile_flag_info_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="soldierflag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("soldier__isnull", True)),
                fields=("unit", "flag_type"),
                name="unit_flags_unique_when_soldier_is_null",
            ),
        ),
    ]
