# Generated by Django 4.2.4 on 2024-09-17 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0020_moscode_moscode_unique_mos_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsoldier",
            name="maintenance_level",
        ),
        migrations.AlterField(
            model_name="historicalsoldier",
            name="mos",
            field=models.ForeignKey(
                blank=True,
                db_column="primary_mos",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="personnel.moscode",
            ),
        ),
        migrations.RenameField(
            model_name="historicalsoldier",
            old_name="mos",
            new_name="primary_mos",
        ),
        migrations.RemoveField(
            model_name="soldier",
            name="maintenance_level",
        ),
        migrations.AlterField(
            model_name="soldier",
            name="mos",
            field=models.ForeignKey(
                blank=True,
                db_column="primary_mos",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="personnel.moscode",
            ),
        ),
        migrations.RenameField(
            model_name="soldier",
            old_name="mos",
            new_name="primary_mos",
        ),
        migrations.AlterField(
            model_name="moscode",
            name="amtp_mos",
            field=models.BooleanField(default=False, verbose_name="MOS falls under AMTP Program"),
        ),
        migrations.AlterField(
            model_name="moscode",
            name="ictl_mos",
            field=models.BooleanField(default=False, verbose_name="MOS has ICTLs in A-MAP"),
        ),
        migrations.CreateModel(
            name="SoldierAdditionalMOS",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique ID")),
                (
                    "mos",
                    models.ForeignKey(
                        db_column="mos", on_delete=django.db.models.deletion.CASCADE, to="personnel.moscode"
                    ),
                ),
                (
                    "soldier",
                    models.ForeignKey(
                        db_column="soldier", on_delete=django.db.models.deletion.CASCADE, to="personnel.soldier"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Soldier Additional MOS",
            },
        ),
        migrations.AddField(
            model_name="soldier",
            name="additional_mos",
            field=models.ManyToManyField(
                related_name="additional_mos", through="personnel.SoldierAdditionalMOS", to="personnel.moscode"
            ),
        ),
        migrations.AddConstraint(
            model_name="soldieradditionalmos",
            constraint=models.UniqueConstraint(fields=("soldier", "mos"), name="unique_additional_mos"),
        ),
    ]
