# Generated by Django 5.0.1 on 2024-09-23 18:32

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0021_remove_historicalsoldier_maintenance_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Generated Unique Id")),
                ("type", models.CharField(max_length=64, verbose_name="Designation Type")),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True, verbose_name="Designation Description"),
                ),
            ],
            options={
                "db_table": "personnel_designation",
            },
        ),
        migrations.CreateModel(
            name="HistoricalSoldierDesignation",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="Auto Generated Unique Id")),
                (
                    "start_date",
                    models.DateTimeField(blank=True, default=None, null=True, verbose_name="Designation Start Date"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, default=None, null=True, verbose_name="Designation End Date"),
                ),
                ("designation_removed", models.BooleanField(default=False)),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical soldier designation",
                "verbose_name_plural": "historical soldier designations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SoldierDesignation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Generated Unique Id")),
                (
                    "start_date",
                    models.DateTimeField(blank=True, default=None, null=True, verbose_name="Designation Start Date"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, default=None, null=True, verbose_name="Designation End Date"),
                ),
                ("designation_removed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "personnel_soldier_designation",
            },
        ),
        migrations.AddConstraint(
            model_name="designation",
            constraint=models.UniqueConstraint(fields=("type", "description"), name="unique_designation"),
        ),
        migrations.AddField(
            model_name="historicalsoldierdesignation",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                db_column="soldier_designation_designation_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="personnel.designation",
            ),
        ),
        migrations.AddField(
            model_name="historicalsoldierdesignation",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                db_column="soldier_designation_last_modified_by_soldier_id",
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="personnel.soldier",
            ),
        ),
        migrations.AddField(
            model_name="historicalsoldierdesignation",
            name="soldier",
            field=models.ForeignKey(
                blank=True,
                db_column="soldier_designation_soldier_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="personnel.soldier",
            ),
        ),
        migrations.AddField(
            model_name="historicalsoldierdesignation",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="designation_unit_uic",
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="personnel.unit",
            ),
        ),
        migrations.AddField(
            model_name="soldierdesignation",
            name="designation",
            field=models.ForeignKey(
                db_column="soldier_designation_designation_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soldier_designation_designation",
                to="personnel.designation",
            ),
        ),
        migrations.AddField(
            model_name="soldierdesignation",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                db_column="soldier_designation_last_modified_by_soldier_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="soldier_designation_last_modified_by",
                to="personnel.soldier",
            ),
        ),
        migrations.AddField(
            model_name="soldierdesignation",
            name="soldier",
            field=models.ForeignKey(
                db_column="soldier_designation_soldier_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soldier_designation_soldier",
                to="personnel.soldier",
            ),
        ),
        migrations.AddField(
            model_name="soldierdesignation",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="designation_unit_uic",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="personnel.unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="soldierdesignation",
            constraint=models.UniqueConstraint(
                fields=("soldier", "designation", "unit"), name="unique_soldier_designation"
            ),
        ),
    ]
