# Generated by Django 4.2.4 on 2024-11-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0022_designation_historicalsoldierdesignation_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="soldierdesignation",
            name="unique_soldier_designation",
        ),
        migrations.AlterField(
            model_name="historicalsoldierflag",
            name="admin_flag_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Leave", "Soldier on leave"),
                    ("TDY", "Soldier is on TDY"),
                    ("Failed Evaluation", "Soldier Failed an Evaluation"),
                    ("SFL TAP", "Soldier is in Soldier For Life - Transition Assistance Program"),
                    ("CSP", "Soldier is in the Career Skills Program"),
                    ("ASAP", "Soldier is in the Army Substance Abuse Prevention Program"),
                    ("Pending Negative Action", "Soldier is pending negative action"),
                    ("Active Investigation", "Soldier is under investigation"),
                    ("Other", "Other Administrative Flag"),
                ],
                max_length=30,
                null=True,
                verbose_name="Administrative Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="soldierflag",
            name="admin_flag_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Leave", "Soldier on leave"),
                    ("TDY", "Soldier is on TDY"),
                    ("Failed Evaluation", "Soldier Failed an Evaluation"),
                    ("SFL TAP", "Soldier is in Soldier For Life - Transition Assistance Program"),
                    ("CSP", "Soldier is in the Career Skills Program"),
                    ("ASAP", "Soldier is in the Army Substance Abuse Prevention Program"),
                    ("Pending Negative Action", "Soldier is pending negative action"),
                    ("Active Investigation", "Soldier is under investigation"),
                    ("Other", "Other Administrative Flag"),
                ],
                max_length=30,
                null=True,
                verbose_name="Administrative Flag Info",
            ),
        ),
    ]
