# Generated by Django 4.2.4 on 2024-11-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0023_remove_soldierdesignation_unique_soldier_designation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsoldier",
            name="recieve_emails",
            field=models.BooleanField(default=False, verbose_name="Receieve E-mail notifications"),
        ),
        migrations.AddField(
            model_name="soldier",
            name="recieve_emails",
            field=models.BooleanField(default=False, verbose_name="Receieve E-mail notifications"),
        ),
        migrations.AlterField(
            model_name="historicalsoldier",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Flag to identify AMAP admin users"),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Flag to identify AMAP admin users"),
        ),
    ]
