# Generated by Django 4.2.2 on 2025-02-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0001_initial"),
        ("personnel", "0024_historicalsoldier_recieve_emails_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="parent_uic",
        ),
        migrations.AlterField(
            model_name="historicalsoldier",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="unit_uic",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsoldierdesignation",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="designation_unit_uic",
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsoldierflag",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="flag_unit_uic",
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserrole",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="unit_uic",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="soldier",
            name="unit",
            field=models.ForeignKey(
                db_column="unit_uic", on_delete=django.db.models.deletion.DO_NOTHING, to="units.unit"
            ),
        ),
        migrations.AlterField(
            model_name="soldierdesignation",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="designation_unit_uic",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="soldierflag",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="flag_unit_uic",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="soldiertransferrequest",
            name="gaining_unit",
            field=models.ForeignKey(
                db_column="gaining_uic", on_delete=django.db.models.deletion.CASCADE, to="units.unit"
            ),
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="uic",
            field=models.ForeignKey(db_column="uic", on_delete=django.db.models.deletion.CASCADE, to="units.unit"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="unit",
            field=models.ForeignKey(db_column="unit_uic", on_delete=django.db.models.deletion.CASCADE, to="units.unit"),
        ),
    ]
