# Generated by Django 4.2.2 on 2025-02-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0031_alter_event_gaining_unit_alter_event_uic_and_more"),
        ("faults", "0010_alter_fault_unit"),
        ("personnel", "0025_remove_unit_parent_uic_alter_historicalsoldier_unit_and_more"),
        ("tasks", "0025_alter_historicalictl_unit_alter_historicaltask_unit_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
