# Generated by Django 4.2.4 on 2025-03-11 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0026_delete_unit"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="soldierflag",
            name="unit_flags_unique_when_soldier_is_null",
        ),
    ]
