# Generated by Django 4.2.4 on 2025-04-01 20:53

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0027_remove_soldierflag_unit_flags_unique_when_soldier_is_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhaseTeam",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Generated Unique Id")),
                ("phase_id", models.IntegerField(verbose_name="Inspection ID (from Griffin)")),
                (
                    "phase_members",
                    models.JSONField(
                        default=list,
                        verbose_name="List of user_ids for Phase Team Members (not including phase lead or assistant phase lead)",
                    ),
                ),
                (
                    "assistant_phase_lead",
                    models.ForeignKey(
                        db_column="assistant_phase_lead_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="phases_asst_lead",
                        to="personnel.soldier",
                    ),
                ),
                (
                    "phase_lead",
                    models.ForeignKey(
                        db_column="phase_lead_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="phases_lead",
                        to="personnel.soldier",
                    ),
                ),
            ],
            options={
                "db_table": "personnel_phase_team",
            },
        ),
        migrations.CreateModel(
            name="HistoricalPhaseTeam",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="Auto Generated Unique Id")),
                ("phase_id", models.IntegerField(verbose_name="Inspection ID (from Griffin)")),
                (
                    "phase_members",
                    models.JSONField(
                        default=list,
                        verbose_name="List of user_ids for Phase Team Members (not including phase lead or assistant phase lead)",
                    ),
                ),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "assistant_phase_lead",
                    models.ForeignKey(
                        blank=True,
                        db_column="assistant_phase_lead_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="personnel.soldier",
                    ),
                ),
                (
                    "phase_lead",
                    models.ForeignKey(
                        blank=True,
                        db_column="phase_lead_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="personnel.soldier",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical phase team",
                "verbose_name_plural": "historical phase teams",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
