# Generated by Django 4.2.4 on 2025-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0028_phaseteam_historicalphaseteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsoldier",
            name="reporting_ml",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ML0", "Maintainer Level 0 - Apprentice"),
                    ("ML1", "Maintainer Level 1 - Journeyman"),
                    ("ML2", "Maintainer Level 2 - Repairer"),
                    ("ML3", "Maintainer Level 3 - Senior Repairer"),
                    ("ML4", "Maintainer Level 4 - Master Repairer"),
                ],
                max_length=3,
                null=True,
                verbose_name="Reporting Maintenance Level",
            ),
        ),
        migrations.AddField(
            model_name="soldier",
            name="reporting_ml",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ML0", "Maintainer Level 0 - Apprentice"),
                    ("ML1", "Maintainer Level 1 - Journeyman"),
                    ("ML2", "Maintainer Level 2 - Repairer"),
                    ("ML3", "Maintainer Level 3 - Senior Repairer"),
                    ("ML4", "Maintainer Level 4 - Master Repairer"),
                ],
                max_length=3,
                null=True,
                verbose_name="Reporting Maintenance Level",
            ),
        ),
    ]
