# Generated by Django 4.2.4 on 2025-05-31 18:18

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("units", "0001_initial"),
        ("personnel", "0029_historicalsoldier_reporting_ml_soldier_reporting_ml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsoldierflag",
            name="unit_position_flag_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Non-Maintenance Position", "Unit is comprised of Non-Maintenance positions"),
                    ("Non-Maintenance Unit", "Unit does not conduct maintenance"),
                    ("Block Leave", "Unit is on block leave"),
                    ("Other", "Other Unit Flag"),
                ],
                max_length=30,
                null=True,
                verbose_name="Unit / Position Flag Info",
            ),
        ),
        migrations.AlterField(
            model_name="soldierflag",
            name="unit_position_flag_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Non-Maintenance Position", "Unit is comprised of Non-Maintenance positions"),
                    ("Non-Maintenance Unit", "Unit does not conduct maintenance"),
                    ("Block Leave", "Unit is on block leave"),
                    ("Other", "Other Unit Flag"),
                ],
                max_length=30,
                null=True,
                verbose_name="Unit / Position Flag Info",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalUserRequest",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="Auto Unique Id")),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("Manager", "Manager"),
                            ("Admin", "Administrator"),
                            ("Evaluator", "Evaluator"),
                            ("Viewer", "Viewer"),
                        ],
                        default="Viewer",
                        max_length=9,
                        verbose_name="User's Requested Role for this unit",
                    ),
                ),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        blank=True,
                        db_column="uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="units.unit",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="personnel.soldier",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user request",
                "verbose_name_plural": "historical user requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSoldierTransferRequest",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="Auto Unique Id")),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "gaining_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="gaining_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="units.unit",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        db_column="requester_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="personnel.soldier",
                    ),
                ),
                (
                    "soldier",
                    models.ForeignKey(
                        blank=True,
                        db_column="soldier_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="personnel.soldier",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical soldier transfer request",
                "verbose_name_plural": "historical soldier transfer requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
