# Generated by Django 4.2.4 on 2025-05-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0030_alter_historicalsoldierflag_unit_position_flag_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserrequest",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("Viewer", "Viewer"),
                    ("Recorder", "Recorder"),
                    ("Manager", "Manager"),
                    ("Admin", "Administrator"),
                    ("Evaluator", "Evaluator"),
                ],
                default="Viewer",
                max_length=9,
                verbose_name="User's Requested Role for this unit",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserrole",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("Viewer", "Viewer"),
                    ("Recorder", "Recorder"),
                    ("Manager", "Manager"),
                    ("Admin", "Administrator"),
                    ("Evaluator", "Evaluator"),
                ],
                default="Viewer",
                max_length=9,
                verbose_name="User's Role for this unit",
            ),
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("Viewer", "Viewer"),
                    ("Recorder", "Recorder"),
                    ("Manager", "Manager"),
                    ("Admin", "Administrator"),
                    ("Evaluator", "Evaluator"),
                ],
                default="Viewer",
                max_length=9,
                verbose_name="User's Requested Role for this unit",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("Viewer", "Viewer"),
                    ("Recorder", "Recorder"),
                    ("Manager", "Manager"),
                    ("Admin", "Administrator"),
                    ("Evaluator", "Evaluator"),
                ],
                default="Viewer",
                max_length=9,
                verbose_name="User's Role for this unit",
            ),
        ),
    ]
