# Generated by Django 4.2.4 on 2025-07-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0032_rawmtoe_rawskill_skill_mtoe_mtoe_unique_mtoe"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAWReadinessSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uic", models.CharField(max_length=8, verbose_name="UIC")),
                ("dodid", models.CharField(max_length=10, unique=True, verbose_name="DOD ID")),
                ("first_name", models.CharField(blank=True, max_length=32, null=True, verbose_name="First Name")),
                ("last_name", models.CharField(blank=True, max_length=32, null=True, verbose_name="Last Name")),
                ("grade_rank", models.CharField(blank=True, max_length=4, null=True, verbose_name="Grade Rank Code")),
                ("positions_posco", models.CharField(blank=True, max_length=8, null=True, verbose_name="Position")),
                ("asi_codes", models.JSONField(blank=True, null=True, verbose_name="ASI Codes")),
                ("mos", models.CharField(blank=True, max_length=4, null=True, verbose_name="Primary Specialty")),
            ],
            options={
                "db_table": "raw_readiness_skills",
            },
        ),
        migrations.AddField(
            model_name="soldier",
            name="asi_codes",
            field=models.ManyToManyField(related_name="personnel_readiness_skills", to="personnel.skill"),
        ),
    ]
