# Generated by Django 4.2.25 on 2026-02-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0033_rawreadinessskill_soldier_asi_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsoldierflag',
            name='simcasualty_flag_info',
            field=models.CharField(blank=True, choices=[('SimulatedInjury', 'Simulated Injury'), ('SimulatedKIA', 'Simulated KIA')], max_length=30, null=True, verbose_name='Simulate Casualty Info'),
        ),
        migrations.AddField(
            model_name='soldierflag',
            name='simcasualty_flag_info',
            field=models.CharField(blank=True, choices=[('SimulatedInjury', 'Simulated Injury'), ('SimulatedKIA', 'Simulated KIA')], max_length=30, null=True, verbose_name='Simulate Casualty Info'),
        ),
    ]
