# Generated by Django 4.2.4 on 2023-08-22 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ictl',
            fields=[
                ('ictl_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('skill_level', models.CharField(blank=True, choices=[('SL0', 'Skill Level 0'), ('SL1', 'Skill Level 1'), ('SL2', 'Skill Level 2'), ('SL3', 'Skill Level 3'), ('SL4', 'Skill Level 4')], max_length=3, null=True, verbose_name='Skill Level')),
                ('target_audience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Target Audience')),
            ],
            options={
                'verbose_name_plural': 'ictl',
                'db_table': 'ictl',
            },
        ),
        migrations.CreateModel(
            name='IctlTasks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique ID')),
                ('ictl', models.ForeignKey(db_column='ictl_id', on_delete=django.db.models.deletion.CASCADE, to='tasks.ictl')),
            ],
            options={
                'db_table': 'ictl_tasks',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_number', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Task Number')),
                ('title', models.CharField(max_length=40, verbose_name='Task Title')),
                ('pdf_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Task PDF Url')),
                ('skill_level', models.CharField(blank=True, choices=[('SL0', 'Skill Level 0'), ('SL1', 'Skill Level 1'), ('SL2', 'Skill Level 2'), ('SL3', 'Skill Level 3'), ('SL4', 'Skill Level 4')], max_length=3, null=True, verbose_name='Skill Level')),
                ('training_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Training Location')),
                ('frequency', models.CharField(blank=True, max_length=30, null=True, verbose_name='Training Frequency')),
                ('ictl', models.ManyToManyField(through='tasks.IctlTasks', to='tasks.ictl')),
            ],
            options={
                'verbose_name_plural': 'tasks',
                'db_table': 'task',
            },
        ),
        migrations.AddField(
            model_name='ictltasks',
            name='task',
            field=models.ForeignKey(db_column='task_number', on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
