# Generated by Django 4.2.4 on 2023-08-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ictltasks',
            options={'verbose_name_plural': 'ictl tasks'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_title',
        ),
        migrations.RemoveField(
            model_name='ictl',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='ictl',
            name='ictl_title',
            field=models.CharField(default=None, max_length=30, verbose_name='ICTL Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ictl',
            name='mos',
            field=models.CharField(blank=True, choices=[('15B', 'Aircraft Power Plant Repairer'), ('15D', 'Aircraft Powertrain Repairer'), ('15E', 'RQ-7 Unmanned Aircraft Systems Repairer'), ('15F', 'Aircraft Electrician'), ('15G', 'Aircraft Structural Repairer'), ('15H', 'Aircraft Pneudraulics Repairer'), ('15M', 'MQ-1 unmanned Aircraft Systems Repairer'), ('15N', 'Avionic Mechanic'), ('15R', 'AH-64 Attach Helicopter Repairer'), ('15T', 'UH-60 Utility Helicopter Repairer'), ('15U', 'CH-47 Cargo Helicopter Repairer'), ('15Y', 'AH-64 Armament/Electrical/Avionic Systems Repairer')], max_length=3, null=True, verbose_name='MOS'),
        ),
        migrations.AddField(
            model_name='ictl',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ICTL Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pdf_url',
            field=models.URLField(blank=True, null=True, verbose_name='Task PDF Url'),
        ),
    ]
