# Generated by Django 4.2.4 on 2023-08-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_ictltasks_options_rename_title_task_task_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictl',
            name='target_audience',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Target Audience'),
        ),
    ]
