# Generated by Django 4.2.4 on 2023-08-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=240, verbose_name='Task Title'),
        ),
    ]
