# Generated by Django 4.2.4 on 2023-08-28 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ictl',
        ),
        migrations.DeleteModel(
            name='IctlTasks',
        ),
        migrations.AddField(
            model_name='task',
            name='ictl',
            field=models.ForeignKey(db_column='ictl_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.ictl'),
            preserve_default=False,
        ),
    ]
