# Generated by Django 4.2.4 on 2023-08-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_ictl_delete_ictltasks_task_ictl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictl',
            name='target_audience',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Target Audience'),
        ),
    ]
