# Generated by Django 4.2.4 on 2023-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_ictl_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictl',
            name='target_audience',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Target Audience'),
        ),
    ]
