# Generated by Django 4.2.4 on 2023-08-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictl',
            name='ictl_title',
            field=models.CharField(max_length=75, verbose_name='ICTL Title'),
        ),
    ]
