# Generated by Django 4.2.4 on 2023-08-28 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_task_ictl_ictltasks_task_ictl'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique ID')),
                ('mos_code', models.CharField(blank=True, choices=[('15B', 'Aircraft Power Plant Repairer'), ('15D', 'Aircraft Powertrain Repairer'), ('15E', 'RQ-7 Unmanned Aircraft Systems Repairer'), ('15F', 'Aircraft Electrician'), ('15G', 'Aircraft Structural Repairer'), ('15H', 'Aircraft Pneudraulics Repairer'), ('15M', 'MQ-1 unmanned Aircraft Systems Repairer'), ('15N', 'Avionic Mechanic'), ('15R', 'AH-64 Attach Helicopter Repairer'), ('15T', 'UH-60 Utility Helicopter Repairer'), ('15U', 'CH-47 Cargo Helicopter Repairer'), ('15Y', 'AH-64 Armament/Electrical/Avionic Systems Repairer')], max_length=3, null=True, verbose_name='MOS Code')),
            ],
            options={
                'verbose_name_plural': 'mos',
                'db_table': 'mos',
            },
        ),
        migrations.RemoveField(
            model_name='ictl',
            name='mos',
        ),
        migrations.CreateModel(
            name='MosIctls',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique ID')),
                ('ictl', models.ForeignKey(db_column='ictl', on_delete=django.db.models.deletion.CASCADE, to='tasks.ictl')),
                ('mos', models.ForeignKey(db_column='mos', on_delete=django.db.models.deletion.CASCADE, to='tasks.mos')),
            ],
            options={
                'verbose_name_plural': 'MosIctls',
            },
        ),
        migrations.AddField(
            model_name='ictl',
            name='mos',
            field=models.ManyToManyField(through='tasks.MosIctls', to='tasks.mos'),
        ),
    ]
