# Generated by Django 4.2.4 on 2023-08-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_alter_soldiertasklists_options_and_more'),
        ('tasks', '0014_mos_remove_ictl_mos_mosictls_ictl_mos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ictl',
            name='proponent',
            field=models.CharField(blank=True, choices=[('011', 'US Army Aviation Center of Excellence'), ('552', 'US Army Aviation Logistics School'), ('000', 'Unit Specific')], max_length=6, null=True, verbose_name='Propenent'),
        ),
        migrations.AddField(
            model_name='ictl',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.unit'),
        ),
        migrations.AlterField(
            model_name='ictl',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('SL1', 'Skill Level 1'), ('SL2', 'Skill Level 2'), ('SL3', 'Skill Level 3'), ('SL4', 'Skill Level 4')], max_length=3, null=True, verbose_name='Skill Level'),
        ),
    ]
