# Generated by Django 4.2.4 on 2023-08-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_ictl_proponent_ictl_unit_alter_ictl_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sus_level',
            field=models.CharField(blank=True, choices=[('1', 'Sustainment Level 1'), ('2', 'Sustainment Level 2'), ('3', 'Sustainment Level 3'), ('4', 'Sustainment Level 4')], max_length=1, null=True, verbose_name='Sustainment Level'),
        ),
    ]
