# Generated by Django 4.2.4 on 2023-10-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_task_sus_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictl',
            name='proponent',
            field=models.CharField(blank=True, choices=[('USAACE', 'US Army Aviation Center of Excellence'), ('USAALS', 'US Army Aviation Logistics School'), ('Unit', 'Unit Specific')], max_length=6, null=True, verbose_name='Propenent'),
        ),
    ]
