# Generated by Django 4.2.4 on 2024-04-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0020_alter_task_unit_task_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
