# Generated by Django 4.2.2 on 2023-09-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phase_sched", "0001_squashed_0002_rename_phase_type_plannedphase_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plannedphase",
            name="type",
        ),
        migrations.AddField(
            model_name="plannedphase",
            name="phase_type",
            field=models.CharField(
                choices=[
                    ("480", "UH-60 480H"),
                    ("960", "UH-60 960H"),
                    ("250", "AH-64 250H"),
                    ("500", "AH-64 500h"),
                    ("320", "CH-47 320H"),
                    ("640", "CH-47 640H"),
                    ("GEN", "Generic PMI"),
                    ("TEST", "Test"),
                ],
                db_column="type",
                default="GEN",
                max_length=12,
                verbose_name="Phase Inspection Type",
            ),
        ),
    ]
