# Generated by Django 4.2.2 on 2023-10-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phase_sched", "0004_alter_plannedphase_phase_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedphase",
            name="phase_type",
            field=models.CharField(
                choices=[
                    ("480", "UH-60 480H"),
                    ("960", "UH-60 960H"),
                    ("250", "AH-64 250H"),
                    ("500", "AH-64 500H"),
                    ("320", "CH-47 320H"),
                    ("640", "CH-47 640H"),
                    ("GEN", "Generic PMI"),
                ],
                default="GEN",
                max_length=12,
                verbose_name="Phase Inspection Type",
            ),
        ),
    ]
