# Generated by Django 4.2.2 on 2023-10-26 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0005_aircraft_current_unit_and_more'),
        ('phase_sched', '0007_remove_phaseeditlog_serial_phasedeletelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasedeletelog',
            name='serial',
            field=models.ForeignKey(db_column='aircraft', default=None, on_delete=django.db.models.deletion.PROTECT, to='aircraft.aircraft'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phaseeditlog',
            name='serial',
            field=models.ForeignKey(db_column='aircraft', default='TEST', on_delete=django.db.models.deletion.PROTECT, to='aircraft.aircraft'),
            preserve_default=False,
        ),
    ]
