# Generated by Django 4.2.25 on 2026-03-03 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('model_name', models.CharField(default='Unknown Model', max_length=100)),
                ('status', models.CharField(default='NMC', max_length=50)),
                ('rtl', models.CharField(default='NRTL', max_length=50)),
                ('current_unit', models.CharField(default='WDDRA0', max_length=50)),
                ('total_airframe_hours', models.FloatField(blank=True, null=True)),
                ('flight_hours', models.FloatField(blank=True, null=True)),
                ('hours_to_phase', models.FloatField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_down', models.DateField(blank=True, null=True)),
                ('ecd', models.DateField(blank=True, null=True)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_export_upload_time', models.DateTimeField(blank=True, null=True)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('total_events', models.IntegerField(default=0)),
                ('applied_events', models.IntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back_end.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='EDIPI Number')),
                ('rank', models.CharField(blank=True, max_length=5, null=True, verbose_name='Rank')),
                ('first_name', models.CharField(max_length=32, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last Name')),
                ('primary_mos', models.CharField(blank=True, max_length=10, null=True, verbose_name='MOS')),
                ('current_unit', models.CharField(default='WDDRA0', max_length=50)),
                ('is_maintainer', models.BooleanField(default=True, verbose_name='Can Maintain')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_pk', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('message', models.TextField()),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('changed', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='back_end.scenariorun')),
            ],
            options={
                'indexes': [models.Index(fields=['run'], name='back_end_sc_run_id_b082e2_idx'), models.Index(fields=['aircraft_pk'], name='back_end_sc_aircraf_0a62c4_idx'), models.Index(fields=['user_id'], name='back_end_sc_user_id_9fa508_idx'), models.Index(fields=['created_at'], name='back_end_sc_created_85c9ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScenarioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=10)),
                ('rtl', models.CharField(blank=True, max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('date_down', models.DateField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(blank=True, db_column='aircraft_pk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_events', to='back_end.aircraft')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='back_end.scenario')),
                ('soldier', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenario_events', to='back_end.soldier')),
            ],
            options={
                'indexes': [models.Index(fields=['scenario'], name='back_end_sc_scenari_8bfc92_idx'), models.Index(fields=['aircraft'], name='back_end_sc_aircraf_8ae3b9_idx'), models.Index(fields=['soldier'], name='back_end_sc_user_id_a736f3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scenarioevent',
            constraint=models.UniqueConstraint(fields=('scenario', 'aircraft'), name='uniq_event_per_aircraft_in_scenario'),
        ),
        migrations.AddConstraint(
            model_name='scenarioevent',
            constraint=models.UniqueConstraint(fields=('scenario', 'soldier'), name='uniq_event_per_soldier_in_scenario'),
        ),
    ]
