# Generated by Django 4.2.25 on 2025-10-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_pk', models.IntegerField(unique=True)),
                ('model_name', models.CharField(default='Unknown Model', max_length=100)),
                ('status', models.CharField(default='NMCM', max_length=50)),
                ('rtl', models.CharField(default='NRTL', max_length=50)),
                ('current_unit', models.CharField(default='WDDRA0', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('date_down', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='EDIPI Number')),
                ('rank', models.CharField(blank=True, max_length=5, null=True, verbose_name='Rank')),
                ('first_name', models.CharField(max_length=32, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last Name')),
                ('primary_mos', models.CharField(blank=True, max_length=10, null=True, verbose_name='MOS')),
                ('current_unit', models.CharField(default='WDDRA0', max_length=50)),
                ('is_maintainer', models.BooleanField(default=True, verbose_name='Can Maintain')),
            ],
        ),
    ]
