# Generated by Django 4.2.25 on 2025-10-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='ecd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='flight_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='hours_to_phase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='last_export_upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='location',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='total_airframe_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_pk',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='date_down',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.CharField(default='NMC', max_length=50),
        ),
    ]
