# Generated by Django 6.0.1 on 2026-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_soldier_simulated_casualty_soldierflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioevent',
            name='personnel_changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scenariorun',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariorunlog',
            name='aircraft_pk',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='scenariorunlog',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
