# Generated by Django 4.2.25 on 2026-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_soldier_simulated_casualty_soldierflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariorunlog',
            name='aircraft_pk',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
