# Generated by Django 4.2.25 on 2025-11-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_aircraft_ecd_aircraft_flight_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='user_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='EDIPI Number'),
        ),
    ]
