# Generated by Django 6.0.1 on 2026-03-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_scenarioevent_personnel_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
