# Generated by Django 4.2.25 on 2026-03-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_alter_scenariorunlog_aircraft_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioevent',
            name='current_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scenarioevent',
            name='is_maintainer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenarioevent',
            name='primary_mos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='scenarioevent',
            name='rank',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='scenarioevent',
            name='simulated_casualty',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
