# Generated by Django 6.0.1 on 2026-03-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0004_soldier_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariorunlog',
            name='aircraft_pk',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='scenariorunlog',
            name='changed',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='scenariorunlog',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
