# Generated by Django 4.2.25 on 2025-11-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0004_scenario_scenariorun_scenariorunlog_scenarioevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioevent',
            name='aircraft_pk',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scenariorunlog',
            name='aircraft_pk',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
