# Generated by Django 4.2.25 on 2026-03-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0004_scenarioevent_current_unit_and_more'),
        ('back_end', '0005_alter_scenariorunlog_aircraft_pk_and_more'),
    ]

    operations = [
    ]
