# Generated by Django 4.2.25 on 2025-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0005_alter_scenarioevent_aircraft_pk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarioevent',
            name='aircraft_pk',
        ),
        migrations.AddField(
            model_name='scenarioevent',
            name='aircraft_pk_int',
            field=models.IntegerField(blank=True, db_column='aircraft_pk_int', null=True),
        ),
        migrations.AlterField(
            model_name='scenarioevent',
            name='rtl',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='scenarioevent',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
