# Generated by Django 4.2.25 on 2026-03-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0006_merge_20260324_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarioevent',
            name='current_unit',
        ),
        migrations.RemoveField(
            model_name='scenarioevent',
            name='is_maintainer',
        ),
        migrations.RemoveField(
            model_name='scenarioevent',
            name='primary_mos',
        ),
        migrations.RemoveField(
            model_name='scenarioevent',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='scenarioevent',
            name='simulated_casualty',
        ),
        migrations.AlterField(
            model_name='scenariorunlog',
            name='aircraft_pk',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
