# Generated by Django 4.2.25 on 2025-11-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0006_remove_scenarioevent_aircraft_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioevent',
            name='aircraft',
            field=models.ForeignKey(blank=True, db_column='aircraft_pk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenario_events', to='back_end.aircraft', to_field='aircraft_pk'),
        ),
    ]
