# Generated by Django 4.2.25 on 2025-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0007_scenarioevent_aircraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_pk',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scenariorunlog',
            name='aircraft_pk',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
