# Generated by Django 4.2.25 on 2025-11-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0008_alter_aircraft_aircraft_pk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarioevent',
            name='aircraft_pk_int',
        ),
        migrations.AddField(
            model_name='scenarioevent',
            name='soldier',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenario_events', to='back_end.soldier'),
        ),
        migrations.AddField(
            model_name='scenariorunlog',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
