# Generated by Django 4.2.2 on 2025-11-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0009_remove_scenarioevent_aircraft_pk_int_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scenarioevent',
            constraint=models.UniqueConstraint(fields=('scenario', 'aircraft'), name='uniq_event_per_aircraft_in_scenario'),
        ),
        migrations.AddConstraint(
            model_name='scenarioevent',
            constraint=models.UniqueConstraint(fields=('scenario', 'soldier'), name='uniq_event_per_soldier_in_scenario'),
        ),
    ]
