# Generated by Django 4.2.2 on 2025-11-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0010_scenarioevent_uniq_event_per_aircraft_in_scenario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='id',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_pk',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scenarioevent',
            name='aircraft',
            field=models.ForeignKey(blank=True, db_column='aircraft_pk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenario_events', to='back_end.aircraft'),
        ),
    ]
