# Generated by Django 4.2.25 on 2026-02-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0011_remove_aircraft_id_alter_aircraft_aircraft_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariorunlog',
            name='changed',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='scenarioevent',
            index=models.Index(fields=['scenario'], name='back_end_sc_scenari_8bfc92_idx'),
        ),
        migrations.AddIndex(
            model_name='scenarioevent',
            index=models.Index(fields=['aircraft'], name='back_end_sc_aircraf_8ae3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='scenarioevent',
            index=models.Index(fields=['soldier'], name='back_end_sc_user_id_a736f3_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariorunlog',
            index=models.Index(fields=['run'], name='back_end_sc_run_id_b082e2_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariorunlog',
            index=models.Index(fields=['aircraft_pk'], name='back_end_sc_aircraf_0a62c4_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariorunlog',
            index=models.Index(fields=['user_id'], name='back_end_sc_user_id_9fa508_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariorunlog',
            index=models.Index(fields=['created_at'], name='back_end_sc_created_85c9ab_idx'),
        ),
    ]
