# Generated by Django 4.2.25 on 2026-02-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0012_scenariorunlog_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='serial',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
