# Generated by Django 4.2.25 on 2026-02-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0013_scenariorunlog_changed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Generated Unique Id')),
                ('simcasualty_flag_info', models.CharField(blank=True, choices=[('SimulatedInjury', 'Simulated Injury'), ('SimulatedKIA', 'Simulated KIA')], max_length=30, null=True, verbose_name='Simulate Casualty Info')),
                ('start_date', models.DateField(verbose_name='Start Date of Flag')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date of Flag')),
                ('flag_remarks', models.TextField(blank=True, max_length=512, null=True, verbose_name='Entry Comment')),
                ('flag_deleted', models.BooleanField(default=False)),
                ('last_modified_by', models.ForeignKey(blank=True, db_column='last_modified_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_modified_flags', to='back_end.soldier')),
                ('soldier', models.ForeignKey(blank=True, db_column='flag_soldier_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldier_flags', to='back_end.soldier')),
            ],
        ),
    ]
