# Generated by Django 4.2.25 on 2026-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0014_soldierflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='simulated_casualty',
            field=models.CharField(choices=[('SimulatedInjury', 'Simulated Injury'), ('SimulatedKIA', 'Simulated KIA')], default=None, max_length=30, verbose_name='Simulated Casualty Status'),
        ),
    ]
