# Generated by Django 4.2.25 on 2026-03-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0015_soldier_simulated_casualty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='simulated_casualty',
            field=models.CharField(blank=True, choices=[('SimulatedInjury', 'Simulated Injury'), ('SimulatedKIA', 'Simulated KIA')], default=None, max_length=30, null=True, verbose_name='Simulated Casualty Status'),
        ),
    ]
