from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch

PAGE_HEIGHT, PAGE_WIDTH = letter
THREE_QUARTER_INCH = 0.75 * inch
HALF_INCH = 0.5 * inch
QUARTER_INCH = 0.25 * inch
HEADER_FONT_SIZE = 24
TABLE_FONT_SIZE = 5
RTL_TABLE_FONT_SIZE = 4
DSR_SLANT_TABLE_HEADER_FONT_SIZE = 6
DSR_SLANT_TABLE_FONT_SIZE = 16
SUMMARY_TABLE_FONT_SIZE = 8
UNIT_LOGO_SIZE = THREE_QUARTER_INCH
GRIFFIN_LOGO_SIZE = 25
MODS_HEADER_ROTATION = 50
LANDSCAPE_FULL_FRAME_WIDTH = PAGE_WIDTH - HALF_INCH
DSR_DETAILS_FRAME_HEIGHT = PAGE_HEIGHT - (2 * inch)
DSR_SLANT_FRAME_START = DSR_DETAILS_FRAME_HEIGHT + HALF_INCH
BASE_COLUMN_COUNT = 12

REMARKS_STYLE = ParagraphStyle(
    name="dsr_remarks_style", fontName="Roboto", fontSize=TABLE_FONT_SIZE, leading=TABLE_FONT_SIZE
)

PMC_STATUSES = set(["PMC", "PMCS", "PMCM"])
NMC_STATUSES = set(["NMC", "NMCM", "NMCS", "FIELD", "SUST", "DADE"])
