# Generated by Django 4.2.2 on 2023-09-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('aircraft', '0005_aircraft_current_unit_and_more'),
        ('auto_dsr', '0018_taskforce_readiness_uic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseLane',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('name', models.CharField(max_length=64, verbose_name='Phase Lane Name')),
                ('unit', models.ForeignKey(db_column='unit_uic', on_delete=django.db.models.deletion.CASCADE, to='auto_dsr.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedPhase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('phase_type', models.CharField(choices=[('480', 'UH-60 480H'), ('960', 'UH-60 960H'), ('250', 'AH-64 250H'), ('500', 'AH-64 500h'), ('320', 'CH-47 320H'), ('640', 'CH-47 640H'), ('GEN', 'Generic PMI'), ('TEST', 'Test')], default='GEN', max_length=12, verbose_name='Phase Inspection Type')),
                ('start_date', models.DateField(verbose_name='Day of Phase Start')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Day of Phase End')),
                ('aircraft', models.ForeignKey(db_column='aircraft_serial', on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircraft')),
                ('lane', models.ForeignKey(db_column='phase_lane_id', on_delete=django.db.models.deletion.CASCADE, to='phase_sched.phaselane')),
            ],
        ),
        migrations.AddConstraint(
            model_name='phaselane',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_lane_name_per_unit'),
        ),
        migrations.RenameField(
            model_name='plannedphase',
            old_name='phase_type',
            new_name='type',
        ),
    ]
