# Generated by Django 4.2.2 on 2023-09-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase_sched', '0003_remove_plannedphase_type_plannedphase_phase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedphase',
            name='phase_type',
            field=models.CharField(choices=[('480', 'UH-60 480H'), ('960', 'UH-60 960H'), ('250', 'AH-64 250H'), ('500', 'AH-64 500h'), ('320', 'CH-47 320H'), ('640', 'CH-47 640H'), ('GEN', 'Generic PMI'), ('TEST', 'Test')], default='GEN', max_length=12, verbose_name='Phase Inspection Type'),
        ),
    ]
