# Generated by Django 4.2.2 on 2023-10-23 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0005_aircraft_current_unit_and_more'),
        ('auto_dsr', '0018_taskforce_readiness_uic'),
        ('phase_sched', '0005_alter_plannedphase_phase_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseEditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('effective_time', models.DateTimeField(verbose_name='The timestamp when a user makde this edit')),
                ('record', models.JSONField(verbose_name='The columns previous an newly edited value')),
                ('serial', models.ForeignKey(db_column='serila', on_delete=django.db.models.deletion.PROTECT, to='aircraft.aircraft')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='auto_dsr.user')),
            ],
            options={
                'db_table': 'phase_edit_log',
            },
        ),
    ]
