# Generated by Django 4.2.2 on 2023-10-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0018_taskforce_readiness_uic'),
        ('phase_sched', '0006_phaseeditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phaseeditlog',
            name='serial',
        ),
        migrations.CreateModel(
            name='PhaseDeleteLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('effective_time', models.DateTimeField(verbose_name='The timestamp when a user made the deletion')),
                ('record', models.JSONField(verbose_name='The record of the phase that was deleted')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='auto_dsr.user')),
            ],
            options={
                'db_table': 'phase_delete_log',
            },
        ),
    ]
