# Generated by Django 4.2.2 on 2024-02-16 02:54

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uac",
            name="last_export_upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(1776, 7, 4, 0, 0, tzinfo=datetime.timezone.utc),
                verbose_name="Last time this UAC was updated from an ACD Export Upload",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uav",
            name="last_export_upload_time",
            field=models.DateTimeField(
                default=datetime.datetime(1776, 7, 4, 0, 0, tzinfo=datetime.timezone.utc),
                verbose_name="Last time this UAV was updated from an ACD Export Upload",
            ),
            preserve_default=False,
        ),
    ]
