# Generated by Django 4.2.2 on 2024-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uas", "0002_uac_last_export_upload_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uac",
            name="should_sync",
            field=models.BooleanField(
                default=True, verbose_name="An indicator if the UAC should be updated automatically"
            ),
        ),
        migrations.AddField(
            model_name="uav",
            name="should_sync",
            field=models.BooleanField(
                default=True, verbose_name="An indicator if the UAV should be updated automatically"
            ),
        ),
    ]
