# Generated by Django 5.0.1 on 2024-07-13 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0026_auto_20240610_0957'),
        ('uas', '0006_remove_historicaluac_history_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('flight_id', models.CharField(max_length=64, verbose_name='The flight id of the flight')),
                ('status_date', models.DateTimeField(verbose_name='When the flight status was set')),
                ('mission_type', models.CharField(choices=[('TRAINING', 'Training'), ('SERVICE', 'Service'), ('COMBAT', 'Combat'), ('IMMINENT_DANGER', 'Imminent Danger'), ('RELAY', 'Relay'), ('COVID_OPERATION', 'Coronavirus Operation'), ('ACCEPTANCE_TEST_FLIGHT', 'Acceptance Test Flight'), ('EXPERIMENTAL_TEST_FLIGHT', 'Experimental Test Flight'), ('MAINTENANCE_TEST_FLIGHT', 'Maintenance Test Flight'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=32, verbose_name='The mission type for this flight')),
                ('flight_codes', models.JSONField(default=list, verbose_name='list of flight codes as for this filght')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='The DateTime this flight began')),
                ('intermediate_datetime', models.DateTimeField(blank=True, null=True, verbose_name='The DateTime of an intermediate stop in the flight')),
                ('stop_datetime', models.DateTimeField(blank=True, null=True, verbose_name='The DateTime this flight ended')),
                ('flight_D_hours', models.FloatField(default=0, verbose_name='The number of daytime hours flown for this flight')),
                ('flight_DS_hours', models.FloatField(default=0, verbose_name='The number of daytime system hours flown for this flight')),
                ('flight_N_hours', models.FloatField(default=0, verbose_name='The number of night time hours flown for this flight')),
                ('flight_NG_hours', models.FloatField(default=0, verbose_name='The number of night goggles hours flown for this flight')),
                ('flight_NS_hours', models.FloatField(default=0, verbose_name='The number of night system hours flown for this flight')),
                ('flight_S_hours', models.FloatField(default=0, verbose_name='The number of system hours flown for this flight')),
                ('flight_H_hours', models.FloatField(default=0, verbose_name='The number of hooded hours flown for this flight')),
                ('flight_W_hours', models.FloatField(default=0, verbose_name='The number of weather hours flown for this flight')),
                ('total_hours', models.IntegerField(default=0, verbose_name='The total number of hours for this flight')),
                ('uav', models.ForeignKey(blank=True, db_column='uav_serial_number', null=True, on_delete=django.db.models.deletion.PROTECT, to='uas.uav')),
                ('unit', models.ForeignKey(db_column='unit_uic', on_delete=django.db.models.deletion.PROTECT, related_name='uas_flights', to='auto_dsr.unit')),
            ],
            options={
                'db_table': 'uas_flights',
            },
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('flight_id',), name='unique_flight_id'),
        ),
    ]
