# Generated by Django 4.2.2 on 2024-08-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uas", "0009_historicaluac_field_sync_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluac",
            name="field_sync_status",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Defines whether individual fields should update"
            ),
        ),
        migrations.AlterField(
            model_name="historicaluav",
            name="field_sync_status",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Defines whether individual fields should update"
            ),
        ),
        migrations.AlterField(
            model_name="uac",
            name="field_sync_status",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Defines whether individual fields should update"
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="field_sync_status",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Defines whether individual fields should update"
            ),
        ),
    ]
