# Generated by Django 4.2.2 on 2025-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uas", "0010_alter_historicaluac_field_sync_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluav",
            name="equipment_number",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="UAV Equipment Number"),
        ),
        migrations.AddField(
            model_name="uav",
            name="equipment_number",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="UAV Equipment Number"),
        ),
    ]
