# Generated by Django 4.2.4 on 2024-11-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogicalClock",
            fields=[
                (
                    "model",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="The model the logical clock is operating for",
                    ),
                ),
                ("current_time", models.IntegerField(verbose_name="The current logical time for the model")),
            ],
            options={
                "verbose_name": "Logical Clock",
                "verbose_name_plural": "Logical Clocks",
            },
        ),
    ]
