import json

from auto_dsr.models import Unit
from supply.models import ProvisionalStock, RawProvisionalStock


def create_single_test_provisional_stock(
    dodaac: str = "ttt",
    gcss_internal_material_number: str = "test",
    material_number: str = "0123456",
    total_stock: float = 3,
    serviceable_stock: float = 2,
    non_serviceable_stock: float = 2,
    num_serviceable_zero_balance_batches: float = 2,
    num_non_serviceable_zero_balance_batches: float = 3,
    batches: float = 2,
    serviceable_batches: float = 2,
    non_serviceable_batches: float = 2,
    num_batches: float = 2,
    num_serviceable_batches: float = 2,
    num_non_serviceable_batches: float = 2,
    is_bench_stock: bool = True,
    sloc_types: str = "t",
    reorder_point: float = 2,
    safety_stock: float = 2,
    has_storage_bin: bool = True,
    is_shop_stock: bool = True,
    is_authorized: bool = True,
    authorized_stock: float = 2,
    unit_price: float = 2,
    unserviceable_credit_value: float = 2,
    serviceable_credit_value: float = 2,
    serviceable_exchange_credit_price: float = 2,
    total_stock_valuation: float = 100,
    storage_location: str = "QQQ",
    material_description: str = "Banana Bread",
    uic=Unit,
    plant: str = "PLANT1",
) -> ProvisionalStock:
    """
    Creates a single Provisional Stock object.

    @returns (Provisional Stock Object)
        The newly created Provisional Stock object
    """
    new_provisional_stock = ProvisionalStock.objects.create(
        dodaac=dodaac,
        gcss_internal_material_number=gcss_internal_material_number,
        total_stock=total_stock,
        serviceable_stock=serviceable_stock,
        non_serviceable_stock=non_serviceable_stock,
        num_serviceable_zero_balance_batches=num_serviceable_zero_balance_batches,
        num_non_serviceable_zero_balance_batches=num_non_serviceable_zero_balance_batches,
        batches=batches,
        serviceable_batches=serviceable_batches,
        non_serviceable_batches=non_serviceable_batches,
        num_batches=num_batches,
        num_serviceable_batches=num_serviceable_batches,
        num_non_serviceable_batches=num_non_serviceable_batches,
        is_bench_stock=is_bench_stock,
        sloc_types=sloc_types,
        reorder_point=reorder_point,
        safety_stock=safety_stock,
        has_storage_bin=has_storage_bin,
        is_shop_stock=is_shop_stock,
        is_authorized=is_authorized,
        authorized_stock=authorized_stock,
        unit_price=unit_price,
        unserviceable_credit_value=unserviceable_credit_value,
        serviceable_credit_value=serviceable_credit_value,
        serviceable_exchange_credit_price=serviceable_exchange_credit_price,
        total_stock_valuation=total_stock_valuation,
        storage_location=storage_location,
        material_description=material_description,
        uic=uic,
        plant=plant,
        material_number=material_number,
    )

    return new_provisional_stock


def create_single_test_raw_provisional_stock(
    uic: str = "XX-123457",
    plant: str = "Test Plant",
    storage_location: str = "QQQ",
    serviceable_stock: float = 2.0,
    material_description: str = "Banana Bread",
    material_number: str = "0123456",
    is_bench_stock: bool = True,
    is_shop_stock: bool = True,
    gcss_internal_material_number: str = "Test GCSS Mat Number",
    mrp_area_id: str = "0123456",
    total_stock: float = 2.0,
    non_serviceable_stock: float = 1.0,
    num_serviceable_zero_balance_batches: int = 1,
    num_non_serviceable_zero_balance_batches: int = 0,
    batches: dict = {},
    serviceable_batches: dict = {},
    non_serviceable_batches: dict = {},
    num_batches: int = 0,
    num_serviceable_batches: int = 0,
    num_non_serviceable_batches: int = 0,
    storage_bin: str = "BIN001",
    sloc_class: str = "SLOCC",
    sloc_types: dict = {},
    sloc_fe_abbr: str = "SLOCFEABBR",
    sloc_fe_name: str = "SLOC FE Name",
    ric: str = "SSA",
    support_ric: str = "SRC",
    sloc_description: str = "SLOC DESC",
    derived_dodaac: str = "DDOAAC",
    sloc_description_uic: str = "XX-123457",
    mrp_type: str = "MT",
    reorder_point: float = 2.2,
    safety_stock: float = 0.0,
    has_storage_bin: bool = False,
    is_authorized: bool = False,
    authorized_stock: float = 0.0,
    material_number_type: str = "MAT NUM TYPE",
    line_item_number: str = "012345",
    material_number_with_fsc: str = "012345ABCD",
    material_number_with_fsc_type: str = "012345TP",
    recovery_code: str = "R",
    unit_price: float = 1.1,
    unserviceable_credit_value: float = 0.5,
    serviceable_credit_value: float = 0.6,
    serviceable_exchange_credit_price: float = 0.2,
    sc_name: str = "SCNAME",
    total_stock_valuation: float = 0.9,
    stock_id: str = "STOCKID",
) -> RawProvisionalStock:
    """
    Creates a single Raw Provisional Stock object.
    """
    new_provisional_stock = RawProvisionalStock.objects.create(
        plant=plant,
        storage_location=storage_location,
        serviceable_stock=serviceable_stock,
        material_description=material_description,
        material_number=material_number,
        is_bench_stock=is_bench_stock,
        is_shop_stock=is_shop_stock,
        gcss_internal_material_number=gcss_internal_material_number,
        mrp_area_id=mrp_area_id,
        total_stock=total_stock,
        non_serviceable_stock=non_serviceable_stock,
        num_serviceable_zero_balance_batches=num_serviceable_zero_balance_batches,
        num_non_serviceable_zero_balance_batches=num_non_serviceable_zero_balance_batches,
        batches=json.dumps(batches),
        serviceable_batches=json.dumps(serviceable_batches),
        non_serviceable_batches=json.dumps(non_serviceable_batches),
        num_batches=num_batches,
        num_serviceable_batches=num_serviceable_batches,
        num_non_serviceable_batches=num_non_serviceable_batches,
        storage_bin=storage_bin,
        uic=uic,
        sloc_class=sloc_class,
        sloc_types=json.dumps(sloc_types),
        sloc_fe_abbr=sloc_fe_abbr,
        sloc_fe_name=sloc_fe_name,
        ric=ric,
        support_ric=support_ric,
        sloc_description=sloc_description,
        derived_dodaac=derived_dodaac,
        sloc_description_uic=sloc_description_uic,
        mrp_type=mrp_type,
        reorder_point=reorder_point,
        safety_stock=safety_stock,
        has_storage_bin=has_storage_bin,
        is_authorized=is_authorized,
        authorized_stock=authorized_stock,
        material_number_type=material_number_type,
        line_item_number=line_item_number,
        material_number_with_fsc=material_number_with_fsc,
        material_number_with_fsc_type=material_number_with_fsc_type,
        recovery_code=recovery_code,
        unit_price=unit_price,
        unserviceable_credit_value=unserviceable_credit_value,
        serviceable_credit_value=serviceable_credit_value,
        serviceable_exchange_credit_price=serviceable_exchange_credit_price,
        sc_name=sc_name,
        total_stock_valuation=total_stock_valuation,
        stock_id=stock_id,
    )

    return new_provisional_stock
