import datetime
from typing import List

from django.utils import timezone

from aircraft.models import RAWStock, Stock
from auto_dsr.models import Unit


def create_single_raw_stock(
    uic: str = "TSTUNIT",
    dodacc: str = "DODACCTST",
    gcss_internal_material_number: str = "GCSSIMN1",
    plant: str = "PLANT1",
    mrp_area_id: str = "MRPID1",
    storage_location: str = "STORAGE1",
    batch: str = "BATCH1",
    unrestricted_stock: float = 1.0,
    restricted_stock: float = 1.0,
    stock_in_transfer: float = 0.0,
    stock_in_quality_inspection: float = 2.0,
    blocked_stock: float = 0.0,
    centaur_sync_timestamp: datetime = timezone.now() - datetime.timedelta(days=7),
    total_stock: float = 10.0,
    is_bench_stock: bool = False,
    storage_bin: str = "STGBIN1",
    is_serviceable_batch: bool = True,
    serviceable_batches: str = "SVCBTC1",
    non_serviceable_batches: str = "NONSVCBTC1",
    serviceable_stock: float = 2.0,
    non_serviceable_stock: float = 0.0,
    num_serviceable_zero_balance_batches: float = 0.0,
    num_non_serviceable_zero_balance_batches: float = 0.0,
    sloc_class: str = "SLOCCLASS",
    sloc_types: List = ["SLOCTYPE1", "SLOCKTYPE2"],
    sloc_fe_abbr: str = "SLOCFEABBR",
    sloc_fe_name: str = "SLOCFENAME",
    ric: str = "RIC",
    support_ric: str = "SPPRIC",
    sloc_description: str = "SLOCDESC",
    derived_dodaac: str = "DERIVED",
    sloc_description_uic: str = "TSTUNT2",
    mrp_type: str = "MRPT",
    reorder_point: float = 3.0,
    safety_stock: float = 1.0,
    has_storage_bin: bool = True,
    is_shop_stock: bool = False,
    is_authorized: bool = True,
    authorized_stock: float = 10.0,
    material_number: str = "MATNUM",
    material_number_type: str = "MATTYP",
    material_description: str = "MATDESC",
    line_item_number: str = "LIN1",
    material_number_with_fsc: str = "MATNWFSC",
    material_number_with_fsc_type: str = "MATNWFSCT",
    recovery_code: str = "RECC",
    unit_price: float = 1.1,
    unserviceable_credit_value: float = 0.9,
    serviceable_credit_value: float = 1.0,
    serviceable_exchange_credit_price: float = 0.5,
    sc_name: str = "SCNAME",
    total_stock_valuation: float = 0.6,
    stock_id: str = "STOCKID1",
):
    """
    Create RAW Part Longevity entry.
    """
    return RAWStock.objects.create(
        uic=uic,
        dodacc=dodacc,
        gcss_internal_material_number=gcss_internal_material_number,
        plant=plant,
        mrp_area_id=mrp_area_id,
        storage_location=storage_location,
        batch=batch,
        unrestricted_stock=unrestricted_stock,
        restricted_stock=restricted_stock,
        stock_in_transfer=stock_in_transfer,
        stock_in_quality_inspection=stock_in_quality_inspection,
        blocked_stock=blocked_stock,
        centaur_sync_timestamp=centaur_sync_timestamp,
        total_stock=total_stock,
        is_bench_stock=is_bench_stock,
        storage_bin=storage_bin,
        is_serviceable_batch=is_serviceable_batch,
        serviceable_batches=serviceable_batches,
        non_serviceable_batches=non_serviceable_batches,
        serviceable_stock=serviceable_stock,
        non_serviceable_stock=non_serviceable_stock,
        num_serviceable_zero_balance_batches=num_serviceable_zero_balance_batches,
        num_non_serviceable_zero_balance_batches=num_non_serviceable_zero_balance_batches,
        sloc_class=sloc_class,
        sloc_types=sloc_types,
        sloc_fe_abbr=sloc_fe_abbr,
        sloc_fe_name=sloc_fe_name,
        ric=ric,
        support_ric=support_ric,
        sloc_description=sloc_description,
        derived_dodaac=derived_dodaac,
        sloc_description_uic=sloc_description_uic,
        mrp_type=mrp_type,
        reorder_point=reorder_point,
        safety_stock=safety_stock,
        has_storage_bin=has_storage_bin,
        is_shop_stock=is_shop_stock,
        is_authorized=is_authorized,
        authorized_stock=authorized_stock,
        material_number=material_number,
        material_number_type=material_number_type,
        material_description=material_description,
        line_item_number=line_item_number,
        material_number_with_fsc=material_number_with_fsc,
        material_number_with_fsc_type=material_number_with_fsc_type,
        recovery_code=recovery_code,
        unit_price=unit_price,
        unserviceable_credit_value=unserviceable_credit_value,
        serviceable_credit_value=serviceable_credit_value,
        serviceable_exchange_credit_price=serviceable_exchange_credit_price,
        sc_name=sc_name,
        total_stock_valuation=total_stock_valuation,
        stock_id=stock_id,
    )


def create_single_stock(
    uic: Unit | None = None,
    dodacc: str = "DODACCTST",
    gcss_internal_material_number: str = "GCSSIMN1",
    plant: str = "PLANT1",
    mrp_area_id: str = "MRPID1",
    storage_location: str = "STORAGE1",
    batch: str = "BATCH1",
    unrestricted_stock: float = 1.0,
    restricted_stock: float = 1.0,
    stock_in_transfer: float = 0.0,
    stock_in_quality_inspection: float = 2.0,
    blocked_stock: float = 0.0,
    centaur_sync_timestamp: datetime = timezone.now() - datetime.timedelta(days=7),
    total_stock: float = 10.0,
    is_bench_stock: bool = False,
    storage_bin: str = "STGBIN1",
    is_serviceable_batch: bool = True,
    serviceable_batches: str = "SVCBTC1",
    non_serviceable_batches: str = "NONSVCBTC1",
    serviceable_stock: float = 2.0,
    non_serviceable_stock: float = 0.0,
    num_serviceable_zero_balance_batches: float = 0.0,
    num_non_serviceable_zero_balance_batches: float = 0.0,
    sloc_class: str = "SLOCCLASS",
    sloc_types: List = ["SLOCTYPE1", "SLOCKTYPE2"],
    sloc_fe_abbr: str = "SLOCFEABBR",
    sloc_fe_name: str = "SLOCFENAME",
    ric: str = "RIC",
    support_ric: str = "SPPRIC",
    sloc_description: str = "SLOCDESC",
    derived_dodaac: str = "DERIVED",
    sloc_description_uic: Unit | None = None,
    mrp_type: str = "MRPT",
    reorder_point: float = 3.0,
    safety_stock: float = 1.0,
    has_storage_bin: bool = True,
    is_shop_stock: bool = False,
    is_authorized: bool = True,
    authorized_stock: float = 10.0,
    material_number: str = "MATNUM",
    material_number_type: str = "MATTYP",
    material_description: str = "MATDESC",
    line_item_number: str = "LIN1",
    material_number_with_fsc: str = "MATNWFSC",
    material_number_with_fsc_type: str = "MATNWFSCT",
    recovery_code: str = "RECC",
    unit_price: float = 1.1,
    unserviceable_credit_value: float = 0.9,
    serviceable_credit_value: float = 1.0,
    serviceable_exchange_credit_price: float = 0.5,
    sc_name: str = "SCNAME",
    total_stock_valuation: float = 0.6,
    stock_id: str = "STOCKID1",
):
    """
    Create RAW Part Longevity entry.
    """
    return Stock.objects.create(
        uic=uic,
        dodacc=dodacc,
        gcss_internal_material_number=gcss_internal_material_number,
        plant=plant,
        mrp_area_id=mrp_area_id,
        storage_location=storage_location,
        batch=batch,
        unrestricted_stock=unrestricted_stock,
        restricted_stock=restricted_stock,
        stock_in_transfer=stock_in_transfer,
        stock_in_quality_inspection=stock_in_quality_inspection,
        blocked_stock=blocked_stock,
        centaur_sync_timestamp=centaur_sync_timestamp,
        total_stock=total_stock,
        is_bench_stock=is_bench_stock,
        storage_bin=storage_bin,
        is_serviceable_batch=is_serviceable_batch,
        serviceable_batches=serviceable_batches,
        non_serviceable_batches=non_serviceable_batches,
        serviceable_stock=serviceable_stock,
        non_serviceable_stock=non_serviceable_stock,
        num_serviceable_zero_balance_batches=num_serviceable_zero_balance_batches,
        num_non_serviceable_zero_balance_batches=num_non_serviceable_zero_balance_batches,
        sloc_class=sloc_class,
        sloc_types=sloc_types,
        sloc_fe_abbr=sloc_fe_abbr,
        sloc_fe_name=sloc_fe_name,
        ric=ric,
        support_ric=support_ric,
        sloc_description=sloc_description,
        derived_dodaac=derived_dodaac,
        sloc_description_uic=sloc_description_uic,
        mrp_type=mrp_type,
        reorder_point=reorder_point,
        safety_stock=safety_stock,
        has_storage_bin=has_storage_bin,
        is_shop_stock=is_shop_stock,
        is_authorized=is_authorized,
        authorized_stock=authorized_stock,
        material_number=material_number,
        material_number_type=material_number_type,
        material_description=material_description,
        line_item_number=line_item_number,
        material_number_with_fsc=material_number_with_fsc,
        material_number_with_fsc_type=material_number_with_fsc_type,
        recovery_code=recovery_code,
        unit_price=unit_price,
        unserviceable_credit_value=unserviceable_credit_value,
        serviceable_credit_value=serviceable_credit_value,
        serviceable_exchange_credit_price=serviceable_exchange_credit_price,
        sc_name=sc_name,
        total_stock_valuation=total_stock_valuation,
        stock_id=stock_id,
    )
