# Generated by Django 4.2.2 on 2024-02-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystatusreport",
            name="csv",
            field=models.BooleanField(
                default=False, verbose_name="A boolean flag indicating if a set of csvs were generated for the user"
            ),
        ),
    ]
