# Generated by Django 4.2.2 on 2025-01-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aircraft", "0045_aircraft_equipment_number_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("auto_dsr", "0031_merge_20240725_1331"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("date_generated", models.DateTimeField(verbose_name="Date Generated")),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AnnouncementNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="Announcement Title")),
                ("announcement", models.TextField(max_length=1024, verbose_name="Annoucement")),
                ("announcement_url", models.TextField(max_length=512, verbose_name="Announcement Teams URL")),
            ],
            options={
                "db_table": "notifications_announcement",
            },
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="ApprovedDeniedNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                ("request_type", models.CharField(max_length=48, verbose_name="Type of Request")),
                ("request_action", models.TextField(max_length=256, verbose_name="Action Requested")),
                ("approved_denied", models.CharField(max_length=48, verbose_name="Type of Request")),
            ],
            options={
                "db_table": "notifications_approved_denied",
            },
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="BugfixNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                ("bugfix", models.CharField(max_length=32, verbose_name="Bugfix short display")),
                ("bugfix_details", models.TextField(max_length=1024, verbose_name="Bugfix details")),
                ("bugfix_url", models.TextField(max_length=512, verbose_name="Bugfix Teams URL")),
            ],
            options={
                "db_table": "notifications_bugfix",
            },
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="ReleaseNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                ("release_version", models.CharField(max_length=15, verbose_name="Release Version Number")),
                ("release_notes", models.TextField(max_length=1024, verbose_name="Release Notes")),
                ("release_url", models.TextField(max_length=512, verbose_name="Release Notes Teams URL")),
            ],
            options={
                "db_table": "notifications_version_release",
            },
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("notification_read", models.BooleanField(default=False, verbose_name="Notification Read")),
                (
                    "notification",
                    models.ForeignKey(
                        db_column="notification_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id", on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferRequestNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                (
                    "transfer_request",
                    models.ForeignKey(
                        db_column="transfer_request_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.aircrafttransferrequest",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_transfer_requests",
            },
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="AccessRequestNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                (
                    "access_request",
                    models.ForeignKey(
                        db_column="access_request_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.userrequest",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_access_requests",
            },
            bases=("notifications.notification",),
        ),
    ]
