# Generated by Django 4.2.2 on 2025-02-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0034_objecttransferrequest_last_updated_by_and_more"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferrequestnotification",
            name="transfer_request",
            field=models.ForeignKey(
                db_column="transfer_request_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="auto_dsr.objecttransferrequest",
            ),
        ),
    ]
