# Generated by Django 4.2.2 on 2024-06-27 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0026_auto_20240610_0957"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agse", "0002_alter_agse_options_alter_agseedits_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAGSE",
            fields=[
                ("equipment_number", models.CharField(db_index=True, max_length=12, verbose_name="Equipment Number")),
                ("serial_number", models.CharField(max_length=32, verbose_name="Serial Number")),
                ("lin", models.CharField(max_length=12, verbose_name="Line Item Number")),
                ("model", models.CharField(max_length=24, null=True, verbose_name="Equipment Model")),
                ("nomenclature", models.CharField(max_length=64, verbose_name="Equipment Nomenclature")),
                ("display_name", models.CharField(max_length=24, verbose_name="Equipment Display Name")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("FMC", "Fully Mission Capable"),
                            ("PMC", "Partially Mission Capable"),
                            ("PMCM", "Partially Mission Capable - Maintenance"),
                            ("PMCS", "Partially Mission Capable - Sustainment"),
                            ("NMC", "Non Mission Capable"),
                            ("NMCS", "Non Mission Capable - Supply"),
                            ("NMCM", "Non Mission Capable - Maintenance"),
                            ("FIELD", "Field"),
                            ("SUST", "Sustainment"),
                            ("DADE", "Department of the Army Directed Event"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=15,
                        null=True,
                        verbose_name="Maintenance Status (FMC, NMC)",
                    ),
                ),
                (
                    "earliest_nmc_start",
                    models.DateField(blank=True, null=True, verbose_name="Starting date of NMC Status"),
                ),
                ("days_nmc", models.FloatField(blank=True, null=True, verbose_name="Days NMC")),
                ("remarks", models.CharField(blank=True, max_length=250, null=True, verbose_name="Equipment Remarks")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "current_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="current_unit_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical agse",
                "verbose_name_plural": "historical AGSE",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
