# Generated by Django 4.2.4 on 2025-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faults", "0002_alter_fault_corrective_action_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="aircraft",
            field=models.CharField(default="Unknown", max_length=40, verbose_name="A/C Serial Number"),
        ),
    ]
