# Generated by Django 4.2.4 on 2025-01-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faults", "0003_alter_fault_aircraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="aircraft",
            field=models.CharField(max_length=40, null=True, verbose_name="A/C Serial Number"),
        ),
    ]
