# Generated by Django 4.2.4 on 2025-01-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faults", "0004_alter_fault_aircraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faultaction",
            name="corrective_action",
            field=models.TextField(max_length=2048, null=True, verbose_name="Corrective Action"),
        ),
        migrations.AlterField(
            model_name="faultaction",
            name="fault_work_unit_code",
            field=models.CharField(max_length=24, null=True, verbose_name="Fault Work Unit Code"),
        ),
        migrations.AlterField(
            model_name="faultaction",
            name="maintenance_action",
            field=models.TextField(max_length=2048, null=True, verbose_name="Maintenance Action"),
        ),
    ]
