# Generated by Django 4.2.4 on 2025-01-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faults", "0005_alter_faultaction_corrective_action_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="maintainerfaultaction",
            constraint=models.UniqueConstraint(
                fields=("fault_action", "soldier"), name="unique_fault_action_maintainer"
            ),
        ),
    ]
