# Generated by Django 4.2.4 on 2025-01-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faults", "0006_maintainerfaultaction_unique_fault_action_maintainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="discovered_by_name",
            field=models.CharField(max_length=64, null=True, verbose_name="Discovered By Name"),
        ),
        migrations.AlterField(
            model_name="fault",
            name="remarks",
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name="Remarks"),
        ),
    ]
