# Generated by Django 4.2.4 on 2025-01-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0024_historicalsoldier_recieve_emails_and_more"),
        ("faults", "0007_alter_fault_discovered_by_name_alter_fault_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="faultaction",
            name="maintainers",
            field=models.ManyToManyField(through="faults.MaintainerFaultAction", to="personnel.soldier"),
        ),
        migrations.AlterField(
            model_name="fault",
            name="remarks",
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name="Remarks"),
        ),
    ]
