# Generated by Django 4.2.4 on 2025-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faults", "0008_faultaction_maintainers_alter_fault_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="faultaction",
            name="source",
            field=models.CharField(
                choices=[("CAMMS", "CAMMS"), ("GCSS-A", "GCSS-A")],
                default="CAMMS",
                max_length=10,
                verbose_name="Fault Action Source",
            ),
        ),
    ]
