# Generated by Django 4.2.2 on 2025-02-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0001_initial"),
        ("faults", "0009_faultaction_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="unit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="faults", to="units.unit"
            ),
        ),
    ]
