# Generated by Django 4.2.4 on 2025-03-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faults", "0010_alter_fault_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawFault",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("serial_number", models.CharField(blank=True, max_length=255, null=True)),
                ("uic", models.CharField(blank=True, max_length=255, null=True)),
                ("fault_discovered_by", models.CharField(blank=True, max_length=255, null=True)),
                ("edipi", models.CharField(blank=True, max_length=255, null=True)),
                ("status_code_value", models.CharField(blank=True, max_length=255, null=True)),
                ("system_code_value", models.CharField(blank=True, max_length=255, null=True)),
                ("when_discovered_code_value", models.CharField(blank=True, max_length=255, null=True)),
                ("how_recognized_code_value", models.CharField(blank=True, max_length=255, null=True)),
                ("malfunction_effect_code_value", models.CharField(blank=True, max_length=255, null=True)),
                ("failure_code_value", models.CharField(blank=True, max_length=255, null=True)),
                ("corrective_action_code_value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ti_maintenance_level_code_value",
                    models.CharField(
                        blank=True, db_column="TI_maintenance_level_code_value", max_length=255, null=True
                    ),
                ),
                ("discovery_date_time", models.DateTimeField(blank=True, null=True)),
                ("corrective_date_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.FloatField(blank=True, null=True)),
                ("remarks", models.CharField(blank=True, max_length=4086, null=True)),
                ("maintenance_delay", models.CharField(blank=True, max_length=255, null=True)),
                ("fault_work_unit_code", models.CharField(blank=True, max_length=255, null=True)),
                ("total_man_hours", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("fault_sync_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "raw_amap_faults",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RawFaultAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_13_1", models.CharField(blank=True, max_length=255, null=True)),
                ("id_13_2", models.CharField(blank=True, max_length=255, null=True)),
                ("discovery_date_time", models.DateTimeField(blank=True, null=True)),
                ("closed_date_time", models.DateTimeField(blank=True, null=True)),
                ("closed_by_dodid", models.CharField(blank=True, max_length=255, null=True)),
                ("maintenance_action", models.CharField(blank=True, max_length=2048, null=True)),
                ("corrective_action", models.CharField(blank=True, max_length=2048, null=True)),
                ("status_code_value", models.CharField(blank=True, max_length=255, null=True)),
                ("fault_work_unit_code", models.CharField(blank=True, max_length=255, null=True)),
                ("technical_inspector_dodid", models.CharField(blank=True, max_length=255, null=True)),
                ("maintenance_level_code_value", models.CharField(blank=True, max_length=255, null=True)),
                ("action_code_value", models.CharField(blank=True, max_length=255, null=True)),
                ("sequence_number", models.FloatField(blank=True, null=True)),
                ("personnel_dodid", models.CharField(blank=True, max_length=255, null=True)),
                ("man_hours", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("fault_action_sync_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "raw_amap_fault_actions",
                "managed": False,
            },
        ),
    ]
