# Generated by Django 4.2.4 on 2023-08-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_ictl_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject Area'),
        ),
    ]
