# Generated by Django 4.2.4 on 2023-08-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_subject_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=60, verbose_name='Task Title'),
        ),
    ]
