# Generated by Django 4.2.4 on 2023-08-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_ictl_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Task Number'),
        ),
    ]
