# Generated by Django 4.2.4 on 2023-08-28 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_ictl_ictl_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ictl',
        ),
        migrations.CreateModel(
            name='IctlTasks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique ID')),
                ('ictl', models.ForeignKey(db_column='ictl_id', on_delete=django.db.models.deletion.CASCADE, to='tasks.ictl')),
                ('task', models.ForeignKey(db_column='task_number', on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'verbose_name_plural': 'ictl tasks',
                'db_table': 'ictl_tasks',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='ictl',
            field=models.ManyToManyField(through='tasks.IctlTasks', to='tasks.ictl'),
        ),
    ]
