# Generated by Django 4.2.4 on 2023-08-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_sus_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sus_level',
        ),
    ]
