# Generated by Django 4.2.4 on 2024-02-01 16:29

import datetime

import django.db.models.deletion
from django.db import migrations, models

import tasks.model_utils.unit_task_upload_to


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0010_alter_login_user_id_alter_soldier_is_admin_and_more"),
        ("tasks", "0018_alter_ictl_proponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="ictl",
            name="date_published",
            field=models.DateField(default=datetime.date(2020, 10, 20), verbose_name="Date the ICTL was published"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="task_unit",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="unit_tasks",
                to="personnel.unit",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="unit_task_pdf",
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=tasks.model_utils.unit_task_upload_to.unit_task_file_name,
                verbose_name="Uploaded Task pdf file",
            ),
        ),
    ]
