# Generated by Django 4.2.4 on 2024-02-05 16:44

from django.db import migrations, models

import tasks.model_utils.unit_task_upload_to


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0019_ictl_date_published_task_unit_task_unit_task_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="unit_task_pdf",
            field=models.FileField(
                max_length=1024,
                null=True,
                upload_to=tasks.model_utils.unit_task_upload_to.unit_task_file_name,
                verbose_name="Uploaded Task pdf file",
            ),
        ),
    ]
