# Generated by Django 5.0.1 on 2024-08-09 19:10

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0016_historicalsoldier_historicalsoldierflag_and_more"),
        ("tasks", "0021_task_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalIctl",
            fields=[
                ("ictl_id", models.BigIntegerField(blank=True, db_index=True, verbose_name="Auto Unique Id")),
                ("ictl_title", models.CharField(max_length=75, verbose_name="ICTL Title")),
                ("date_published", models.DateField(verbose_name="Date the ICTL was published")),
                (
                    "proponent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USAACE", "US Army Aviation Center of Excellence"),
                            ("USAALS", "US Army Aviation Logistics School"),
                            ("Unit", "Unit Specific"),
                        ],
                        max_length=6,
                        null=True,
                        verbose_name="Propenent",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True, verbose_name="ICTL Status")),
                (
                    "skill_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SL1", "Skill Level 1"),
                            ("SL2", "Skill Level 2"),
                            ("SL3", "Skill Level 3"),
                            ("SL4", "Skill Level 4"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Skill Level",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(blank=True, max_length=240, null=True, verbose_name="Target Audience"),
                ),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="personnel.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ictl",
                "verbose_name_plural": "historical ictl",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMosIctls",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="Auto Unique ID")),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to="tasks.historicalictl"
                    ),
                ),
                (
                    "ictl",
                    models.ForeignKey(
                        blank=True,
                        db_column="ictl",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tasks.ictl",
                    ),
                ),
                (
                    "mos",
                    models.ForeignKey(
                        blank=True,
                        db_column="mos",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tasks.mos",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalMosIctls",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTask",
            fields=[
                ("task_number", models.CharField(db_index=True, max_length=20, verbose_name="Task Number")),
                ("task_title", models.CharField(max_length=240, verbose_name="Task Title")),
                ("pdf_url", models.URLField(blank=True, null=True, verbose_name="Task PDF Url")),
                ("unit_task_pdf", models.TextField(max_length=1024, null=True, verbose_name="Uploaded Task pdf file")),
                (
                    "training_location",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Training Location"),
                ),
                (
                    "frequency",
                    models.CharField(blank=True, max_length=30, null=True, verbose_name="Training Frequency"),
                ),
                ("subject_area", models.CharField(blank=True, max_length=100, null=True, verbose_name="Subject Area")),
                ("deleted", models.BooleanField(default=False)),
                ("history_user_id", models.CharField(max_length=255, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="task_unit",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="personnel.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical task",
                "verbose_name_plural": "historical tasks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalIctlTasks",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="Auto Unique ID")),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ictl",
                    models.ForeignKey(
                        blank=True,
                        db_column="ictl_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tasks.ictl",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        db_column="task_number",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tasks.task",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to="tasks.historicaltask"
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalIctlTasks",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
