# Generated by Django 4.2.4 on 2024-10-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0022_historicalictl_historicalmosictls_historicaltask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mos",
            name="mos_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("15B", "Aircraft Power Plant Repairer"),
                    ("15D", "Aircraft Powertrain Repairer"),
                    ("15E", "RQ-7 Unmanned Aircraft Systems Repairer"),
                    ("15F", "Aircraft Electrician"),
                    ("15G", "Aircraft Structural Repairer"),
                    ("15H", "Aircraft Pneudraulics Repairer"),
                    ("15M", "MQ-1 unmanned Aircraft Systems Repairer"),
                    ("15N", "Avionic Mechanic"),
                    ("15R", "AH-64 Attach Helicopter Repairer"),
                    ("15T", "UH-60 Utility Helicopter Repairer"),
                    ("15U", "CH-47 Cargo Helicopter Repairer"),
                    ("15Y", "AH-64 Armament/Electrical/Avionic Systems Repairer"),
                    ("15K", "Aircraft Components Repair Supervisor"),
                    ("15L", "Armament/Electrical/Avionic Repair Supervisor"),
                    ("15Z", "Aviation Senior Sergeant"),
                    ("94R", "Avionics and Survivability Equipment Repairer"),
                    ("94E", "Radio Equipment Repairer"),
                    ("B3", "UH-72A Lakota Utility Helicopter Repairer"),
                ],
                max_length=3,
                null=True,
                verbose_name="MOS Code",
            ),
        ),
    ]
