# Generated by Django 4.2.2 on 2025-02-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0001_initial"),
        ("tasks", "0024_alter_historicalictl_proponent_alter_ictl_proponent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalictl",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="task_unit",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="ictl",
            name="unit",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="units.unit"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                db_column="task_unit",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="unit_tasks",
                to="units.unit",
            ),
        ),
    ]
