import React from 'react';

import RefreshIcon from '@mui/icons-material/Refresh';
import SupportAgentIcon from '@mui/icons-material/SupportAgent';
import { Button, Container, Skeleton, Stack, Typography } from '@mui/material';

import { Links } from '@utils/links';

const ContainerBody: React.FC<{ children: React.ReactNode; label: string | undefined }> = ({ children, label }) => (
  <Container maxWidth={false} disableGutters sx={{ width: '100%', minHeight: '100%', py: 4, px: 3 }}>
    {label && (
      <Typography variant="h6" mb={3}>
        {label}
      </Typography>
    )}
    {children}
  </Container>
);

interface PmxGridItemTemplateProps<TData, TError> {
  dataHook?: {
    data?: TData;
    originalArgs?: unknown;
    currentData?: TData;
    error?: TError;
    requestId?: string;
    endpointName?: string;
    startedTimeStamp?: number;
    fulfilledTimeStamp?: number;

    // Derived request status booleans
    isUninitialized?: boolean;
    isLoading?: boolean;
    isFetching?: boolean;
    isSuccess?: boolean;
    isError?: boolean;
    refetch?: () => void;
  };
  RenderComponent?: React.ComponentType<{ data: TData }>;
  FallbackComponent?: React.ComponentType<{
    uic: string;
    start_date: string;
    end_date: string;
    validDateRange: boolean;
  }>;
  FallbackComponentProps?: { uic: string; start_date: string; end_date: string; validDateRange: boolean };
  label?: string;
}

/**
 * Props for the PmxGridItemTemplate component.
 *
 * @template TData - The type of the data returned by the query.
 * @template TError - The type of the error returned by the query.
 *
 * @property {Object} [dataHook] - The hook data and metadata.
 * @property {TData} [dataHook.data] - The data returned by the query.
 * @property {unknown} [dataHook.originalArgs] - Arguments passed to the query.
 * @property {TData} [dataHook.currentData] - The latest returned result for the current hook arg, if present.
 * @property {TError} [dataHook.error] - Error result if present.
 * @property {string} [dataHook.requestId] - A string generated by RTK Query.
 * @property {string} [dataHook.endpointName] - The name of the given endpoint for the query.
 * @property {number} [dataHook.startedTimeStamp] - Timestamp for when the query was initiated.
 * @property {number} [dataHook.fulfilledTimeStamp] - Timestamp for when the query was completed.
 * @property {boolean} [dataHook.isUninitialized] - Query has not started yet.
 * @property {boolean} [dataHook.isLoading] - Query is currently loading for the first time. No data yet.
 * @property {boolean} [dataHook.isFetching] - Query is currently fetching, but might have data from an earlier request.
 * @property {boolean} [dataHook.isSuccess] - Query has data from a successful load.
 * @property {boolean} [dataHook.isError] - Query is currently in an "error" state.
 * @property {() => void} [props.dataHook.refetch] - Function to refetch the data.
 * @property {React.ComponentType<{ data: TData }>} RenderComponent - The component to render with the data.
 * @property {string} [label] - An optional label for the component.
 */

const PmxGridItemTemplate = <TData, TError>({
  dataHook,
  RenderComponent,
  FallbackComponent,
  FallbackComponentProps,
  label,
}: PmxGridItemTemplateProps<TData, TError>) => {
  if (!dataHook && FallbackComponent && FallbackComponentProps) {
    return (
      <ContainerBody label={label}>
        {
          <FallbackComponent
            uic={FallbackComponentProps.uic}
            start_date={FallbackComponentProps.start_date}
            end_date={FallbackComponentProps.end_date}
            validDateRange={FallbackComponentProps.validDateRange}
          />
        }
      </ContainerBody>
    );
  }

  const { data, isError, isFetching, isUninitialized, refetch } = dataHook || {};

  if (isUninitialized || isFetching) {
    return <Skeleton data-testid="skeleton-loading" variant="rectangular" width="100%" height="100%" />;
  }

  if (isError) {
    return (
      <ContainerBody label="Component Failure Predictions">
        <Typography variant="body1">
          Issues loading data. <br />
          Try refreshing, or contact support if the issue persists.
        </Typography>
        <Stack direction="row" spacing={4} mt={4}>
          <Button
            component="a"
            href={Links.SUPPORT}
            rel="noopener noreferrer"
            target="_blank"
            variant="outlined"
            startIcon={<SupportAgentIcon />}
          >
            <Typography variant="body1" mb={'-3px'}>
              Contact
            </Typography>
          </Button>
          <Button variant="contained" startIcon={<RefreshIcon />} onClick={refetch}>
            <Typography variant="body1" mb={'-3px'}>
              Refresh
            </Typography>
          </Button>
        </Stack>
      </ContainerBody>
    );
  }

  return RenderComponent ? (
    <ContainerBody label={label}>{data && <RenderComponent data={data} />}</ContainerBody>
  ) : null;
};

export default PmxGridItemTemplate;
