# Generated by Django 4.2.2 on 2024-02-01 02:23

from django.db import migrations, models
import django.db.models.deletion
import reports.model_utils.dsr_upload


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auto_dsr", "0020_unit_nick_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStatusReport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "generated_at",
                    models.DateTimeField(verbose_name="The Timestamp when this report was generated (UTC)"),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        upload_to=reports.model_utils.dsr_upload.dsr_upload_to,
                        verbose_name="Uploaded DA 4856 File",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_dodid", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Status Report",
                "verbose_name_plural": "Daily Status Reports",
                "db_table": "reports_daily_status_report",
            },
        ),
    ]
