# Generated by Django 4.2.2 on 2024-02-09 16:10

from django.db import migrations, models
import reports.model_utils.dsr_upload


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailystatusreport",
            name="document",
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=reports.model_utils.dsr_upload.dsr_upload_to,
                verbose_name="Griffin Generated DSR document",
            ),
        ),
    ]
