# Generated by Django 4.2.2 on 2024-02-16 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_alter_dailystatusreport_document"),
        ("reports", "0002_dailystatusreport_csv"),
    ]

    operations = []
