deployment_level: 'PRODUCTION' # DEVELOPMENT, STAGING, PRODUCTION
security_group: 'ai2c' # dami_im, up, test_security_group... full list at: cdso/cdso/catalog/security_groups
organization: 'ai2c' # Set to your organization name
sdd_project_id: 6746 # uncomment and set if the sdd is in a different project

.semgrep:tags:
  tags: [cdso-large]

frontend:
  version: 0.0.1
  project_type: 'container'
  dockerfile_folder: '.'
  container_lifespan: 'EPHEMERAL'
  connection_context: 'INTERNAL'
  mitigations:
    - CVE-2025-53859: >-
        Description: NGINX Open Source and NGINX Plus have a vulnerability in the ngx_mail_smtp_module that might
        allow an unauthenticated attacker to over-read NGINX SMTP authentication process memory; as a result, the server
        side may leak arbitrary bytes sent in a request to the authentication server. This issue happens during the NGINX
        SMTP authentication process and requires the attacker to make preparations against the target system to extract the
        leaked data. The issue affects NGINX only if (1) it is built with the ngx_mail_smtp_module, (2) the smtp_auth
        directive is configured with method "none," and (3) the authentication server returns the "Auth-Wait" response
        header. Mitigation: This vulnerability is mitigated because the ngx_mail_smtp_module is not utilized so the conditions
        for the issue are not met.
    - CVE-2026-22184: >-
        DESCRIPTION: zlib versions up to and including 1.3.1.2 include a global buffer overflow in the untgz utility
        located under contrib/untgz. The vulnerability is limited to the standalone demonstration utility and does not
        affect the core zlib compression library. The flaw occurs when a user executes the untgz command with an excessively
        long archive name supplied via the command line, leading to an out-of-bounds write in a fixed-size global buffer.
        MITIGATION: This is a false positive.  Alpine linux is using the latest version of zlib and our application does not use
        the zlib library on the OS.
    - CVE-2026-27171: >-
        DESCRIPTION: zlib before 1.3.2 allows CPU consumption via crc32_combine64 and crc32_combine_gen64 because
        x2nmodp can do right shifts within a loop that has no termination condition.
        MITIGATION: This is a false positive.  Alpine linux is using the latest version of zlib and our application does not use
        the zlib library on the OS.
  semgrep:
    exclusions:
      - 'app.rules.community.typescript.react.portability.i18next.jsx-not-internationalized'
      - 'app.rules.community.typescript.react.portability.i18next.jsx-label-not-i18n'
      - 'app.rules.community.typescript.react.best-practice.react-props-spreading'
      - 'app.rules.community.javascript.lang.best-practice.javascript-alert'
      - 'app.rules.community.javascript.lang.security.html-in-template-string'
      - 'app.rules.community.json.npm.security.package-dependencies-check'
    ignore:
      - 'vitest/'
      - '.husky/'
      - '.sonarlint/'
      - '.vscode/'
      - 'docs/'
      - 'public/'
      - '__tests__/'
  trufflehog:
    excluded_files:
      - "vitest/*"
      - "coverage/*"
      - "src/pmx-mui/icons/AmapIcon.tsx"
  zap:
    mitigations:
      ZAP_10096: 'Skipping ZAP alert (10096) - Timestamp Disclosure - False positive for a timestamp found.'
      ZAP_10109: 'Skipping ZAP alert (10109) - Modern Web Application - Based on the Alert Info, this is not a finding.'
      ZAP_10015: 'Skipping ZAP alert (10015) - The cache-control header has not been set properly or is missing, allowing the browser and proxies to cache content. - Based on the Alert Info, this is not a finding.'
      ZAP_10104: 'Skipping ZAP alert (10104) - User Agent Fuzzer - Based on the Alert Info, this is not a finding.'
      ZAP_10027: 'Skipping ZAP alert (10027) - Information Disclosure - Suspicious Comments - Comment found was not provided in our code but included module.'
      ZAP_10055_6: 'Skipping ZAP alert (10055-6) - Content Security Policy (CSP): The presence of inline styles in our application does not present a security risk, as these styles are static and do not involve any user-supplied content or executable code that could lead to injection attacks. Therefore, this alert is considered a low risk and will be skipped'
      ZAP_40035: 'Skipping ZAP alert (40035) - Hidden File Found - False Positive.  With SPA apps, if a file is not found it redirects to an error page.  Thus zap says it found hidden file while there are none.'
