# Project Defintion
sonar.sources=src

# Coverage Configuration
sonar.coverage.exclusions=**/*.test.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.xunit.reportPath=junit-report.xml