# Generated by Django 4.2.2 on 2024-02-05 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auto_dsr", "0020_unit_nick_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawForscomMonthlyForecast",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("unit_type", models.CharField(blank=True, max_length=4, null=True, verbose_name="Unit Type")),
                ("model", models.CharField(max_length=16, verbose_name="Aircraft Model")),
                ("forecasted_hours", models.IntegerField(verbose_name="Hours Forecasted")),
                ("reporting_month", models.DateField(verbose_name="Reporting Month")),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit"
                    ),
                ),
            ],
            options={
                "db_table": "fhp_raw_forscom_monthly_forecast",
            },
        ),
        migrations.CreateModel(
            name="RawForscomAnnual",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("unit_type", models.CharField(blank=True, max_length=4, null=True, verbose_name="Unit Type")),
                ("model", models.CharField(max_length=16, verbose_name="Aircraft Model")),
                ("requested_hours", models.IntegerField(verbose_name="Unit Requested hours")),
                (
                    "fiscal_year",
                    models.IntegerField(verbose_name="The year the flying hours were requested for in format: YYYY"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit"
                    ),
                ),
            ],
            options={
                "db_table": "fhp_raw_forscom_annual",
            },
        ),
        migrations.CreateModel(
            name="RawForscomCostFactor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("unit_type", models.CharField(blank=True, max_length=4, null=True, verbose_name="Unit Type")),
                ("model", models.CharField(max_length=16, verbose_name="Aircraft Model")),
                ("cost_factor", models.IntegerField(verbose_name="Cost Factor")),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit"
                    ),
                ),
                (
                    "fiscal_year",
                    models.IntegerField(
                        default=2024, verbose_name="The year the flying hours were requested for in format: YYYY"
                    ),
                ),
            ],
            options={
                "db_table": "fhp_raw_forscom_cost_factor",
            },
        ),
        migrations.CreateModel(
            name="MonthlyProjection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("model", models.CharField(max_length=16, verbose_name="Aircraft Model")),
                ("reporting_month", models.DateField(verbose_name="The last day of the reporting period in question")),
                (
                    "projected_hours",
                    models.IntegerField(verbose_name="Hours projected to be flown during the given period"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.PROTECT, to="auto_dsr.unit"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="monthlyprojection",
            constraint=models.UniqueConstraint(
                fields=("unit", "model", "reporting_month"), name="unit_monthly_projections_per_mds"
            ),
        ),
        migrations.AlterField(
            model_name="monthlyprojection",
            name="projected_hours",
            field=models.FloatField(verbose_name="Hours projected to be flown during the given period"),
        ),
        migrations.CreateModel(
            name="MonthlyPrediction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("reporting_month", models.DateField(verbose_name="The last day of the reporting period")),
                (
                    "predicted_hours",
                    models.FloatField(verbose_name="Hours predicted to be flown during the given period"),
                ),
                (
                    "model",
                    models.CharField(max_length=64, verbose_name="The name of the model that made the prediction"),
                ),
                ("prediction_date", models.DateField(verbose_name="The day the predictions were made")),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="rawforscomcostfactor",
            name="fiscal_year",
            field=models.IntegerField(verbose_name="The fiscal year the cost factor was estimated for: YYYY"),
        ),
        migrations.AlterField(
            model_name="rawforscommonthlyforecast",
            name="reporting_month",
            field=models.DateField(verbose_name="Final Day in Reporting Month"),
        ),
        migrations.AddConstraint(
            model_name="monthlyprediction",
            constraint=models.UniqueConstraint(
                fields=("unit", "model", "reporting_month"), name="unit_monthly_predictions_per_mds"
            ),
        ),
        migrations.AlterModelTable(
            name="monthlyprediction",
            table="fhp_monthly_prediction",
        ),
        migrations.AlterModelTable(
            name="monthlyprojection",
            table="fhp_monthly_projection",
        ),
        migrations.AddConstraint(
            model_name="rawforscomannual",
            constraint=models.UniqueConstraint(
                fields=("unit", "model", "fiscal_year"), name="unit_annual_projection_per_mds"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawforscomcostfactor",
            constraint=models.UniqueConstraint(
                fields=("unit", "model", "fiscal_year"), name="unit_annual_cost_factor_per_mds"
            ),
        ),
        migrations.AddConstraint(
            model_name="rawforscommonthlyforecast",
            constraint=models.UniqueConstraint(
                fields=("unit", "model", "reporting_month"), name="raw_unit_monthly_projections_per_mds"
            ),
        ),
    ]
