# Generated by Django 4.2.2 on 2024-05-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0024_rename_user_id_usersetting_user_and_more'),
        ('fhp', '0007_remove_monthlyprediction_unit_monthly_predictions_per_mds_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawForscomAnnual',
            new_name='RawAnnualProjection',
        ),
        migrations.RenameModel(
            old_name='RawForscomCostFactor',
            new_name='RawCostFactor',
        ),
        migrations.RenameModel(
            old_name='RawForscomMonthlyForecast',
            new_name='RawMonthlyForecast',
        ),
        migrations.AlterModelTable(
            name='rawannualprojection',
            table='fhp_raw_annual_projection',
        ),
        migrations.AlterModelTable(
            name='rawcostfactor',
            table='fhp_raw_cost_factor',
        ),
        migrations.AlterModelTable(
            name='rawmonthlyforecast',
            table='fhp_raw_monthly_forecast',
        ),
    ]
