# Generated by Django 4.2.2 on 2024-05-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhp', '0009_rawannualprojection_source_rawcostfactor_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcostfactor',
            name='cost_factor',
            field=models.FloatField(verbose_name='Cost Factor'),
        ),
    ]
