# Generated by Django 4.2.2 on 2023-08-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_dsr', '0014_userrequest_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGSE',
            fields=[
                ('equipment_number', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Equipment Number')),
                ('lin', models.CharField(max_length=12, verbose_name='Line Item Number')),
                ('serial_number', models.CharField(max_length=32, verbose_name='Serial Number')),
                ('condition', models.CharField(choices=[('FMC', 'Fully Mission Capable'), ('PMC', 'Partially Mission Capable'), ('PMCM', 'Partially Mission Capable - Maintenance'), ('PMCS', 'Partially Mission Capable - Sustainment'), ('NMC', 'Non Mission Capable'), ('NMCS', 'Non Mission Capable - Supply'), ('NMCM', 'Non Mission Capable - Maintenance'), ('FIELD', 'Field'), ('SUST', 'Sustainment'), ('DADE', 'Department of the Army Directed Event'), ('UNK', 'Unknown')], default='UNK', max_length=15, null=True, verbose_name='Maintenance Status (FMC, NMC)')),
                ('nomenclature', models.CharField(max_length=64, verbose_name='Equipment Nomenclature')),
                ('display_name', models.CharField(max_length=24, verbose_name='Equipment Display Name')),
                ('earliest_nmc_start', models.DateField(blank=True, null=True, verbose_name='Starting date of NMC Status')),
                ('model', models.CharField(max_length=24, null=True, verbose_name='Equipment Model')),
                ('days_nmc', models.FloatField(blank=True, null=True, verbose_name='Days NMC')),
                ('remarks', models.CharField(blank=True, max_length=250, null=True, verbose_name='Equipment Remarks')),
            ],
            options={
                'verbose_name_plural': 'agse',
                'db_table': 'agse',
            },
        ),
        migrations.CreateModel(
            name='UnitAGSE',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique Id')),
                ('equipment_number', models.ForeignKey(db_column='equipment_number', on_delete=django.db.models.deletion.CASCADE, to='agse.agse')),
                ('uic', models.ForeignKey(db_column='uic', on_delete=django.db.models.deletion.CASCADE, to='auto_dsr.unit')),
            ],
            options={
                'verbose_name_plural': 'unit agse',
                'db_table': 'unit_agse',
            },
        ),
        migrations.AddField(
            model_name='agse',
            name='uic',
            field=models.ManyToManyField(through='agse.UnitAGSE', to='auto_dsr.unit'),
        ),
        migrations.CreateModel(
            name='AgseEdits',
            fields=[
                ('equipment_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agse.agse')),
                ('lock_type', models.CharField(choices=[('PERM', 'Permanent'), ('UGSRE', 'Until GCSS-A Status Reflects Edit'), ('DEL', 'Delete Lock (revert to GCSS Status')], default='UGSRE', max_length=15, verbose_name='Lock Type')),
                ('date_locked', models.DateField(blank=True, null=True, verbose_name='Date Lock Entered')),
                ('entered_by', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_dsr.user')),
            ],
            options={
                'verbose_name_plural': 'agse edits',
                'db_table': 'agse_edits',
            },
        ),
    ]
