# Generated by Django 4.2.2 on 2023-09-21 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0017_unit_child_uics_unit_parent_uics_and_more'),
        ('agse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agse',
            options={'verbose_name_plural': 'AGSE'},
        ),
        migrations.AlterModelOptions(
            name='agseedits',
            options={'verbose_name_plural': 'AGSE Edits'},
        ),
        migrations.AlterModelOptions(
            name='unitagse',
            options={'verbose_name_plural': 'Unit AGSE'},
        ),
        migrations.RenameField(
            model_name='agse',
            old_name='uic',
            new_name='tracked_by_unit',
        ),
        migrations.RenameField(
            model_name='unitagse',
            old_name='equipment_number',
            new_name='agse',
        ),
        migrations.RenameField(
            model_name='unitagse',
            old_name='uic',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='agse',
            name='current_unit',
            field=models.ForeignKey(db_column='current_unit_uic', default='WDARFF', on_delete=django.db.models.deletion.PROTECT, related_name='currently_assigned_agse', to='auto_dsr.unit'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='unitagse',
            constraint=models.UniqueConstraint(fields=('agse', 'unit'), name='agse_in_unit'),
        ),
    ]
