# Generated by Django 4.2.2 on 2024-06-29 19:54

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0026_auto_20240610_0957"),
        ("agse", "0003_historicalagse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalagse",
            name="history_user",
        ),
        migrations.AddField(
            model_name="historicalagse",
            name="history_user_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalUnitAGSE",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="Auto Unique Id")),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "agse",
                    models.ForeignKey(
                        blank=True,
                        db_column="equipment_number",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="agse.agse",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to="agse.historicalagse"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalUnitAGSE",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
