# Generated by Django 4.2.2 on 2025-04-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0038_rawsynctimestamp"),
        ("agse", "0006_alter_agse_field_sync_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agse",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_column="location_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auto_dsr.location",
            ),
        ),
        migrations.AddField(
            model_name="historicalagse",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_column="location_id",
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="auto_dsr.location",
            ),
        ),
        migrations.AlterField(
            model_name="agse",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FMC", "Fully Mission Capable"),
                    ("PMC", "Partially Mission Capable"),
                    ("PMCM", "Partially Mission Capable - Maintenance"),
                    ("PMCS", "Partially Mission Capable - Sustainment"),
                    ("NMC", "Non Mission Capable"),
                    ("NMCS", "Non Mission Capable - Supply"),
                    ("NMCM", "Non Mission Capable - Maintenance"),
                    ("FIELD", "Field"),
                    ("SUST", "Sustainment"),
                    ("DADE", "Department of the Army Directed Event"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=15,
                verbose_name="Maintenance Status (FMC, NMC)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalagse",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FMC", "Fully Mission Capable"),
                    ("PMC", "Partially Mission Capable"),
                    ("PMCM", "Partially Mission Capable - Maintenance"),
                    ("PMCS", "Partially Mission Capable - Sustainment"),
                    ("NMC", "Non Mission Capable"),
                    ("NMCS", "Non Mission Capable - Supply"),
                    ("NMCM", "Non Mission Capable - Maintenance"),
                    ("FIELD", "Field"),
                    ("SUST", "Sustainment"),
                    ("DADE", "Department of the Army Directed Event"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=15,
                verbose_name="Maintenance Status (FMC, NMC)",
            ),
        ),
    ]
