# Generated by Django 4.2.21 on 2025-08-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agse", "0007_agse_location_historicalagse_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agse",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FMC", "Fully Mission Capable"),
                    ("PMC", "Partially Mission Capable"),
                    ("PMCM", "Partially Mission Capable - Maintenance"),
                    ("PMCS", "Partially Mission Capable - Sustainment"),
                    ("NMC", "Non Mission Capable"),
                    ("NMCS", "Non Mission Capable - Supply"),
                    ("NMCM", "Non Mission Capable - Maintenance"),
                    ("FIELD", "Field"),
                    ("SUST", "Sustainment"),
                    ("DADE", "Department of the Army Directed Event"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=15,
                null=True,
                verbose_name="Maintenance Status (FMC, NMC)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalagse",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FMC", "Fully Mission Capable"),
                    ("PMC", "Partially Mission Capable"),
                    ("PMCM", "Partially Mission Capable - Maintenance"),
                    ("PMCS", "Partially Mission Capable - Sustainment"),
                    ("NMC", "Non Mission Capable"),
                    ("NMCS", "Non Mission Capable - Supply"),
                    ("NMCM", "Non Mission Capable - Maintenance"),
                    ("FIELD", "Field"),
                    ("SUST", "Sustainment"),
                    ("DADE", "Department of the Army Directed Event"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=15,
                null=True,
                verbose_name="Maintenance Status (FMC, NMC)",
            ),
        ),
    ]
