# Generated by Django 4.2.4 on 2023-08-17 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DA_7817',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Auto Unique ID')),
                ('date_time', models.DateTimeField(verbose_name='Date and time of record entry')),
                ('event_type', models.CharField(choices=[('Training', 'Training Event'), ('Evaluation', 'Evaluation Event'), ('PCS/ETS', 'PCS or ETS Event'), ('Award', 'Award Event'), ('Other', 'Other Event')], default='Other', max_length=15, verbose_name='Event Type')),
                ('training_type', models.CharField(blank=True, choices=[('Advanced Composites', 'Advanced Composites Training'), ('Weight and Balance', 'Aircraft Weight and Balance Software Training'), ('Oil Analysis', 'Army Oil Analysis Training'), ('Corpus Christi Deopt', 'Corpus Christi Army Depot Training'), ('Corrosion Monitor', 'Corrosion Monitor Training'), ('Defence Acquisition University', 'Defense Acquisition University'), ('T700 Engine', 'T700 Engine Training'), ('Logistics Assistance Representative University', 'Logistics Assistance Representative University'), ('Non-Destructive Testing Training', 'Non-Destructive Testing Training'), ('Senior Maintainer Course', 'Senior Maintainer Course'), ('Test, Measurement, and Diagnostic', 'Test, Measurement, and Diagnostic Equipment Training'), ('Credentialing Programs', 'Credentialing Programs'), ('Other', 'Other Training Type')], max_length=50, null=True, verbose_name='Training Type')),
                ('award_type', models.CharField(blank=True, choices=[('AAM', 'Army Achievement Medal'), ('ARCOM', 'Army Accomodation Medal'), ('Other', 'Other Medal')], max_length=20, null=True, verbose_name='Award Type')),
                ('total_mx_hours', models.FloatField(default=0.0, verbose_name='Total Maintenance Hours')),
                ('comment', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Entry Comment')),
                ('maintenance_level', models.CharField(blank=True, choices=[('ML0', 'Maintainer Level 0 - Apprentice'), ('ML1', 'Maintainer Level 1 - Journeyman'), ('ML2', 'Maintainer Level 2 - Repairer'), ('ML3', 'Maintainer Level 3 - Senior Repairer'), ('ML4', 'Maintainer Level 4 - Master Repairer')], max_length=3, null=True, verbose_name='Maintenance Level')),
                ('gainingUnit', models.ForeignKey(blank=True, db_column='gaining_uic', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gaining_uic', to='personnel.unit')),
                ('soldier', models.ForeignKey(db_column='soldier_id', on_delete=django.db.models.deletion.CASCADE, to='personnel.soldier')),
                ('uic', models.ForeignKey(db_column='unit_uic', on_delete=django.db.models.deletion.DO_NOTHING, related_name='owning_uic', to='personnel.unit')),
            ],
            options={
                'verbose_name': 'DA 7817',
                'verbose_name_plural': 'DA 7817s',
                'db_table': 'da_7817',
            },
        ),
    ]
