# Generated by Django 4.2.4 on 2023-08-30 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_soldier_pfc_dor_soldier_pv2_dor_soldier_sfc_dor_and_more'),
        ('forms', '0002_da_7817_evaluation_type_da_7817_go_nogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='da_7817',
            name='recorded_by',
            field=models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recorded_by', to='personnel.soldier'),
        ),
        migrations.AlterField(
            model_name='da_7817',
            name='award_type',
            field=models.CharField(blank=True, choices=[('AAM', 'Army Achievement Medal'), ('ARCOM', 'Army Commendation Medal'), ('AGCM', 'Good Conduct Medal'), ('DSC', 'Distinguished Service Cross'), ('DDSM', 'Defense Distinguished Service Medal'), ('DSM', 'Distinguished Service Medal'), ('SSTAR', 'Silver Star'), ('DSSM', 'Defense Superior Service Medal'), ('LOM', 'Legion of Merit'), ('DFC', 'Distinguished Flying Cross'), ('SM', "Soldier's Medal"), ('BSM', 'Bronze Star Medal'), ('PH', 'Purple Heart'), ('DMSM', 'Defense Meritorious Service Medal'), ('MSM', 'Meritorious Service Medal'), ('AM', 'Air Medal'), ('JSCM', 'Joint Service Commendation Medal'), ('JSAM', 'Joint Service Achievement Medal'), ('POWM', 'Prisoner of War Medal'), ('ARCAM', 'Army Reserve Component Achievement Medal'), ('AOM', 'Army of Occupation Medal'), ('NDSM', 'National Defense Service Medal'), ('AFEM', 'Armed Forces Expeditionary Medal'), ('ASR', 'Army Service Ribbon'), ('AFSM', 'Armed Forces Service Medal'), ('AOSR', 'Army Overseas Service Ribbon'), ('AFRM', 'Armed Forces Reserve Medal'), ('NPDR', 'NCO Professional Development Ribbon'), ('NM', 'Nato Medal'), ('UNM', 'United Nations Medal'), ('ARCOTR', 'Army Reserve Component Overseas Training Ribbon'), ('Other', 'Other Award')], max_length=20, null=True, verbose_name='Award Type'),
        ),
        migrations.AlterField(
            model_name='da_7817',
            name='soldier',
            field=models.ForeignKey(db_column='soldier_id', on_delete=django.db.models.deletion.CASCADE, related_name='soldier_id', to='personnel.soldier'),
        ),
    ]
