# Generated by Django 4.2.4 on 2023-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_da_7817_award_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='da_7817',
            name='date_time',
            field=models.DateField(verbose_name='Date of event'),
        ),
    ]
