# Generated by Django 4.2.4 on 2023-11-30 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_da_4856_da_7817_da_7817_uniqueness_da_4856_soldier_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='da_7817',
            name='da_7817_uniqueness',
        ),
        migrations.AddField(
            model_name='da_4856',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Counseling'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='da_7817',
            constraint=models.UniqueConstraint(fields=('soldier', 'date_time', 'event_type', 'recorded_by', 'recorded_by_legacy', 'go_nogo'), name='da_7817_uniqueness'),
        ),
    ]
