# Generated by Django 4.2.4 on 2023-12-02 20:22

import django.db.models.deletion
from django.db import migrations, models

import forms.model_utils.counseling_upload_to
import utils.storage.azure.carmy_azure_storage


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0009_alter_unit_echelon_alter_userrequest_access_level_and_more"),
        ("forms", "0008_remove_da_7817_da_7817_uniqueness_da_4856_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="da_4856",
            name="document",
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                storage=utils.storage.azure.carmy_azure_storage.AzureContainerStorage,
                upload_to=forms.model_utils.counseling_upload_to.counseling_file_name,
                verbose_name="Uploaded DA 4856 File",
            ),
        ),
        migrations.AlterField(
            model_name="da_4856",
            name="soldier",
            field=models.ForeignKey(
                db_column="soldier_dod_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counselings",
                to="personnel.soldier",
            ),
        ),
        migrations.AlterField(
            model_name="da_4856",
            name="title",
            field=models.CharField(max_length=128, verbose_name="DA 4856 Title"),
        ),
        migrations.AlterModelTable(
            name="da_4856",
            table="forms_da_4856",
        ),
    ]
