# Generated by Django 4.2.4 on 2023-12-02 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0010_alter_login_user_id_alter_soldier_is_admin_and_more"),
        ("forms", "0009_alter_da_4856_document_alter_da_4856_soldier_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="da_7817", old_name="gainingUnit", new_name="gaining_unit"),
        migrations.AlterField(
            model_name="da_7817",
            name="gaining_unit",
            field=models.ForeignKey(
                blank=True,
                db_column="gaining_unit_uic",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="soldier_pcs_records",
                to="personnel.unit",
            ),
        ),
        migrations.AlterField(
            model_name="da_7817",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                db_column="recorded_by",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="recorded_events",
                to="personnel.soldier",
            ),
        ),
        migrations.AlterField(
            model_name="da_7817",
            name="soldier",
            field=models.ForeignKey(
                db_column="soldier_dod_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_records",
                to="personnel.soldier",
            ),
        ),
        migrations.AlterField(
            model_name="da_7817",
            name="uic",
            field=models.ForeignKey(
                db_column="unit_uic",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="soldier_event_records",
                to="personnel.unit",
            ),
        ),
        migrations.AlterModelTable(
            name="da_7817",
            table="forms_da_7817",
        ),
    ]
