# Generated by Django 4.2.4 on 2023-12-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0011_remove_da_7817_da_7817_uniqueness_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="da_7817",
            name="event_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
