# Generated by Django 4.2.4 on 2024-01-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0018_alter_ictl_proponent"),
        ("forms", "0012_da_7817_event_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTasks",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique ID")),
                (
                    "event",
                    models.ForeignKey(
                        db_column="da7817", on_delete=django.db.models.deletion.CASCADE, to="forms.da_7817"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(db_column="task", on_delete=django.db.models.deletion.CASCADE, to="tasks.task"),
                ),
            ],
            options={
                "verbose_name_plural": "EventTasks",
            },
        ),
        migrations.AddField(
            model_name="da_7817",
            name="event_tasks",
            field=models.ManyToManyField(through="forms.EventTasks", to="tasks.task"),
        ),
    ]
