# Generated by Django 4.2.4 on 2024-02-01 16:29

from django.db import migrations, models

import forms.model_utils.counseling_upload_to


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0013_eventtasks_da_7817_event_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="da_4856",
            name="document",
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=forms.model_utils.counseling_upload_to.counseling_file_name,
                verbose_name="Uploaded DA 4856 File",
            ),
        ),
    ]
