# Generated by Django 4.2.4 on 2024-04-17 19:20

import django.db.models.deletion
from django.db import migrations, models

import forms.model_utils.supporting_document_upload_to


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0012_soldier_birth_month_soldier_dod_email"),
        ("forms", "0015_apicalllogging"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportingDocumentType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique ID")),
                ("type", models.CharField(max_length=32, verbose_name="The name of the Supporting Document Type")),
            ],
            options={
                "verbose_name": "Supporting Document Type",
                "verbose_name_plural": "Supporting Document Types",
                "db_table": "supporting_document_type",
            },
        ),
        migrations.CreateModel(
            name="SupportingDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique ID")),
                ("upload_date", models.DateField(verbose_name="Upload Date of Supporting Document")),
                ("document_date", models.DateField(verbose_name="Date on the Supporting Document")),
                ("document_title", models.CharField(max_length=128, verbose_name="Supporting Document Title")),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        upload_to=forms.model_utils.supporting_document_upload_to.supporting_document_file_name,
                        verbose_name="Uploaded Supporting Document File",
                    ),
                ),
                (
                    "visible_to_user",
                    models.BooleanField(
                        default=True, verbose_name="If this Supporting Document is visible or 'deleted' by the user."
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="supporting_document_type_id",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supporting_document_type",
                        to="forms.supportingdocumenttype",
                        verbose_name="Supporting Document Type",
                    ),
                ),
                (
                    "related_event",
                    models.ForeignKey(
                        blank=True,
                        db_column="da7817_id",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_event_id",
                        to="forms.da_7817",
                    ),
                ),
                (
                    "soldier",
                    models.ForeignKey(
                        db_column="soldier_dod_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_doc_for_soldier",
                        to="personnel.soldier",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="uploaded_by_soldier_dod_id",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supporting_doc_uploaded_by",
                        to="personnel.soldier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supporting Document",
                "verbose_name_plural": "Supporting Documents",
                "db_table": "forms_supporting_document",
            },
        ),
    ]
