# Generated by Django 4.2.4 on 2024-05-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0018_da_7817_tcs_location_alter_da_7817_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="da_4856",
            name="visible_to_user",
            field=models.BooleanField(
                default=True, verbose_name="If this DA 4856 is currently visible or 'deleted' by the user."
            ),
        ),
    ]
