# Generated by Django 4.2.2 on 2024-07-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0021_alter_da_7817_award_type_alter_da_7817_training_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="da_7817",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Training", "Training Event"),
                    ("Evaluation", "Evaluation Event"),
                    ("PCS/ETS", "PCS or ETS Event"),
                    ("TCS", "TCS Event"),
                    ("In-Unit Transfer", "In-Unit Transfer Event"),
                    ("Award", "Award Event"),
                    ("Records Review", "Records Review Event"),
                    ("Other", "Other Event"),
                ],
                default="Other",
                max_length=16,
                verbose_name="Event Type",
            ),
        ),
    ]
