# Generated by Django 4.2.4 on 2024-07-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0022_alter_da_7817_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="da_7817",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("Training", "Training Event"),
                    ("Evaluation", "Evaluation Event"),
                    ("PCS/ETS", "PCS or ETS Event"),
                    ("TCS", "TCS Event"),
                    ("In-Unit Transfer", "In-Unit Transfer Event"),
                    ("LAO", "Local Area Orientation Event"),
                    ("Award", "Award Event"),
                    ("Records Review", "Records Review Event"),
                    ("Other", "Other Event"),
                ],
                default="Other",
                max_length=16,
                verbose_name="Event Type",
            ),
        ),
        migrations.AlterField(
            model_name="da_7817",
            name="training_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Advanced Composites", "Advanced Composites Training"),
                    ("Weight and Balance", "Aircraft Weight and Balance Software Training"),
                    ("Oil Analysis", "Army Oil Analysis Training"),
                    ("Corpus Christi Depot", "Corpus Christi Army Depot Training"),
                    ("Corrosion Monitor", "Corrosion Monitor Training"),
                    ("Defence Acquisition University", "Defense Acquisition University"),
                    ("T700 Engine", "T700 Engine Training"),
                    (
                        "Logistics Assistance Representative University",
                        "Logistics Assistance Representative University",
                    ),
                    ("Non-Destructive Testing Training", "Non-Destructive Testing Training"),
                    ("Senior Maintainer Course", "Senior Maintainer Course"),
                    ("Test, Measurement, and Diagnostic", "Test, Measurement, and Diagnostic Equipment Training"),
                    ("Credentialing Programs", "Credentialing Programs"),
                    ("Professional Military Education", "Professional Military Education"),
                    ("Hazardous Materials", "Hazardous Materials"),
                    ("Flight Evaluator Training", "Flight Evaluator Training"),
                    ("Compressed Gas", "Compressed Gas Training"),
                    ("Tire Inflation", "Tire Inflation Training"),
                    ("ECS Cart", "ECS Cart Training"),
                    ("Overhead Hoist", "Overhead Hoist Training"),
                    ("Job Hazard Analysis", "Job Hazard Analysis Training"),
                    ("CPR Certification", "CPR Certification Training"),
                    ("Laser Safety", "Laser Safety Training"),
                    ("FOD Training", "Foreign Object and Debris Training"),
                    ("Evaluator Training", "AMTP Evaluator Training"),
                    ("Annual Corrosion", "Annual Corrosion Training"),
                    ("Other", "Other Training Type"),
                ],
                max_length=50,
                null=True,
                verbose_name="Training Type",
            ),
        ),
    ]
