# Generated by Django 4.2.2 on 2024-08-20 18:25

import django.db.models.deletion
from django.db import migrations, models

import forms.models
from forms.model_utils import AwardType as OldAwardType
from forms.model_utils import EvaluationType as OldEvaluationType
from forms.model_utils import EventType as OldEventType
from forms.model_utils import TCS_Locations as OldTCS_Locations
from forms.model_utils import TrainingType as OldTrainingType


def import_field_to_foreign_key(apps, schema_editor):
    DA_7817 = apps.get_model("forms", "DA_7817")
    AwardType = apps.get_model("forms", "AwardType")
    EvaluationType = apps.get_model("forms", "EvaluationType")
    EventType = apps.get_model("forms", "EventType")
    TrainingType = apps.get_model("forms", "TrainingType")
    TCSLocation = apps.get_model("forms", "TCSLocation")

    for da_7817 in DA_7817.objects.all():
        try:
            award_type, created = AwardType.objects.get_or_create(type=da_7817.legacy_award_type, description=OldAwardType(da_7817.legacy_award_type).label)
        except:
            award_type = None

        try:
            evaluation_type, created = EvaluationType.objects.get_or_create(type=da_7817.legacy_evaluation_type, description=OldEvaluationType(da_7817.legacy_evaluation_type).label)
        except:
            evaluation_type = None

        try:
            event_type, created = EventType.objects.get_or_create(type=da_7817.legacy_event_type, description=OldEventType(da_7817.legacy_event_type).label)
        except:
            event_type = forms.models.get_default_event_type()

        try:
            training_type, created = TrainingType.objects.get_or_create(type=da_7817.legacy_training_type, description=OldTrainingType(da_7817.legacy_training_type).label)
        except:
            training_type = None

        try:
            tcs_location, created = TCSLocation.objects.get_or_create(abbreviation=da_7817.legacy_tcs_location, location=OldTCS_Locations(da_7817.legacy_tcs_location).label)
        except:
            tcs_location = None

        da_7817.award_type = award_type
        da_7817.evaluation_type = evaluation_type
        da_7817.event_type = event_type
        da_7817.training_type = training_type
        da_7817.tcs_location = tcs_location

        da_7817.save()


def import_foreign_key_to_field(apps, schema_editor):
    DA_7817 = apps.get_model("forms", "DA_7817")

    for da_7817 in DA_7817.objects.all():
        try:
            if da_7817.award_type:
                award_type = da_7817.award_type.type
            else:
                award_type = None
            if award_type and award_type not in OldAwardType.values:
                award_type = None

            if da_7817.evaluation_type:
                evaluation_type = da_7817.evaluation_type.type
            else:
                evaluation_type = None
            if evaluation_type and evaluation_type not in OldEvaluationType.values:
                evaluation_type = None

            if da_7817.event_type:
                event_type = da_7817.event_type.type
            else:
                event_type = None
            if event_type and event_type not in OldEventType.values:
                event_type = OldEventType.Other.value

            if da_7817.training_type:
                training_type = da_7817.training_type.type
            else:
                training_type = None
            if training_type and training_type not in OldTrainingType.values:
                training_type = None

            if da_7817.tcs_location:
                tcs_location = da_7817.tcs_location.abbreviation
            else:
                tcs_location = None
            if tcs_location and tcs_location not in OldTCS_Locations.values:
                tcs_location = None
            
            da_7817.legacy_award_type = award_type
            da_7817.legacy_evaluation_type = evaluation_type
            da_7817.legacy_event_type = event_type
            da_7817.legacy_training_type = training_type
            da_7817.legacy_tcs_location = tcs_location

            da_7817.save()

        except:
            pass



class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0024_historicalda_4856_historicalda_7817_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Generated Unique Id")),
                ("type", models.CharField(max_length=64, verbose_name="Award Type")),
                ("description", models.CharField(max_length=128, verbose_name="Award Type Description", null=True, blank=True)),
            ],
            options={
                "db_table": "forms_award_type",
            },
        ),
        migrations.CreateModel(
            name="EvaluationType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Generated Unique Id")),
                ("type", models.CharField(max_length=64, verbose_name="Evaluation Type")),
                ("description", models.CharField(max_length=128, verbose_name="Evaluation Type Description", null=True, blank=True)),
            ],
            options={
                "db_table": "forms_evaluation_type",
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Generated Unique Id")),
                ("type", models.CharField(max_length=64, verbose_name="Event Type")),
                ("description", models.CharField(max_length=128, verbose_name="Event Type Description", null=True, blank=True)),
            ],
            options={
                "db_table": "forms_event_type",
            },
        ),
        migrations.CreateModel(
            name="TrainingType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Generated Unique Id")),
                ("type", models.CharField(max_length=64, verbose_name="Training Type")),
                ("description", models.CharField(max_length=128, verbose_name="Training Type Description", null=True, blank=True)),
            ],
            options={
                "db_table": "forms_training_type",
            },
        ),
        migrations.CreateModel(
            name="TCSLocation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Generated Unique Id")),
                ("abbreviation", models.CharField(max_length=64, verbose_name="Training Type")),
                (
                    "location",
                    models.CharField(blank=True, max_length=128, null=True, verbose_name="Training Type Description"),
                ),
            ],
            options={
                "db_table": "forms_tcs_location",
            },
        ),
        migrations.AddConstraint(
            model_name="trainingtype",
            constraint=models.UniqueConstraint(fields=("type",), name="unique_training_type"),
        ),
        migrations.AddConstraint(
            model_name="eventtype",
            constraint=models.UniqueConstraint(fields=("type",), name="unique_event_type"),
        ),
        migrations.AddConstraint(
            model_name="evaluationtype",
            constraint=models.UniqueConstraint(fields=("type",), name="unique_evaluation_type"),
        ),
        migrations.AddConstraint(
            model_name="awardtype",
            constraint=models.UniqueConstraint(fields=("type",), name="unique_award_type"),
        ),
        migrations.AddConstraint(
            model_name="tcslocation",
            constraint=models.UniqueConstraint(fields=("abbreviation", "location"), name="unique_tcs_location"),
        ),
        migrations.RenameField(
            model_name="da_7817",
            old_name="award_type",
            new_name="legacy_award_type",
        ),
        migrations.RenameField(
            model_name="da_7817",
            old_name="evaluation_type",
            new_name="legacy_evaluation_type",
        ),
        migrations.RenameField(
            model_name="da_7817",
            old_name="event_type",
            new_name="legacy_event_type",
        ),
        migrations.RenameField(
            model_name="da_7817",
            old_name="training_type",
            new_name="legacy_training_type",
        ),
        migrations.RenameField(
            model_name="historicalda_7817",
            old_name="award_type",
            new_name="legacy_award_type",
        ),
        migrations.RenameField(
            model_name="historicalda_7817",
            old_name="evaluation_type",
            new_name="legacy_evaluation_type",
        ),
        migrations.RenameField(
            model_name="historicalda_7817",
            old_name="event_type",
            new_name="legacy_event_type",
        ),
        migrations.RenameField(
            model_name="historicalda_7817",
            old_name="training_type",
            new_name="legacy_training_type",
        ),
        migrations.RenameField(
            model_name="da_7817",
            old_name="tcs_location",
            new_name="legacy_tcs_location",
        ),
        migrations.RenameField(
            model_name="historicalda_7817",
            old_name="tcs_location",
            new_name="legacy_tcs_location",
        ),
        migrations.AddField(
            model_name="da_7817",
            name="award_type",
            field=models.ForeignKey(
                blank=True,
                db_column="award_type",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="forms.awardtype",
            ),
        ),
        migrations.AddField(
            model_name="da_7817",
            name="evaluation_type",
            field=models.ForeignKey(
                blank=True,
                db_column="evaluation_type",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="forms.evaluationtype",
            ),
        ),
        migrations.AddField(
            model_name="da_7817",
            name="event_type",
            field=models.ForeignKey(
                db_column="event_type",
                default=forms.models.get_default_event_type,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="forms.eventtype",
            ),
        ),
        migrations.AddField(
            model_name="da_7817",
            name="training_type",
            field=models.ForeignKey(
                blank=True,
                db_column="training_type",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="forms.trainingtype",
            ),
        ),
        migrations.AddField(
            model_name="da_7817",
            name="tcs_location",
            field=models.ForeignKey(
                blank=True,
                db_column="tcs_location",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="forms.tcslocation",
            ),
        ),
        migrations.AddField(
            model_name="historicalda_7817",
            name="award_type",
            field=models.ForeignKey(
                blank=True,
                db_column="award_type",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="forms.awardtype",
            ),
        ),
        migrations.AddField(
            model_name="historicalda_7817",
            name="evaluation_type",
            field=models.ForeignKey(
                blank=True,
                db_column="evaluation_type",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="forms.evaluationtype",
            ),
        ),
        migrations.AddField(
            model_name="historicalda_7817",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                db_column="event_type",
                db_constraint=False,
                default=forms.models.get_default_event_type,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="forms.eventtype",
            ),
        ),
        migrations.AddField(
            model_name="historicalda_7817",
            name="training_type",
            field=models.ForeignKey(
                blank=True,
                db_column="training_type",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="forms.trainingtype",
            ),
        ),
        migrations.AddField(
            model_name="historicalda_7817",
            name="tcs_location",
            field=models.ForeignKey(
                blank=True,
                db_column="tcs_location",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="forms.tcslocation",
            ),
        ),
        migrations.RunPython(
            import_field_to_foreign_key, import_foreign_key_to_field
        ),
        migrations.RemoveField(
            model_name="da_7817",
            name="legacy_award_type",
        ),
        migrations.RemoveField(
            model_name="da_7817",
            name="legacy_evaluation_type",
        ),
        migrations.RemoveField(
            model_name="da_7817",
            name="legacy_event_type",
        ),
        migrations.RemoveField(
            model_name="da_7817",
            name="legacy_training_type",
        ),
        migrations.RemoveField(
            model_name="da_7817",
            name="legacy_tcs_location",
        ),
        migrations.RemoveField(
            model_name="historicalda_7817",
            name="legacy_award_type",
        ),
        migrations.RemoveField(
            model_name="historicalda_7817",
            name="legacy_evaluation_type",
        ),
        migrations.RemoveField(
            model_name="historicalda_7817",
            name="legacy_event_type",
        ),
        migrations.RemoveField(
            model_name="historicalda_7817",
            name="legacy_training_type",
        ),
        migrations.RemoveField(
            model_name="historicalda_7817",
            name="legacy_tcs_location",
        ),
    ]
