# Generated by Django 4.2.4 on 2024-09-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0021_remove_historicalsoldier_maintenance_level_and_more"),
        ("forms", "0025_awardtype_evaluationresult_evaluationtype_eventtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="da_7817",
            name="mos",
            field=models.ForeignKey(
                blank=True,
                db_column="specific_mos_event",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="personnel.moscode",
            ),
        ),
        migrations.AddField(
            model_name="historicalda_7817",
            name="mos",
            field=models.ForeignKey(
                blank=True,
                db_column="specific_mos_event",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="personnel.moscode",
            ),
        ),
    ]
