# Generated by Django 4.2.4 on 2024-10-14 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0023_alter_mos_mos_code"),
        ("personnel", "0021_remove_historicalsoldier_maintenance_level_and_more"),
        ("forms", "0027_da_7817_mass_entry_key_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DA_7817",
            new_name="Event",
        ),
        migrations.RenameModel(
            old_name="HistoricalDA_7817",
            new_name="HistoricalEvent",
        ),
    ]
