# Generated by Django 4.2.4 on 2024-10-14 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0028_rename_da_7817_event_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.AlterModelOptions(
            name="historicalevent",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Event",
                "verbose_name_plural": "historical Events",
            },
        ),
        migrations.AlterModelTable(
            name="event",
            table="forms_events",
        ),
    ]
