# Generated by Django 4.2.4 on 2024-10-24 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0022_designation_historicalsoldierdesignation_and_more"),
        ("forms", "0029_alter_event_options_alter_historicalevent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsupportingdocument",
            name="related_designation",
            field=models.ForeignKey(
                blank=True,
                db_column="soldier_designation_id",
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="personnel.soldierdesignation",
            ),
        ),
        migrations.AddField(
            model_name="supportingdocument",
            name="related_designation",
            field=models.ForeignKey(
                blank=True,
                db_column="soldier_designation_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_soldier_designation_id",
                to="personnel.soldierdesignation",
            ),
        ),
    ]
