# Generated by Django 4.2.2 on 2025-02-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0001_initial"),
        ("forms", "0030_historicalsupportingdocument_related_designation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="gaining_unit",
            field=models.ForeignKey(
                blank=True,
                db_column="gaining_unit_uic",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="soldier_pcs_records",
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="uic",
            field=models.ForeignKey(
                db_column="unit_uic",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="soldier_event_records",
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="gaining_unit",
            field=models.ForeignKey(
                blank=True,
                db_column="gaining_unit_uic",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="units.unit",
            ),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="uic",
            field=models.ForeignKey(
                blank=True,
                db_column="unit_uic",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="units.unit",
            ),
        ),
    ]
