# Generated by Django 4.2.4 on 2025-04-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0031_alter_event_gaining_unit_alter_event_uic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtasks",
            name="go_nogo",
            field=models.CharField(
                choices=[("GO", "Go - Passed Task"), ("NOGO", "No Go - Failed Task"), ("N/A", "Not Applicable")],
                default="N/A",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicaleventtasks",
            name="go_nogo",
            field=models.CharField(
                choices=[("GO", "Go - Passed Task"), ("NOGO", "No Go - Failed Task"), ("N/A", "Not Applicable")],
                default="N/A",
                max_length=10,
            ),
        ),
    ]
