# Generated by Django 4.2.2 on 2023-11-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auto_dsr", "0020_unit_nick_name"),
        ("aircraft", "0005_aircraft_current_unit_and_more"),
        ("agse", "0002_alter_agse_options_alter_agseedits_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsOrder",
            fields=[
                (
                    "dod_document_number",
                    models.CharField(
                        max_length=15, primary_key=True, serialize=False, verbose_name="DOD Document Number"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Shipment carrier ie. UPS/FEDEX"
                    ),
                ),
                (
                    "carrier_tracking_number",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="Carrier Tracking Number"),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="A boolean flag to track if a user wants to view this on their DSR"
                    ),
                ),
                (
                    "agse",
                    models.ForeignKey(
                        blank=True,
                        db_column="agse_equipment_number",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agse.agse",
                    ),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True,
                        db_column="aircraft_serial_number",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parts Orders",
            },
        ),
    ]
