# Generated by Django 3.2.6 on 2023-01-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "serial",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Aircraft Serial Number",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        max_length=16, verbose_name="Aircraft Mission Design Series"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FMC", "Fully Mission Capable"),
                            ("PMC", "Partially Mission Capable"),
                            ("PMCM", "Partially Mission Capable - Maintenance"),
                            ("PMCS", "Partially Mission Capable - Sustainment"),
                            ("NMC", "Non Mission Capable"),
                            ("NMCS", "Non Mission Capable - Supply"),
                            ("NMCM", "Non Mission Capable - Maintenance"),
                            ("FIELD", "Field"),
                            ("SUST", "Sustainment"),
                            ("DADE", "Department of the Army Directed Event"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=5,
                        verbose_name="Maintenance Status (FMC, NMC)",
                    ),
                ),
                (
                    "rtl",
                    models.CharField(
                        max_length=4, verbose_name="Ready to Launch Status (RTL, NRTL)"
                    ),
                ),
                (
                    "total_airframe_hours",
                    models.FloatField(
                        verbose_name="Lifetime Flight Hours for that Airframe"
                    ),
                ),
                (
                    "hours_to_phase",
                    models.FloatField(
                        verbose_name="Flight Hours Until Phase Inspection"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Displayed Aircraft Remarks",
                    ),
                ),
                (
                    "date_down",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date Aircraft Entered non-FMC status",
                    ),
                ),
                (
                    "ecd",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Estimated Completion Date for non-FMC Aircraft",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(verbose_name="Last Sync from ACN"),
                ),
            ],
            options={
                "db_table": "aircraft",
            },
        ),
        migrations.CreateModel(
            name="CanEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Day User Can Edit Aircraft Data",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Day User Can No Longer Edit Aircraft",
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        db_column="serial",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.aircraft",
                    ),
                ),
            ],
            options={
                "db_table": "can_edit",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Location Name"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Airport Code"
                    ),
                ),
                (
                    "mgrs",
                    models.CharField(
                        blank=True,
                        max_length=24,
                        null=True,
                        verbose_name="Military Grid Reference System",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "uic",
                    models.CharField(
                        max_length=9,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unit Identification Code",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(max_length=64, verbose_name="Unit Short Name"),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Unit Display Name",
                    ),
                ),
                (
                    "echelon",
                    models.CharField(
                        choices=[
                            ("PLT", "Platoon"),
                            ("CO", "Company"),
                            ("BN", "Battalion"),
                            ("BDE", "Brigade"),
                            ("DIV", "Division"),
                            ("CORPS", "Corps"),
                            ("MACOM", "Major Command"),
                            ("CNTR", "Center"),
                            ("ARMY", "Army"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=5,
                        verbose_name="Unit Echelon",
                    ),
                ),
                (
                    "parent_uic",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_uic",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "db_table": "units",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="EDIPI Number",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PV1", "Private"),
                            ("PV2", "Private"),
                            ("PFC", "Private First Class"),
                            ("SPC", "Specialist"),
                            ("CPL", "Corporal"),
                            ("SGT", "Sergeant"),
                            ("SSG", "Staff Sergeant"),
                            ("SFC", "Sergeant First Class"),
                            ("MSG", "Master Sergeant"),
                            ("1SG", "First Sergeant"),
                            ("SGM", "Sergeant Major"),
                            ("CSM", "Command Sergeant Major"),
                            ("SMA", "Sergeant Major of the Army"),
                            ("WO1", "Warrant Officer 1"),
                            ("CW2", "Chief Warrant Officer 2"),
                            ("CW3", "Chief Warrant Officer 3"),
                            ("CW4", "Chief Warrant Officer 4"),
                            ("CW5", "Chief Warrant Officer 5"),
                            ("2LT", "Second Lieutenant"),
                            ("1LT", "First Lieutenant"),
                            ("CPT", "Captain"),
                            ("MAJ", "Major"),
                            ("LTC", "Lieutenant Colonel"),
                            ("COL", "Colonel"),
                            ("BG", "Brigadier General"),
                            ("MG", "Major General"),
                            ("LTG", "Lieutenant General"),
                            ("GEN", "General"),
                            ("GA", "General of the Army"),
                            ("CTR", "Contractor"),
                            ("GS1", "GS-1"),
                            ("GS2", "GS-2"),
                            ("GS3", "GS-3"),
                            ("GS4", "GS-4"),
                            ("GS5", "GS-5"),
                            ("GS6", "GS-6"),
                            ("GS7", "GS-7"),
                            ("GS8", "GS-8"),
                            ("GS9", "GS-9"),
                            ("GS10", "GS-10"),
                            ("GS11", "GS-11"),
                            ("GS12", "GS-12"),
                            ("GS13", "GS-13"),
                            ("GS14", "GS-14"),
                            ("GS15", "GS-15"),
                            ("SES1", "SES-1"),
                            ("SES2", "SES-2"),
                            ("SES3", "SES-3"),
                            ("SES4", "SES-4"),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name="Rank",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=32, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=32, verbose_name="Last Name"),
                ),
                (
                    "can_edit",
                    models.ManyToManyField(
                        through="auto_dsr.CanEdit", to="auto_dsr.Aircraft"
                    ),
                ),
            ],
            options={
                "db_table": "clean_users",
            },
        ),
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        db_column="uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_requests",
            },
        ),
        migrations.CreateModel(
            name="UnitAircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        db_column="serial",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.aircraft",
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        db_column="uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "db_table": "unit_aircraft",
            },
        ),
        migrations.CreateModel(
            name="TaskForce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Task Force Mission Begin Date"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Task Force Mission End Date",
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        db_column="uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "db_table": "task_forces",
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=64, verbose_name="Settings Unique Id Key"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=128, verbose_name="The associated value"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.user",
                    ),
                ),
            ],
            options={
                "db_table": "settings",
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "inspection_name",
                    models.CharField(
                        max_length=64, verbose_name="Inpsection Display Name"
                    ),
                ),
                (
                    "last_conducted_hours",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Aircraft Hours When Last Conducted",
                    ),
                ),
                (
                    "hours_interval",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Maximum Flying Hours before Inspection",
                    ),
                ),
                (
                    "next_due_hours",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Aircraft Hours the Inspection must occur by",
                    ),
                ),
                (
                    "last_conducted_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date the inspection was last conducted on",
                    ),
                ),
                (
                    "day_interval",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Maximum Days before inspection",
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date the inspection must occur by",
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        blank=True,
                        db_column="serial",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auto_dsr.aircraft",
                    ),
                ),
            ],
            options={
                "db_table": "inspections",
            },
        ),
        migrations.AddField(
            model_name="canedit",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="auto_dsr.user",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_column="location_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auto_dsr.location",
            ),
        ),
        migrations.AddField(
            model_name="aircraft",
            name="uic",
            field=models.ManyToManyField(
                through="auto_dsr.UnitAircraft", to="auto_dsr.Unit"
            ),
        ),
    ]
