# Generated by Django 3.2.6 on 2023-01-15 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0002_auto_20230111_1820"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="flight_hours",
            field=models.FloatField(
                default=0.0, verbose_name="Hours Flown in the current reporting period"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="auto_dsr_users",
        ),
        migrations.CreateModel(
            name="UserAircraftRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "save_time",
                    models.DateTimeField(
                        verbose_name="The time the user saved this remark"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        max_length=2048,
                        verbose_name="User provided Remarks for a given Aircraft",
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        db_column="serial",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auto_dsr.aircraft",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auto_dsr.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_aircraft_remarks",
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "begin_time",
                    models.DateTimeField(
                        verbose_name="When the flight is expected to begin"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        verbose_name="When the flight is expected to end"
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        db_column="serial",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auto_dsr.aircraft",
                    ),
                ),
                (
                    "uic",
                    models.ForeignKey(
                        db_column="uic",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "db_table": "flights",
            },
        ),
        migrations.CreateModel(
            name="Faults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        max_length=2048, verbose_name="Fault Remarks from ACN"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("X", "Deadline"),
                            ("O", "Commander Underwritten Deadline"),
                            ("/", "Non-deadlining Fault"),
                            ("U", "Unknown or Unspecified"),
                        ],
                        default="U",
                        max_length=10,
                        verbose_name="Severity Code",
                    ),
                ),
                (
                    "open_date",
                    models.DateField(verbose_name="Date the fault was identified"),
                ),
                (
                    "open",
                    models.BooleanField(
                        verbose_name="Flag indicating if the fault is still open"
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        db_column="serial",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auto_dsr.aircraft",
                    ),
                ),
            ],
            options={
                "db_table": "faults",
            },
        ),
        migrations.CreateModel(
            name="AircraftEditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "effective_time",
                    models.DateTimeField(
                        verbose_name="The timestamp when a user made this edit"
                    ),
                ),
                (
                    "edited_column",
                    models.CharField(
                        max_length=32, verbose_name="The column edited by the user"
                    ),
                ),
                (
                    "lock_edit",
                    models.BooleanField(
                        verbose_name="A flag to keep track of if this column should be locked (not updated when a new ACN update is made)"
                    ),
                ),
                (
                    "record",
                    models.JSONField(
                        verbose_name="The column's previous and newly edited value"
                    ),
                ),
                (
                    "serial",
                    models.ForeignKey(
                        db_column="serial",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auto_dsr.aircraft",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auto_dsr.user",
                    ),
                ),
            ],
            options={
                "db_table": "aircraft_edit_log",
            },
        ),
    ]
