# Generated by Django 3.2.6 on 2023-01-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0003_auto_20230115_2250"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Faults",
            new_name="Fault",
        ),
        migrations.AlterModelOptions(
            name="aircraft",
            options={"verbose_name_plural": "aircraft"},
        ),
        migrations.AlterModelOptions(
            name="canedit",
            options={"verbose_name_plural": "can edit aircraft"},
        ),
        migrations.AlterModelOptions(
            name="useraircraftremark",
            options={"verbose_name_plural": "user aircraft remarks"},
        ),
        migrations.AddField(
            model_name="useraircraftremark",
            name="lock_remark",
            field=models.BooleanField(
                default=True,
                verbose_name="A flag to identify if this column should persist through ACN updates",
            ),
            preserve_default=False,
        ),
    ]
