# Generated by Django 3.2.6 on 2023-01-29 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0004_auto_20230118_2225"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="length",
            field=models.FloatField(
                default=0.0, verbose_name="How long the flight is expected to last for"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flight",
            name="end_time",
            field=models.DateTimeField(
                null=True, verbose_name="When the flight is expected to end"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="serial",
            field=models.ForeignKey(
                blank=True,
                db_column="serial",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auto_dsr.aircraft",
            ),
        ),
    ]
