# Generated by Django 3.2.6 on 2023-03-21 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0006_auto_20230321_1318"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="phase",
            table="phases",
        ),
    ]
