# Generated by Django 4.2.2 on 2023-09-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0016_unitphaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='child_uics',
            field=models.JSONField(default=list, verbose_name='A list of all immediate child uics to this unit.'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent_uics',
            field=models.JSONField(default=list, verbose_name='A list of all uics over this one in the hierarchy.'),
        ),
        migrations.AddField(
            model_name='unit',
            name='subordinate_uics',
            field=models.JSONField(default=list, verbose_name='A list of all uics subordinate to this one.'),
        ),
    ]
