# Generated by Django 4.2.2 on 2023-09-11 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0017_unit_child_uics_unit_parent_uics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskforce",
            name="readiness_uic",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="readiness_uic",
                to="auto_dsr.unit",
            ),
        ),
    ]
