# Generated by Django 4.2.2 on 2024-02-12 14:23

import auto_dsr.model_utils.acd_export_upload
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auto_dsr", "0021_alter_unit_echelon"),
    ]

    operations = [
        migrations.CreateModel(
            name="ACDExport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                ("uploaded_at", models.DateTimeField(verbose_name="The timestamp when this file was uploaded")),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        upload_to=auto_dsr.model_utils.acd_export_upload.acd_export_upload_to,
                        verbose_name="Uploaded ACD Export File",
                    ),
                ),
                (
                    "succeeded",
                    models.BooleanField(
                        default=False, verbose_name="A Boolean flag indicating if the upload succeeded"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.unit"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_dodid", on_delete=django.db.models.deletion.DO_NOTHING, to="auto_dsr.user"
                    ),
                ),
            ],
            options={
                "db_table": "auto_dsr_acd_exports",
            },
        ),
    ]
