# Generated by Django 4.2.2 on 2024-06-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uas", "0003_uac_should_sync_uav_should_sync"),
        ("aircraft", "0019_flight_flight_id"),
        ("auto_dsr", "0024_rename_user_id_usersetting_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectTransferRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "requested_object_type",
                    models.CharField(
                        choices=[("AIR", "Aircraft"), ("UAC", "UAC"), ("UAV", "UAV")],
                        max_length=5,
                        verbose_name="The type of object being requested",
                    ),
                ),
                (
                    "originating_unit_approved",
                    models.BooleanField(
                        default=False,
                        verbose_name="Boolean indicating if the originating unit has approved the transfer",
                    ),
                ),
                (
                    "destination_unit_approved",
                    models.BooleanField(
                        default=False,
                        verbose_name="Boolean indicating if the destination unit has approved the transfer",
                    ),
                ),
                (
                    "permanent_transfer",
                    models.BooleanField(
                        default=False,
                        verbose_name="Boolean indicating if the transfer will remove instances of other units tracking on the originating unit hierarchy.",
                    ),
                ),
                ("date_requested", models.DateField(verbose_name="Date the Transfer Request was created")),
                (
                    "destination_unit",
                    models.ForeignKey(
                        db_column="destination_unit_uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_object_transfer_requests",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "originating_unit",
                    models.ForeignKey(
                        db_column="originating_unit_uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_object_transfer_requests",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "requested_aircraft",
                    models.OneToOneField(
                        blank=True,
                        db_column="requested_aircraft_serial_number",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "requested_by_user",
                    models.ForeignKey(
                        db_column="requsted_by_user_id", on_delete=django.db.models.deletion.CASCADE, to="auto_dsr.user"
                    ),
                ),
                (
                    "requested_uac",
                    models.OneToOneField(
                        blank=True,
                        db_column="requested_uac_serial_number",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uas.uac",
                    ),
                ),
                (
                    "requested_uav",
                    models.OneToOneField(
                        blank=True,
                        db_column="requested_uav_serial_number",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uas.uav",
                    ),
                ),
            ],
            options={
                "db_table": "auto_dsr_object_transfer_requests",
            },
        ),
        migrations.CreateModel(
            name="ObjectTransferLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="Auto Unique Id")),
                (
                    "requested_object_type",
                    models.CharField(
                        choices=[("AIR", "Aircraft"), ("UAC", "UAC"), ("UAV", "UAV")],
                        max_length=5,
                        verbose_name="The type of object being requested",
                    ),
                ),
                (
                    "permanent_transfer",
                    models.BooleanField(verbose_name="Boolean indicating if the transfer was permanent"),
                ),
                ("date_requested", models.DateField(verbose_name="Date the Transfer Request was created")),
                ("decision_date", models.DateField(verbose_name="Date the request was either approved or denied")),
                (
                    "transfer_approved",
                    models.BooleanField(
                        verbose_name="Boolean indicating if the object transfer was approved or denied"
                    ),
                ),
                (
                    "destination_unit",
                    models.ForeignKey(
                        db_column="destination_unit_uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_object_transfer_request_log",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "originating_unit",
                    models.ForeignKey(
                        db_column="originating_unit_uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_object_transfer_request_log",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "requested_aircraft",
                    models.ForeignKey(
                        blank=True,
                        db_column="requested_aircraft_serial_number",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "requested_uac",
                    models.ForeignKey(
                        blank=True,
                        db_column="requested_uac_serial_number",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uas.uac",
                    ),
                ),
                (
                    "requested_uav",
                    models.ForeignKey(
                        blank=True,
                        db_column="requested_uav_serial_number",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uas.uav",
                    ),
                ),
            ],
            options={
                "db_table": "auto_dsr_object_transfer_log",
            },
        ),
    ]
