# Generated by Django 4.2.2 on 2024-06-10 13:57

from django.db import migrations


def migrate_from_aircraft_to_object_transfers(apps, schema_editor):
    AircraftTransferRequest = apps.get_model("aircraft", "AircraftTransferRequest")
    ObjectTransferRequest = apps.get_model("auto_dsr", "ObjectTransferRequest")

    for aircraft_transfer_object in AircraftTransferRequest.objects.all():
        try:
            ObjectTransferRequest.objects.get_or_create(
                requested_aircraft=aircraft_transfer_object.requested_aircraft,
                requested_object_type="AIR",
                originating_unit=aircraft_transfer_object.originating_unit,
                originating_unit_approved=aircraft_transfer_object.originating_unit_approved,
                destination_unit=aircraft_transfer_object.destination_unit,
                destination_unit_approved=aircraft_transfer_object.destination_unit_approved,
                requested_by_user=aircraft_transfer_object.requested_by_user,
                permanent_transfer=aircraft_transfer_object.permanent_transfer,
                date_requested=aircraft_transfer_object.date_requested,
            )
        except:
            pass


def reverse_from_object_transfers_to_aircraft_transfers(apps, schema_editor):
    AircraftTransferRequest = apps.get_model("aircraft", "AircraftTransferRequest")
    ObjectTransferRequest = apps.get_model("auto_dsr", "ObjectTransferRequest")

    for object_transfer_object in ObjectTransferRequest.objects.all():
        if object_transfer_object.requested_object_type == "AIR":
            try:
                AircraftTransferRequest.objects.get_or_create(
                    requested_aircraft=object_transfer_object.requested_aircraft,
                    originating_unit=object_transfer_object.originating_unit,
                    originating_unit_approved=object_transfer_object.originating_unit_approved,
                    destination_unit=object_transfer_object.destination_unit,
                    destination_unit_approved=object_transfer_object.destination_unit_approved,
                    requested_by_user=object_transfer_object.requested_by_user,
                    permanent_transfer=object_transfer_object.permanent_transfer,
                    date_requested=object_transfer_object.date_requested,
                )
            except:
                pass

def migrate_from_aircraft_log_to_object_log(apps, schema_editor):
    AircraftTransferLog = apps.get_model("aircraft", "AircraftTransferLog")
    ObjectTransferLog = apps.get_model("auto_dsr", "ObjectTransferLog")

    for aircraft_transfer_log in AircraftTransferLog.objects.all():
        try:
            ObjectTransferLog.objects.get_or_create(
                requested_aircraft=aircraft_transfer_log.requested_aircraft,
                requested_object_type="AIR",
                originating_unit=aircraft_transfer_log.originating_unit,
                destination_unit=aircraft_transfer_log.destination_unit,
                permanent_transfer=aircraft_transfer_log.permanent_transfer,
                date_requested=aircraft_transfer_log.date_requested,
                decision_date=aircraft_transfer_log.decision_date,
                transfer_approved=aircraft_transfer_log.transfer_approved
            )
        except:
            pass


def reverse_from_object_log_to_aircraft_log(apps, schema_editor):
    AircraftTransferLog = apps.get_model("aircraft", "AircraftTransferLog")
    ObjectTransferLog = apps.get_model("auto_dsr", "ObjectTransferLog")

    for object_transfer_log in ObjectTransferLog.objects.all():
        if object_transfer_log.requested_object_type == "AIR":
            try:
                AircraftTransferLog.objects.get_or_create(
                requested_aircraft=object_transfer_log.requested_aircraft,
                originating_unit=object_transfer_log.originating_unit,
                destination_unit=object_transfer_log.destination_unit,
                permanent_transfer=object_transfer_log.permanent_transfer,
                date_requested=object_transfer_log.date_requested,
                decision_date=object_transfer_log.decision_date,
                transfer_approved=object_transfer_log.transfer_approved
                )
            except:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0025_objecttransferrequest_objecttransferlog"),
    ]

    operations = [
        migrations.RunPython(
            migrate_from_aircraft_to_object_transfers, reverse_from_object_transfers_to_aircraft_transfers
        ),
        migrations.RunPython(
            migrate_from_aircraft_log_to_object_log, reverse_from_object_log_to_aircraft_log
        )
    ]
