# Generated by Django 5.0.1 on 2024-07-04 12:21

import auto_dsr.model_utils.logo_upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0026_auto_20240610_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=auto_dsr.model_utils.logo_upload_to.unit_logo_upload_to, verbose_name='Unit logo'),
        ),
    ]
