# Generated by Django 5.0.1 on 2024-07-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0027_unit_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_edit',
        ),
        migrations.DeleteModel(
            name='CanEdit',
        ),
    ]
