# Generated by Django 3.2.6 on 2023-03-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManualInspection",
            fields=[
                (
                    "serial",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Aircraft for Inspection Serial Number",
                    ),
                ),
                (
                    "insp_1",
                    models.FloatField(
                        null=True,
                        verbose_name="Airframe hours when the First inspection type for this model is due",
                    ),
                ),
                (
                    "insp_2",
                    models.FloatField(
                        null=True,
                        verbose_name="Airframe hours when the Second inspection type for this model is due",
                    ),
                ),
                (
                    "insp_3",
                    models.FloatField(
                        null=True,
                        verbose_name="Airframe hours when the Third inspection type for this model is due",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "RawManualInspections",
                "db_table": "raw_manual_inspections",
            },
        ),
    ]
