# Generated by Django 3.2.6 on 2023-03-29 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("raw_schema", "0002_manualuicoverride"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manualuicoverride",
            options={"verbose_name_plural": "RawManualUICOverride"},
        ),
        migrations.AlterModelTable(
            name="manualuicoverride",
            table="raw_manual_uic_override",
        ),
    ]
