# Generated by Django 4.2.2 on 2023-10-18 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auto_dsr", "0018_taskforce_readiness_uic"),
    ]

    operations = [
        migrations.CreateModel(
            name="UAC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=32, verbose_name="Serial Number"),
                ),
                (
                    "model",
                    models.CharField(
                        max_length=16, verbose_name="Mission Design Series"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FMC", "Fully Mission Capable"),
                            ("PMC", "Partially Mission Capable"),
                            ("PMCM", "Partially Mission Capable - Maintenance"),
                            ("PMCS", "Partially Mission Capable - Sustainment"),
                            ("NMC", "Non Mission Capable"),
                            ("NMCS", "Non Mission Capable - Supply"),
                            ("NMCM", "Non Mission Capable - Maintenance"),
                            ("FIELD", "Field"),
                            ("SUST", "Sustainment"),
                            ("DADE", "Department of the Army Directed Event"),
                            ("MTF", "Maintenance Test Flight"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=5,
                        verbose_name="Maintenance Status (FMC, NMC)",
                    ),
                ),
                (
                    "rtl",
                    models.CharField(
                        max_length=4, verbose_name="Ready to Launch Status (RTL, NRTL)"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Displayed UAC Remarks",
                    ),
                ),
                (
                    "date_down",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date UAC Entered non-FMC status",
                    ),
                ),
                (
                    "ecd",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Estimated Completion Date for non-FMC UACs",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(verbose_name="Last Sync from ACN"),
                ),
                (
                    "last_update_time",
                    models.DateTimeField(
                        verbose_name="Last Edit to this component made in Griffin"
                    ),
                ),
                (
                    "current_unit",
                    models.ForeignKey(
                        db_column="current_unit_uic",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="currently_assigned_uacs",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auto_dsr.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unmanned Aerial Component",
                "verbose_name_plural": "Unmanned Aerial Components",
            },
        ),
        migrations.CreateModel(
            name="UAV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="Auto Unique Id"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=32, verbose_name="Serial Number"),
                ),
                (
                    "model",
                    models.CharField(
                        max_length=16, verbose_name="Mission Design Series"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FMC", "Fully Mission Capable"),
                            ("PMC", "Partially Mission Capable"),
                            ("PMCM", "Partially Mission Capable - Maintenance"),
                            ("PMCS", "Partially Mission Capable - Sustainment"),
                            ("NMC", "Non Mission Capable"),
                            ("NMCS", "Non Mission Capable - Supply"),
                            ("NMCM", "Non Mission Capable - Maintenance"),
                            ("FIELD", "Field"),
                            ("SUST", "Sustainment"),
                            ("DADE", "Department of the Army Directed Event"),
                            ("MTF", "Maintenance Test Flight"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=5,
                        verbose_name="Maintenance Status (FMC, NMC)",
                    ),
                ),
                (
                    "rtl",
                    models.CharField(
                        max_length=4, verbose_name="Ready to Launch Status (RTL, NRTL)"
                    ),
                ),
                (
                    "total_airframe_hours",
                    models.FloatField(
                        verbose_name="Lifetime Flight Hours for that Airframe"
                    ),
                ),
                (
                    "flight_hours",
                    models.FloatField(
                        default=0.0,
                        verbose_name="Hours Flown in the current reporting period",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Displayed UAV Remarks",
                    ),
                ),
                (
                    "date_down",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date UAV Entered non-FMC status",
                    ),
                ),
                (
                    "ecd",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Estimated Completion Date for non-FMC UAVs",
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(verbose_name="Last Sync from ACN"),
                ),
                (
                    "last_update_time",
                    models.DateTimeField(
                        verbose_name="Last Edit to this vehicle made in Griffin"
                    ),
                ),
                (
                    "current_unit",
                    models.ForeignKey(
                        db_column="current_unit_uic",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="currently_assigned_uavs",
                        to="auto_dsr.unit",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_column="location_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auto_dsr.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unmanned Aerial Vehicle",
                "verbose_name_plural": "Unmanned Aerial Vehicles",
            },
        ),
        migrations.CreateModel(
            name="UnitUAV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="UnitUAV Unique ID",
                    ),
                ),
                (
                    "uav",
                    models.ForeignKey(
                        db_column="uav_serial_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uas.uav",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "db_table": "uas_unit_uav",
            },
        ),
        migrations.CreateModel(
            name="UnitUAC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="UnitUAC Unique ID",
                    ),
                ),
                (
                    "uac",
                    models.ForeignKey(
                        db_column="uac_serial_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="uas.uac",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        db_column="unit_uic",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "db_table": "uas_unit_uac",
            },
        ),
        migrations.AddField(
            model_name="uav",
            name="tracked_by_unit",
            field=models.ManyToManyField(
                related_name="tracked_uavs", through="uas.UnitUAV", to="auto_dsr.unit"
            ),
        ),
        migrations.AddField(
            model_name="uac",
            name="tracked_by_unit",
            field=models.ManyToManyField(
                related_name="tracked_uacs", through="uas.UnitUAC", to="auto_dsr.unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="unituav",
            constraint=models.UniqueConstraint(
                fields=("uav", "unit"), name="uav_in_unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="unituac",
            constraint=models.UniqueConstraint(
                fields=("uac", "unit"), name="uac_in_unit"
            ),
        ),
    ]
