# Generated by Django 4.2.2 on 2024-06-29 19:54

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_dsr", "0026_auto_20240610_0957"),
        ("uas", "0004_historicaluav_historicaluac"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluav",
            name="history_user",
        ),
        migrations.AddField(
            model_name="historicaluav",
            name="history_user_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalUnitUAV",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="UnitUAV Unique ID")),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to="uas.historicaluav"
                    ),
                ),
                (
                    "uav",
                    models.ForeignKey(
                        blank=True,
                        db_column="uav_serial_number",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="uas.uav",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="unit_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalUnitUAV",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUnitUAC",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True, verbose_name="UnitUAC Unique ID")),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to="uas.historicaluac"
                    ),
                ),
                (
                    "uac",
                    models.ForeignKey(
                        blank=True,
                        db_column="uac_serial_number",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="uas.uac",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="unit_uic",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auto_dsr.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalUnitUAC",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
