# Generated by Django 4.2.2 on 2024-06-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uas", "0005_remove_historicaluav_history_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluac",
            name="history_user",
        ),
        migrations.AddField(
            model_name="historicaluac",
            name="history_user_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
