# Generated by Django 5.0.1 on 2024-07-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_dsr', '0031_merge_20240725_1331'),
        ('uas', '0007_flight_flight_unique_flight_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='uac',
            index=models.Index(fields=['serial_number', 'model'], name='uas_uac_serial__f25a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='uav',
            index=models.Index(fields=['serial_number'], name='uas_uav_serial__e16f99_idx'),
        ),
    ]
