# Generated by Django 4.2.2 on 2024-08-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uas", "0008_uac_uas_uac_serial__f25a6b_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluac",
            name="field_sync_status",
            field=models.JSONField(default=dict, verbose_name="Defines whether individual fields should update"),
        ),
        migrations.AddField(
            model_name="historicaluav",
            name="field_sync_status",
            field=models.JSONField(default=dict, verbose_name="Defines whether individual fields should update"),
        ),
        migrations.AddField(
            model_name="uac",
            name="field_sync_status",
            field=models.JSONField(default=dict, verbose_name="Defines whether individual fields should update"),
        ),
        migrations.AddField(
            model_name="uav",
            name="field_sync_status",
            field=models.JSONField(default=dict, verbose_name="Defines whether individual fields should update"),
        ),
    ]
